### ISSUE TITLE
SequelizeUniqueConstraintError: Validation error

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#1066]
```
[2016-11-12 13:46:29]   [chunri-mein-lagga-daag-1844-313-4859-sage-50-tech-support-phone-number-sage-technical-support-phone-number] start unpublished 0 versions from local cnpm registry
[2016-11-12 13:46:29] [c#0] [error] [chunri-mein-lagga-daag-1844-313-4859-sage-50-tech-support-phone-number-sage-technical-support-phone-number] sync error: SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/home/www/git/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/query.js:149:14)
    at Query._callback (/home/www/git/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/home/www/git/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
    at Query.ErrorPacket (/home/www/git/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/home/www/git/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/www/git/cnpmjs.org/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/home/www/git/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/www/git/cnpmjs.org/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)

```

**Comment by fengmk2** [comment]
npm 牛皮癣，已经被官方删除，但是我们的同步逻辑有问题，name 太长就报了数据库错误。

**Comment by lucaszhu2zgf** [comment]
但现在还是很容易出现这个问题

**Comment by chuckchen314** [comment]
Hi，我使用的是2.19.4版本建立服务，在同步ionic的时候，报同样的错，具体怎么处理呢？
错误如下：
[2018-03-29 19:00:05]     [cordova:231] sync error, version: 7.0.2-nightly.2017.7.29.596da5df, SequelizeDatabaseError: SequelizeDatabaseError: ER_DATA_TOO_LONG: Data too long for column 'version' at row 1
    at Query.formatError (/home/admin/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/home/admin/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/home/admin/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (/home/admin/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/home/admin/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/admin/cnpmjs.org/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/admin/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket. (/home/admin/cnpmjs.org/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
