### ISSUE TITLE
cnpm private registry can't install module its registed 

### ISSUE THREAD

**Issue by johnnychen** [cnpm/cnpmjs.org#1080]
https://github.com/cnpm/cnpmjs.org/wiki/Deploy-a-private-npm-registry-in-5-minutes

按照上述教程快速搭建并发布了自己的私有模块@cathay/cnpm-test，但无法安装该模块：

其中模块信息:

```js
{ name: '@cathay/cnpm-test',
  description: 'cnpm-test desc',
  'dist-tags': { latest: '1.0.0' },
  maintainers: [ 'myname <johnnychq@gmail.com>' ],
  time: 
   { modified: '2016-11-27T08:36:12.162Z',
     created: '2016-11-27T08:36:12.149Z',
     '1.0.0': '2016-11-27T08:36:12.149Z' },
  users: {},
  author: 'johnnychen',
  versions: [ '1.0.0' ],
  license: 'ISC',
  version: '1.0.0',
  main: 'index.js',
  scripts: { test: 'echo "Error: no test specified" && exit 1' },
  keywords: [ 'test' ],
  dist: 
   { shasum: '7270c137a478ebb71386e41edd32811c908a1082',
     size: 284,
     key: '/@cathay/cnpm-test/-/@cathay/cnpm-test-1.0.0.tgz',
     tarball: 'http://r.cnpmjs.org/@cathay/cnpm-test/download/@cathay/cnpm-test-1.0.0.tgz' },
  publish_time: 1480235772149 }
```

安装时的报错：(cnpm install @cathay/cnpm-test)

```
cnpm install @cathay/cnpm-test
⠧ Installing @cathay/cnpm-test@*Error: GET http://r.cnpmjs.org/@cathay/cnpm-test/download/@cathay/cnpm-test-1.0.0.tgz response 404 status
    at get (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/get.js:49:17)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:65:19)
npminstall version: 2.13.2
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/johnnychq/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://localhost:7001/ @cathay/cnpm-test
```

疑问：cnpm set registry http://localhost:7001 运行后所有cnpm的注册和模块下载都会走local registry把？其中public模块会自动代理到cnpm官方registry?

**Comment by gondgnay** [comment]
解决了吗？

**Comment by johnnychen** [comment]
没有，你遇到同样问题了？

**Comment by flyfly6** [comment]
我也遇到了这个问题，
可以参考https://github.com/cnpm/cnpmjs.org/issues/1065#issuecomment-260531747设置一下registryHost，指定模块下载地址

**Comment by johnnychen** [comment]
此问题如@flyfly6所回答，需要手动配置下`registryHost`，譬如 http://yourIP:7001 即可。

但，无法采用5分钟教程命令行传参的方式启动应用程序，必须通过定义一个配置文件，配置文件中声明registryHost指向。

原因是，5分钟教程中的命令行传参只支持部分参数，registryHost就不支持，会报如下错误
```
cnpmjs.org start --admins='myname,othername' \
  --registryHost='10.167.11.65:7001' \
  --scopes='@my-company-name,@other-name'

error: unknown option `--registryHost'
```
