### ISSUE TITLE
tunneling socket could not be established----, statusCode=403 (req "error")

### ISSUE THREAD

**Issue by lucaszhu2zgf** [cnpm/cnpmjs.org#1133]
在公司局域网里面部署cnpmjs，通过代理同步包，但在服务器上telnet这种出错的url的时候，返回的明明是302，但tunnel-agent会说403，直接报错了

**Comment by louiszhu2zgf** [comment]
[2017-02-28 15:37:16.933][8659] [sync_module_worker] downloading "http://registry.npm.taobao.org/mkdirp/download/mkdirp-0.0.2.tgz" to "/home/wnpm/.cnpmjs.org/downloads/mkdirp-0.0.2.a90918b79ac7649cb0448fafd2397e53.tgz"
[2017-02-28 15:37:17.014][8659] [sync_module_worker] download "http://registry.npm.taobao.org/mkdirp/download/mkdirp-0.0.2.tgz" to "/home/wnpm/.cnpmjs.org/downloads/mkdirp-0.0.2.a90918b79ac7649cb0448fafd2397e53.tgz" error: RequestError: tunneling socket could not be established----, statusCode=403 (req "error"), GET http://registry.npm.taobao.org/mkdirp/download/mkdirp-0.0.2.tgz -1 (connected: false, keepalive socket: false)
headers: {}

**Comment by fengmk2** [comment]
`tunneling socket could not be established` 没法通过你提供的 tunneling 进行数据同步

**Comment by louiszhu2zgf** [comment]
但我已经配置了httpproxy啊

**Comment by louiszhu2zgf** [comment]
是不是还有其他配置

**Comment by louiszhu2zgf** [comment]
var worker = new SyncModuleWorker({
    username: 'admin',
    name: packages,
    concurrency: config.syncConcurrency,    ===>1
    syncUpstreamFirst: false,
  });

**Comment by fengmk2** [comment]
你的 httpProxy 需要授权才能使用？httpProxy 我没有使用过，不确保能够长期可用 https://github.com/cnpm/cnpmjs.org/blob/74e9bdde725791cf63b45f8804815da7eb8f6ca7/common/urllib.js#L26

**Comment by fengmk2** [comment]
而且 npm install 不仅仅是到 registry 下载 pkg，在 install 过程还会执行 post script，它会去外网下载 node binary的，如 fsevents 和 node-sass，这些模块你这种模式就没法worked了

**Comment by louiszhu2zgf** [comment]
内网已经开了策略了，我用的同步策略是exist，上面worker是在sync/snyc_exist.js里面的，是默认配置，我没有改。而且worker会疯狂访问代理，有时候端口都占满了

**Comment by louiszhu2zgf** [comment]
[Tue Feb 28 2017 16:19:57 GMT+0800 (CST)] [worker:22206] new worker start
[Tue Feb 28 2017 16:19:57 GMT+0800 (CST)] [worker:22212] new worker start
[Tue Feb 28 2017 16:19:57 GMT+0800 (CST)] [worker:22218] new worker start
[Tue Feb 28 2017 16:19:57 GMT+0800 (CST)] [worker:22223] new worker start
[Tue Feb 28 2017 16:19:57 GMT+0800 (CST)] [worker:22230] new worker start
[Tue Feb 28 2017 16:19:57 GMT+0800 (CST)] [worker:22236] new worker start
[Tue Feb 28 2017 16:19:57 GMT+0800 (CST)] [worker:22242] new worker start
[Tue Feb 28 2017 16:19:57 GMT+0800 (CST)] [worker:22248] new worker start
[Tue Feb 28 2017 16:19:57 GMT+0800 (CST)] [worker:22254] new worker start
[Tue Feb 28 2017 16:19:57 GMT+0800 (CST)] [worker:22260] new worker start
[Tue Feb 28 2017 16:19:57 GMT+0800 (CST)] [worker:22266] new worker start
[Tue Feb 28 2017 16:19:57 GMT+0800 (CST)] [worker:22272] new worker start
[Tue Feb 28 2017 16:19:57 GMT+0800 (CST)] [worker:22278] new worker start
[Tue Feb 28 2017 16:19:57 GMT+0800 (CST)] [worker:22284] new worker start
[Tue Feb 28 2017 16:19:57 GMT+0800 (CST)] [worker:22290] new worker start
[Tue Feb 28 2017 16:19:57 GMT+0800 (CST)] [worker:22296] new worker start

**Comment by louiszhu2zgf** [comment]
而且我手动同步的时候明明前面的已经成功了，后面的又失败了[2017-02-28 16:20:34] user: anonymous, sync vue worker start, 1 concurrency, nodeps: false, publish: false
[2017-02-28 16:20:34] ----------------- Syncing upstream https://registry.npm.taobao.org/vue/sync/log/2506846 -------------------
[2017-02-28 16:20:35] [2017-02-28 16:20:34] user: anonymous, sync vue worker start, 1 concurrency, nodeps: false, publish: false
[2017-02-28 16:20:37] [2017-02-28 16:20:35] ----------------- Syncing upstream https://r.cnpmjs.org/vue/sync/log/1504217 -------------------
[2017-02-28 16:20:39] [2017-02-28 16:20:37] [2017-02-28 16:20:35] user: anonymous, sync vue worker start, 1 concurrency, nodeps: false, publish: false
[2017-02-28 16:20:35] ----------------- Syncing vue -------------------
[2017-02-28 16:20:36] [c#0] [vue] package(https://replicate.npmjs.com/vue) status: 200, dist-tags: {"latest":"2.2.1","csp":"1.0.28-csp","beta":"2.2.0-beta.2"}, time.modified: 2017-02-26T13:10:58.636Z, unpublished: null, start...
[2017-02-28 16:20:37]   [vue] found 0 missing star users
[2017-02-28 16:20:37]   [vue] all versions are exists
[2017-02-28 16:20:37]   [vue] no versions need to deleted
[2017-02-28 16:20:37]   [vue] all 116 npm users exists
[2017-02-28 16:20:37] [c#0] [vue] synced success, 0 versions: 
[2017-02-28 16:20:37] ----------------- Synced vue success -------------------
[2017-02-28 16:20:37] [Upstream done] Sync vue package finished, 1 success, 0 fail
Success: [ vue ]
Fail: [  ]
[2017-02-28 16:20:37] ----------------- Synced upstream https://r.cnpmjs.org/vue/sync/log/1504217 -------------------
[2017-02-28 16:20:37] ----------------- Syncing vue -------------------
[2017-02-28 16:20:39] [c#0] [vue] package(https://r.cnpmjs.org/vue) status: 200, dist-tags: {"beta":"2.2.0-beta.2","csp":"1.0.28-csp","latest":"2.2.1"}, time.modified: 2017-02-26T13:21:11.000Z, start...
[2017-02-28 16:20:39]   [vue] found 0 missing star users
[2017-02-28 16:20:39]   [vue] all versions are exists
[2017-02-28 16:20:39]   [vue] no versions need to deleted
[2017-02-28 16:20:39]   [vue] all 116 npm users exists
[2017-02-28 16:20:39] [c#0] [vue] synced success, 0 versions: 
[2017-02-28 16:20:39] ----------------- Synced vue success -------------------
[2017-02-28 16:20:39] [Upstream done] Sync vue package finished, 1 success, 0 fail
Success: [ vue ]
Fail: [  ]
[2017-02-28 16:20:39] ----------------- Synced upstream https://registry.npm.taobao.org/vue/sync/log/2506846 -------------------
[2017-02-28 16:20:39] ----------------- Syncing vue -------------------
[2017-02-28 16:20:40] [c#0] [vue] package(https://registry.npm.taobao.org/vue) status: 200, dist-tags: {"beta":"2.2.0-beta.2","csp":"1.0.28-csp","latest":"2.2.1"}, time.modified: 2017-02-26T13:21:15.000Z, unpublished: null, start...
[2017-02-28 16:20:40]   [vue] found 0 missing star users
[2017-02-28 16:20:40]   [vue] 195 versions need to sync
[2017-02-28 16:20:40]     [vue:0] syncing, delay: 101873452520 ms, version: 0.0.0, dist: {"shasum":"02a9248eb4a26ebc2bbf834f6db630af725ff258","size":261,"noattachment":false,"tarball":"http://registry.npm.taobao.org/vue/download/vue-0.0.0.tgz"}, no deps: false, publish on cnpm: false, dependencies: 0, devDependencies: 0, syncDevDependencies: false
[2017-02-28 16:20:40]     [vue:0] sync error, version: 0.0.0, RequestError: RequestError: tunneling socket could not be established----, statusCode=403 (req "error"), GET http://registry.npm.taobao.org/vue/download/vue-0.0.0.tgz -1 (connected: false, keepalive socket: false)
headers: {}
    at ClientRequest.onConnect (/nemo/node-v6.10.0-linux-x64/lib/node_modules/cnpmjs.org/node_modules/tunnel-agent/index.js:165:19)
    at ClientRequest.g (events.js:291:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:395:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
[2017-02-28 16:20:40]     [vue:1] syncing, delay: 101807074322 ms, version: 0.6.0, dist: {"shasum":"123c1a24ce6fe13c4530c03d780cb1ef966f9cde","size":23870,"noattachment":false,"tarball":"http://registry.npm.taobao.org/vue/download/vue-0.6.0.tgz"}, no deps: false, publish on cnpm: false, dependencies: 0, devDependencies: 0, syncDevDependencies: false
[2017-02-28 16:20:41]     [vue:1] sync error, version: 0.6.0, RequestError: RequestError: tunneling socket could not be established----, statusCode=403 (req "error"), GET http://registry.npm.taobao.org/vue/download/vue-0.6.0.tgz -1 (connected: false, keepalive socket: false)
headers: {}
    at ClientRequest.onConnect (/nemo/node-v6.10.0-linux-x64/lib/node_modules/cnpmjs.org/node_modules/tunnel-agent/index.js:165:19)
    at ClientRequest.g (events.js:291:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:395:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

**Comment by louiszhu2zgf** [comment]
@fengmk2 我把设置里面的syncModel设置成none就不会报这个错。初步推断是端口满了没法再开新的导致的
