### ISSUE TITLE
cnpm install error 

### ISSUE THREAD

**Issue by inickel** [cnpm/cnpmjs.org#1146]
```  javascript
JSONResponseFormatError: [express@4.13.4 › send@0.13.1 › statuses@~1.2.1] Unexpected token A in JSON at position 0 (data json format: "Active connections: 5 \nserver accepts handled requests\n 17735 17735 377716 \nReading: 0 Writing: 4 Waiting: 1 \n"), GET http://registry.cnpm.conpany.com/statuses/%3E%3D1.2.1%20%3C1.3.0 200 (connected: true, keepalive socket: true, agent status: {"createSocketCount":10,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":24,"freeSockets":{},"sockets":{"registry.cnpm.conpany.com:80::":10},"requests":{"registry.cnpm.conpany.com:80::":1}})
headers: {"server":"nginx/1.4.3","date":"Mon, 20 Mar 2017 01:26:25 GMT","content-type":"text/plain","content-length":"110","connection":"keep-alive"}
    at Object.parse (native)
    at parseJSON (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\urllib\lib\urllib.js:871:24)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\urllib\lib\urllib.js:658:23
    at decodeContent (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\urllib\lib\urllib.js:512:14)
    at IncomingMessage.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\urllib\lib\urllib.js:639:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npminstall version: 2.13.2
npminstall args: C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\Administrator\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://registry.cnpm.conpany.com/ express -d

```
安装时出错

**Comment by dead-horse** [comment]
重新安装一下看看，看起来像是网络异常了

**Comment by inickel** [comment]
不行，直接用registry访问结果也是异常的，跟网络没关系，用sync过也还是不对

**Comment by inickel** [comment]
查到是与nginx的状态路由冲突，非程序问题
