### ISSUE TITLE
增加https://atom.io/download/electron

### ISSUE THREAD

**Issue by nealsun** [cnpm/cnpmjs.org#1158]
希望增加https://atom.io/download/electron   既不是electron也不是atom-shell
在electron-rebuild的时候会使用
gyp http GET https://atom.io/download/electron/v1.6.2/win-x86/iojs.lib
gyp http GET https://atom.io/download/electron/v1.6.2/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.6.2/win-x86/iojs.lib
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1034:11)
gyp ERR! stack     at TLSWrap.onread (net.js:580:26)

**Comment by nealsun** [comment]
__
