### ISSUE TITLE
【3.0.0-alpha.3】TypeError: Cannot read property 'findAll' of null

### ISSUE THREAD

**Issue by Arnosir** [cnpm/cnpmjs.org#1162]
[2017-04-07 21:26:31] user: anonymous, sync n worker start, 1 concurrency, nodeps: false, publish: false
[2017-04-07 21:26:31] ----------------- Syncing upstream https://registry.npm.taobao.org/n/sync/log/3498090 -------------------
[2017-04-07 21:26:31] [2017-04-07 21:26:31] user: anonymous, sync n worker start, 1 concurrency, nodeps: false, publish: false
[2017-04-07 21:26:33] [2017-04-07 21:26:31] ----------------- Syncing upstream https://r.cnpmjs.org/n/sync/log/2367330 -------------------
[2017-04-07 21:26:31] [2017-04-07 21:26:31] user: anonymous, sync n worker start, 1 concurrency, nodeps: false, publish: false
[2017-04-07 21:26:31] ----------------- Syncing n -------------------
[2017-04-07 21:26:35] [2017-04-07 21:26:33] [2017-04-07 21:26:32] [c#0] [n] package(https://replicate.npmjs.com/n) status: 200, dist-tags: {"latest":"2.1.7"}, time.modified: 2017-03-31T01:30:18.063Z, unpublished: null, start...
[2017-04-07 21:26:32]   [n] found 0 missing star users
[2017-04-07 21:26:32]   [n] all versions are exists
[2017-04-07 21:26:32]   [n] no versions need to deleted
[2017-04-07 21:26:32]   [n] all 156 npm users exists
[2017-04-07 21:26:32] [c#0] [n] synced success, 0 versions: 
[2017-04-07 21:26:32] ----------------- Synced n success -------------------
[2017-04-07 21:26:32] ----------------- Syncing n -------------------
[2017-04-07 21:26:32] [c#0] [n] package(https://registry.npmjs.com/n) status: 200, dist-tags: {"latest":"2.1.7"}, time.modified: 2017-03-31T01:30:18.063Z, unpublished: null, start...
[2017-04-07 21:26:32]   [n] found 0 missing star users
[2017-04-07 21:26:32]   [n] all versions are exists
[2017-04-07 21:26:32]   [n] no versions need to deleted
[2017-04-07 21:26:32]   [n] all 156 npm users exists
[2017-04-07 21:26:32] [c#0] [n] synced success, 0 versions: 
[2017-04-07 21:26:32] ----------------- Synced n success -------------------
[2017-04-07 21:26:32] [Upstream done] Sync n package finished, 2 success, 0 fail
Success: [ n, n ]
Fail: [  ]
[2017-04-07 21:26:33] ----------------- Synced upstream https://r.cnpmjs.org/n/sync/log/2367330 -------------------
[2017-04-07 21:26:33] ----------------- Syncing n -------------------
[2017-04-07 21:26:34] [c#0] [n] package(https://r.cnpmjs.org/n) status: 200, dist-tags: {"latest":"2.1.7"}, time.modified: 2017-03-31T00:07:29.000Z, unpublished: null, start...
[2017-04-07 21:26:34]   [n] found 0 missing star users
[2017-04-07 21:26:34]   [n] all versions are exists
[2017-04-07 21:26:34]   [n] no versions need to deleted
[2017-04-07 21:26:34]   [n] all 162 npm users exists
[2017-04-07 21:26:34] [c#0] [n] synced success, 0 versions: 
[2017-04-07 21:26:34] ----------------- Synced n success -------------------
[2017-04-07 21:26:34] [Upstream done] Sync n package finished, 1 success, 0 fail
Success: [ n ]
Fail: [  ]
[2017-04-07 21:26:35] ----------------- Synced upstream https://registry.npm.taobao.org/n/sync/log/3498090 -------------------
[2017-04-07 21:26:35] ----------------- Syncing n -------------------
[2017-04-07 21:26:35] [c#0] [n] package(https://registry.npm.taobao.org/n) status: 200, dist-tags: {"latest":"2.1.7"}, time.modified: 2017-03-31T00:07:47.000Z, unpublished: null, start...
[2017-04-07 21:26:35] [c#0] [error] [n] sync error: TypeError: Cannot read property 'findAll' of null
    at Object.exports.listModuleAbbreviatedsByName (/opt/soft/cnpmjs.org/services/package.js:327:44)
    at next (native)
    at onFulfilled (/opt/soft/cnpmjs.org/node_modules/co/index.js:65:19)
    at /opt/soft/cnpmjs.org/node_modules/co/index.js:54:5
    at co (/opt/soft/cnpmjs.org/node_modules/co/index.js:50:10)
    at toPromise (/opt/soft/cnpmjs.org/node_modules/co/index.js:118:63)
    at Array.map (native)
    at arrayToPromise (/opt/soft/cnpmjs.org/node_modules/co/index.js:154:26)
    at toPromise (/opt/soft/cnpmjs.org/node_modules/co/index.js:120:49)
    at next (/opt/soft/cnpmjs.org/node_modules/co/index.js:99:29)
    at onFulfilled (/opt/soft/cnpmjs.org/node_modules/co/index.js:69:7)
    at /opt/soft/cnpmjs.org/node_modules/co/index.js:54:5
    at co (/opt/soft/cnpmjs.org/node_modules/co/index.js:50:10)
    at toPromise (/opt/soft/cnpmjs.org/node_modules/co/index.js:118:63)
    at next (/opt/soft/cnpmjs.org/node_modules/co/index.js:99:29)
    at onFulfilled (/opt/soft/cnpmjs.org/node_modules/co/index.js:69:7)
[2017-04-07 21:26:35] ----------------- Synced n fail -------------------
[2017-04-07 21:26:35] [done] Sync n package finished, 0 success, 1 fail
Success: [  ]
Fail: [ n ]
Sync n complete!

\# node -v
v6.10.2

@fengmk2 
之前测试环境搭建的2.18.0 是没有问题的，今天线上构建最新的3.0.0-alpha.3   同步package的时候报上述错误，请教下是怎么回事？又该如何解决呢？

**Comment by Arnosir** [comment]
反馈： 同环境下，我换成 2.19.4  可以正常使用。

**Comment by cooclsee** [comment]
+1

**Comment by LuanLouis** [comment]
+1

**Comment by LaveyD** [comment]
+1

**Comment by fengmk2** [comment]
@Arnosir 3.0.0-alpha.3 需要新建表结构 module_abbreviated 和 package_readme，还没正式发布，请不要升级到这个版本。https://github.com/cnpm/cnpmjs.org/blob/master/docs/db.sql#L90
