### ISSUE TITLE
Cannot read property 'findAll' of null

### ISSUE THREAD

**Issue by liguangge** [cnpm/cnpmjs.org#1174]
部署成功后，将syncModel设置为'exist',然后在http://127.0.0.1:7002/同步模块，会抱错，并未同步到模块。完整的信息如下：
[2017-05-11 15:21:37] user: anonymous, sync axios worker start, 1 concurrency, nodeps: false, publish: false
[2017-05-11 15:21:37] ----------------- Syncing upstream https://registry.npm.taobao.org/axios/sync/log/4941029 -------------------
[2017-05-11 15:21:37] [2017-05-11 15:21:37] user: anonymous, sync axios worker start, 1 concurrency, nodeps: false, publish: false
[2017-05-11 15:21:40] [2017-05-11 15:21:37] ----------------- Syncing upstream https://r.cnpmjs.org/axios/sync/log/3241953 -------------------
[2017-05-11 15:21:38] [2017-05-11 15:21:37] user: anonymous, sync axios worker start, 1 concurrency, nodeps: false, publish: false
[2017-05-11 15:21:37] ----------------- Syncing axios -------------------
[2017-05-11 15:21:42] [2017-05-11 15:21:40] [2017-05-11 15:21:39] [c#0] [axios] package(https://replicate.npmjs.com/axios) status: 200, dist-tags: {"latest":"0.16.1"}, time.modified: 2017-05-10T10:18:06.162Z, unpublished: null, start...
[2017-05-11 15:21:39]   [axios] found 0 missing star users
[2017-05-11 15:21:39]   [axios] all versions are exists
[2017-05-11 15:21:39]   [axios] no versions need to deleted
[2017-05-11 15:21:39]   [axios] all 251 npm users exists
[2017-05-11 15:21:39] [c#0] [axios] synced success, 0 versions: 
[2017-05-11 15:21:39] ----------------- Synced axios success -------------------
[2017-05-11 15:21:39] ----------------- Syncing axios -------------------
[2017-05-11 15:21:39] [c#0] [axios] package(https://registry.npmjs.com/axios) status: 200, dist-tags: {"latest":"0.16.1"}, time.modified: 2017-05-10T10:18:06.162Z, unpublished: null, start...
[2017-05-11 15:21:39]   [axios] found 0 missing star users
[2017-05-11 15:21:39]   [axios] all versions are exists
[2017-05-11 15:21:39]   [axios] no versions need to deleted
[2017-05-11 15:21:39]   [axios] all 251 npm users exists
[2017-05-11 15:21:39] [c#0] [axios] synced success, 0 versions: 
[2017-05-11 15:21:39] ----------------- Synced axios success -------------------
[2017-05-11 15:21:39] [Upstream done] Sync axios package finished, 2 success, 0 fail
Success: [ axios, axios ]
Fail: [  ]
[2017-05-11 15:21:40] ----------------- Synced upstream https://r.cnpmjs.org/axios/sync/log/3241953 -------------------
[2017-05-11 15:21:40] ----------------- Syncing axios -------------------
[2017-05-11 15:21:40] [c#0] [axios] package(https://r.cnpmjs.org/axios) status: 200, dist-tags: {"latest":"0.16.1"}, time.modified: 2017-04-08T18:52:03.000Z, unpublished: null, start...
[2017-05-11 15:21:41]   [axios] found 0 missing star users
[2017-05-11 15:21:41]   [axios] all versions are exists
[2017-05-11 15:21:41]   [axios] no versions need to deleted
[2017-05-11 15:21:41]   [axios] all 256 npm users exists
[2017-05-11 15:21:41] [c#0] [axios] synced success, 0 versions: 
[2017-05-11 15:21:41] ----------------- Synced axios success -------------------
[2017-05-11 15:21:41] [Upstream done] Sync axios package finished, 1 success, 0 fail
Success: [ axios ]
Fail: [  ]
[2017-05-11 15:21:42] ----------------- Synced upstream https://registry.npm.taobao.org/axios/sync/log/4941029 -------------------
[2017-05-11 15:21:42] ----------------- Syncing axios -------------------
[2017-05-11 15:21:42] [c#0] [axios] package(https://registry.npm.taobao.org/axios) status: 200, dist-tags: {"latest":"0.16.1"}, time.modified: 2017-04-08T18:52:06.000Z, unpublished: null, start...
[2017-05-11 15:21:42] [c#0] [error] [axios] sync error: TypeError: Cannot read property 'findAll' of null
    at Object.exports.listModuleAbbreviatedsByName (/Users/kevin/Documents/cnpmjs/services/package.js:327:44)
    at exports.listModuleAbbreviatedsByName.next ()
    at onFulfilled (/Users/kevin/Documents/cnpmjs/node_modules/co/index.js:65:19)
    at /Users/kevin/Documents/cnpmjs/node_modules/co/index.js:54:5
    at co (/Users/kevin/Documents/cnpmjs/node_modules/co/index.js:50:10)
    at toPromise (/Users/kevin/Documents/cnpmjs/node_modules/co/index.js:118:63)
    at Array.map (native)
    at arrayToPromise (/Users/kevin/Documents/cnpmjs/node_modules/co/index.js:154:26)
    at toPromise (/Users/kevin/Documents/cnpmjs/node_modules/co/index.js:120:49)
    at next (/Users/kevin/Documents/cnpmjs/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/kevin/Documents/cnpmjs/node_modules/co/index.js:69:7)
    at /Users/kevin/Documents/cnpmjs/node_modules/co/index.js:54:5
    at co (/Users/kevin/Documents/cnpmjs/node_modules/co/index.js:50:10)
    at toPromise (/Users/kevin/Documents/cnpmjs/node_modules/co/index.js:118:63)
    at next (/Users/kevin/Documents/cnpmjs/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/kevin/Documents/cnpmjs/node_modules/co/index.js:69:7)
[2017-05-11 15:21:42] ----------------- Synced axios fail -------------------
[2017-05-11 15:21:42] [done] Sync axios package finished, 0 success, 1 fail
Success: [  ]
Fail: [ axios ]
Sync axios complete!

**Comment by Arnosir** [comment]
https://github.com/cnpm/cnpmjs.org/issues/1162

**Comment by MarvenGong** [comment]
did you have resolved this problem ?
