### ISSUE TITLE
syncModel配置为none时同步正常，但是还是搜索不到

### ISSUE THREAD

**Issue by yincoco** [cnpm/cnpmjs.org#1194]
[2017-06-22 20:20:54] user: anonymous, sync gulp worker start, 1 concurrency, nodeps: false, publish: false
[2017-06-22 20:20:54] ----------------- Syncing upstream https://registry.npm.taobao.org/gulp/sync/log/5438317 -------------------
[2017-06-22 20:20:54] [2017-06-22 20:20:54] user: anonymous, sync gulp worker start, 1 concurrency, nodeps: false, publish: false
[2017-06-22 20:20:56] [2017-06-22 20:20:54] ----------------- Syncing upstream https://r.cnpmjs.org/gulp/sync/log/3596509 -------------------
[2017-06-22 20:20:54] [2017-06-22 20:20:54] user: anonymous, sync gulp worker start, 1 concurrency, nodeps: false, publish: false
[2017-06-22 20:20:54] ----------------- Syncing gulp -------------------
[2017-06-22 20:20:58] [2017-06-22 20:20:56] [2017-06-22 20:20:55] [c#0] [gulp] package(https://replicate.npmjs.com/gulp) status: 200, dist-tags: {"latest":"3.9.1"}, time.modified: 2017-06-15T19:06:39.806Z, unpublished: null, start...
[2017-06-22 20:20:55]   [gulp] found 0 missing star users
[2017-06-22 20:20:55]   [gulp] all versions are exists
[2017-06-22 20:20:55]   [gulp] no versions need to deleted
[2017-06-22 20:20:55]   [gulp] saving 1/1326 missing npm users: ["botero.89"]
[2017-06-22 20:20:56] [c#0] [gulp] synced success, 0 versions: 
[2017-06-22 20:20:56] ----------------- Synced gulp success -------------------
[2017-06-22 20:20:56] ----------------- Syncing gulp -------------------
[2017-06-22 20:20:56] [c#0] [gulp] package(https://registry.npmjs.com/gulp) status: 200, dist-tags: {"latest":"3.9.1"}, time.modified: 2017-06-15T19:06:39.806Z, unpublished: null, start...
[2017-06-22 20:20:56]   [gulp] found 0 missing star users
[2017-06-22 20:20:56]   [gulp] all versions are exists
[2017-06-22 20:20:56]   [gulp] no versions need to deleted
[2017-06-22 20:20:56]   [gulp] saving 1/1326 missing npm users: ["botero.89"]
[2017-06-22 20:21:00] [2017-06-22 20:20:58] [2017-06-22 20:20:57] [c#0] [gulp] synced success, 0 versions: 
[2017-06-22 20:20:57] ----------------- Synced gulp success -------------------
[2017-06-22 20:20:57] [Upstream done] Sync gulp package finished, 2 success, 0 fail
Success: [ gulp, gulp ]
Fail: [  ]
[2017-06-22 20:20:58] ----------------- Synced upstream https://r.cnpmjs.org/gulp/sync/log/3596509 -------------------
[2017-06-22 20:20:58] ----------------- Syncing gulp -------------------
[2017-06-22 20:20:59] [c#0] [gulp] package(https://r.cnpmjs.org/gulp) status: 200, dist-tags: {"latest":"3.9.1"}, time.modified: 2017-03-24T16:04:47.000Z, unpublished: null, start...
[2017-06-22 20:20:59]   [gulp] found 0 missing star users
[2017-06-22 20:20:59]   [gulp] all versions are exists
[2017-06-22 20:20:59]   [gulp] no versions need to deleted
[2017-06-22 20:20:59]   [gulp] saving 1/1382 missing npm users: ["botero.89"]
[2017-06-22 20:20:59] [c#0] [gulp] synced success, 0 versions: 
[2017-06-22 20:20:59] ----------------- Synced gulp success -------------------
[2017-06-22 20:20:59] [Upstream done] Sync gulp package finished, 1 success, 0 fail
Success: [ gulp ]
Fail: [  ]
[2017-06-22 20:21:00] ----------------- Synced upstream https://registry.npm.taobao.org/gulp/sync/log/5438317 -------------------
[2017-06-22 20:21:00] [c#0] [undefined] syncModel is none, ignore
[2017-06-22 20:21:00] [done] Sync gulp package finished, 0 success, 0 fail
Success: [  ]
Fail: [  ]
Sync gulp complete!

**Comment by yincoco** [comment]
syncModel配置为exist时会报：
[2017-06-22 20:24:32] ----------------- Synced upstream https://registry.npm.taobao.org/gulp/sync/log/5438393 -------------------
[2017-06-22 20:24:32] ----------------- Syncing gulp -------------------
[2017-06-22 20:24:32] [c#0] [gulp] package(https://registry.npm.taobao.org/gulp) status: 200, dist-tags: {"latest":"3.9.1"}, time.modified: 2017-03-27T10:03:32.000Z, unpublished: null, start...
[2017-06-22 20:24:32] [c#0] [error] [gulp] sync error: TypeError: Cannot read property 'findAll' of null
    at Object.exports.listModuleAbbreviatedsByName (/home/yinkeke/cnpmjs.org/services/package.js:327:44)
    at exports.listModuleAbbreviatedsByName.next ()
    at onFulfilled (/home/yinkeke/cnpmjs.org/node_modules/co/index.js:65:19)
    at /home/yinkeke/cnpmjs.org/node_modules/co/index.js:54:5
    at Promise ()
    at co (/home/yinkeke/cnpmjs.org/node_modules/co/index.js:50:10)
    at toPromise (/home/yinkeke/cnpmjs.org/node_modules/co/index.js:118:63)
    at Array.map (native)
    at arrayToPromise (/home/yinkeke/cnpmjs.org/node_modules/co/index.js:154:26)
    at toPromise (/home/yinkeke/cnpmjs.org/node_modules/co/index.js:120:49)
    at next (/home/yinkeke/cnpmjs.org/node_modules/co/index.js:99:29)
    at onFulfilled (/home/yinkeke/cnpmjs.org/node_modules/co/index.js:69:7)
    at /home/yinkeke/cnpmjs.org/node_modules/co/index.js:54:5
    at Promise ()
    at co (/home/yinkeke/cnpmjs.org/node_modules/co/index.js:50:10)
    at toPromise (/home/yinkeke/cnpmjs.org/node_modules/co/index.js:118:63)
[2017-06-22 20:24:32] ----------------- Synced gulp fail -------------------
[2017-06-22 20:24:32] [done] Sync gulp package finished, 0 success, 1 fail
Success: [  ]
Fail: [ gulp ]
Sync gulp complete!

**Comment by Asher-Tan** [comment]
syncModel为all也同样会报这个错，还不知道什么原因

**Comment by pengfeiWang** [comment]
我这可以搜索到, 但是安装时报错

**Comment by Baoyx007** [comment]
#1162
