### ISSUE TITLE
http://localhost:7002 页面打开正常，在Search Package中搜索报错

### ISSUE THREAD

**Issue by Rexxxxxxxxar** [cnpm/cnpmjs.org#1195]
{ SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Handshake._callback (/data/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:80:20)
    at Handshake.Sequence.end (/data/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Protocol.handleNetworkError (/data/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:364:14)
    at Connection._handleNetworkError (/data/cnpmjs.org/node_modules/mysql/lib/Connection.js:428:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'SequelizeConnectionRefusedError',
  message: 'connect ECONNREFUSED 127.0.0.1:3306',
  parent: 
   { Error: connect ECONNREFUSED 127.0.0.1:3306
       at Object.exports._errnoException (util.js:1018:11)
       at exports._exceptionWithHostPort (util.js:1041:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
       --------------------
       at Protocol._enqueue (/data/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:141:48)
       at Protocol.handshake (/data/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:52:41)
       at Connection.connect (/data/cnpmjs.org/node_modules/mysql/lib/Connection.js:130:18)
       at /data/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:75:16
       at Promise._execute (/data/cnpmjs.org/node_modules/bluebird/js/release/debuggability.js:300:9)
       at Promise._resolveFromExecutor (/data/cnpmjs.org/node_modules/bluebird/js/release/promise.js:483:18)
       at new Promise (/data/cnpmjs.org/node_modules/bluebird/js/release/promise.js:79:10)
       at ConnectionManager.connect (/data/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:55:10)
       at ConnectionManager.tryCatcher (/data/cnpmjs.org/node_modules/bluebird/js/release/util.js:16:23)
       at Promise._settlePromiseFromHandler (/data/cnpmjs.org/node_modules/bluebird/js/release/promise.js:512:31)
       at Promise._settlePromise (/data/cnpmjs.org/node_modules/bluebird/js/release/promise.js:569:18)
       at Promise._settlePromise0 (/data/cnpmjs.org/node_modules/bluebird/js/release/promise.js:614:10)
       at Promise._settlePromises (/data/cnpmjs.org/node_modules/bluebird/js/release/promise.js:693:18)
       at Async._drainQueue (/data/cnpmjs.org/node_modules/bluebird/js/release/async.js:133:16)
       at Async._drainQueues (/data/cnpmjs.org/node_modules/bluebird/js/release/async.js:143:10)
       at Immediate.Async.drainQueues (/data/cnpmjs.org/node_modules/bluebird/js/release/async.js:17:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3306,
     fatal: true },
  original: 
   { Error: connect ECONNREFUSED 127.0.0.1:3306
       at Object.exports._errnoException (util.js:1018:11)
       at exports._exceptionWithHostPort (util.js:1041:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
       --------------------
       at Protocol._enqueue (/data/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:141:48)
       at Protocol.handshake (/data/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:52:41)
       at Connection.connect (/data/cnpmjs.org/node_modules/mysql/lib/Connection.js:130:18)
       at /data/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:75:16
       at Promise._execute (/data/cnpmjs.org/node_modules/bluebird/js/release/debuggability.js:300:9)
       at Promise._resolveFromExecutor (/data/cnpmjs.org/node_modules/bluebird/js/release/promise.js:483:18)
       at new Promise (/data/cnpmjs.org/node_modules/bluebird/js/release/promise.js:79:10)
       at ConnectionManager.connect (/data/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:55:10)
       at ConnectionManager.tryCatcher (/data/cnpmjs.org/node_modules/bluebird/js/release/util.js:16:23)
       at Promise._settlePromiseFromHandler (/data/cnpmjs.org/node_modules/bluebird/js/release/promise.js:512:31)
       at Promise._settlePromise (/data/cnpmjs.org/node_modules/bluebird/js/release/promise.js:569:18)
       at Promise._settlePromise0 (/data/cnpmjs.org/node_modules/bluebird/js/release/promise.js:614:10)
       at Promise._settlePromises (/data/cnpmjs.org/node_modules/bluebird/js/release/promise.js:693:18)
       at Async._drainQueue (/data/cnpmjs.org/node_modules/bluebird/js/release/async.js:133:16)
       at Async._drainQueues (/data/cnpmjs.org/node_modules/bluebird/js/release/async.js:143:10)
       at Immediate.Async.drainQueues (/data/cnpmjs.org/node_modules/bluebird/js/release/async.js:17:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3306,
     fatal: true },
  url: '/total' }

**Comment by newsn** [comment]
你本机3306端口的mysql问题，我也是刚刚配好mysql。config/index.js里面配好信息后，执行make init-database 。然后就不报错了。但是这边，搜索啥，都是空的页面。不知道数据从哪里来的。
