### ISSUE TITLE
ng build --prod 报错

### ISSUE THREAD

**Issue by mac86cy** [cnpm/cnpmjs.org#1227]
在安装Angular项目依赖时，采用cnpm install ，在ng serve 和ng build为任何问题，正常运行，到加入--prod 时就报错。
采用npm就没此问题。

 return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/jicg/Documents/WebstormProjects/Text/node_modules/._@angular_common@4.3.4@@angular/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at licensePlugin.readPackageJson (/Users/jicg/Documents/WebstormProjects/Text/node_modules/._license-webpack-plugin@0.5.1@license-webpack-plugin/index.js:26:19)
    at licensePlugin.getModuleInfo (/Users/jicg/Documents/WebstormProjects/Text/node_modules/._license-webpack-plugin@0.5.1@license-webpack-plugin/index.js:30:28)
    at licensePlugin.<anonymous> (/Users/jicg/Documents/WebstormProjects/Text/node_modules/._license-webpack-plugin@0.5.1@license-webpack-plugin/index.js:81:31)
    at Array.filter (native)
    at licensePlugin.writeModuleInfo (/Users/jicg/Documents/WebstormProjects/Text/node_modules/._license-webpack-plugin@0.5.1@license-webpack-plugin/index.js:77:8)
    at licensePlugin.gatherModuleInfo (/Users/jicg/Documents/WebstormProjects/Text/node_modules/._license-webpack-plugin@0.5.1@license-webpack-plugin/index.js:117:10)
    at licensePlugin.<anonymous> (/Users/jicg/Documents/WebstormProjects/Text/node_modules/._license-webpack-plugin@0.5.1@license-webpack-plugin/index.js:233:12)
    at Compiler.applyPlugins (/Users/jicg/Documents/WebstormProjects/Text/node_modules/._tapable@0.2.8@tapable/lib/Tapable.js:61:14)

**Comment by ibigbug** [comment]
可以加参数 `--by=npm` 试试
