### ISSUE TITLE
MySQL ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x9A\x80' for column 'description'

### ISSUE THREAD

**Issue by dingzhengkai** [cnpm/cnpmjs.org#1229]
关于MySQL字段编码的问题

> 同步ava的时候报错
[2016-10-31 11:00:20] [ava:0] sync error, version: 0.4.0, SequelizeDatabaseError: SequelizeDatabaseError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x9A\x80' for column 'description' at row 1
at Query.formatError (/usr/local/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
at Query._callback (/usr/local/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
at Query.Sequence.end (/usr/local/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
at Query.ErrorPacket (/usr/local/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
at Protocol._parsePacket (/usr/local/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:280:23)
at Parser.write (/usr/local/cnpmjs.org/node_modules/mysql/lib/protocol/Parser.js:74:12)
at Protocol.write (/usr/local/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:39:16)
at Socket. (/usr/local/cnpmjs.org/node_modules/mysql/lib/Connection.js:109:28)
at emitOne (events.js:77:13)
at Socket.emit (events.js:169:7)
at readableAddChunk (_stream_readable.js:153:18)
at Socket.Readable.push (_stream_readable.js:111:10)
at TCP.onread (net.js:536:20)

我使用 npm 安装 cnpmjs "version": "2.19.4", 数据库的字段类型也改过了，同步ava仍然失败，有人解决了没？

**Comment by dingzhengkai** [comment]
使用源码安装的方式
cnpmjs.org@3.0.0-alpha.15
mysql 5.7.19
仍然有这个问题

**Comment by dingzhengkai** [comment]
修改mysql server字符集加表字段字符集解决
