### ISSUE TITLE
安装私有包提示错误404

### ISSUE THREAD

**Issue by czd890** [cnpm/cnpmjs.org#1234]
上周还没有问题，今天安装直接就404。

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'gd-express-basic' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose npm-session d81efb1cc0d595d4
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 http://registry.npm.guodong.cn/gd-express-basic 92ms (from cache)
8 http fetch GET 404 http://r.cnpmjs.org/gd-express-basic/download/gd-express-basic-1.0.1.tgz 526ms
9 silly fetchPackageMetaData error for gd-express-basic@^1.0.1 404 Not Found: gd-express-basic@^1.0.1
10 verbose stack Error: 404 Not Found: gd-express-basic@^1.0.1
10 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:41:19)
10 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
10 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
10 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
10 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
10 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
10 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
10 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
10 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
10 verbose stack     at runCallback (timers.js:781:20)
10 verbose stack     at tryOnImmediate (timers.js:743:5)
10 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
11 verbose cwd D:\sourcecode\gd\node-web-demo
12 verbose Windows_NT 10.0.15063
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gd-express-basic"
14 verbose node v8.2.1
15 verbose npm  v5.3.0
16 error code E404
17 error 404 Not Found: gd-express-basic@^1.0.1
18 verbose exit [ 1, true ]

**Comment by czd890** [comment]
修改服务端 config/index.js
registryHost: 'registry.npm.guodong.cn'
