### ISSUE TITLE
出现这个错误 应该怎么办呢 同步的时候

### ISSUE THREAD

**Issue by yanglinnie** [cnpm/cnpmjs.org#1236]
[2017-09-22 03:27:16] [c#0] [error] [connect] sync error: TypeError: Cannot read property 'findAll' of null
    at Object.exports.listModuleAbbreviatedsByName (/data/cnpmjs.org/services/package.js:327:44)

**Comment by csnikey** [comment]
同问，我也是这个报错目前。
另外一个问题就是，现在可以发布成功模块，但是下载的模块web页面上没有记录，自己发布的模块也下载不了。不知道是哪里的配置不对。

**Comment by csnikey** [comment]
@fengmk2  大神方便的时候解答下 谢谢啦

**Comment by hstarorg** [comment]
我跟了下源码，发现只需要在设置中配置：`enableAbbreviatedMetadata: true`，即可修复该问题。

**Comment by csnikey** [comment]
@hstarorg 3q 设置后，果然解决了

**Comment by vincent-lee** [comment]
@csnikey "下载的模块web页面上没有记录，自己发布的模块也下载不了。" 我也出现这个问题了，请问你最后解决了吗？

**Comment by vincent-lee** [comment]
@csnikey 请问是修改哪一项设置呢？是 enableAbbreviatedMetadata: true 这个吗？我修改了，“ [error] [connect] sync error: TypeError: Cannot read property 'findAll' of null
at Object.exports.listModuleAbbreviatedsByName (/data/cnpmjs.org/services/package.js:327:44)” 这个是问题是解决了，但是”下载的模块web页面上没有记录“这个问题还是没有解决

**Comment by csnikey** [comment]
@vincent-lee  加我微信 csnikey 详细了解下，我现在搭建的没问题的了，可能某些配置你还是没配置好的
