### ISSUE TITLE
error 413 Payload Too Large

### ISSUE THREAD

**Issue by loveatting** [cnpm/cnpmjs.org#1240]
想问下有没有人碰到这个error的，
一开始报错有Error: request entity too large
然后将使用的nginx中的限制已经更改到100M，包的大小是80M的
然后现在出现的是
verbose bad json Payload Too Large
error registry error parsing json

```
41 verbose stack Error: 413 Payload Too Large
41 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
41 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:215:9)
41 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
41 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:199:22)
41 verbose stack     at emitTwo (events.js:100:13)
41 verbose stack     at Request.emit (events.js:185:7)
41 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1036:10)
41 verbose stack     at emitOne (events.js:95:20)
41 verbose stack     at Request.emit (events.js:182:7)
41 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:963:12)
42 verbose statusCode 413
```

**Comment by loveatting** [comment]
修改了jsonlimit的大小后OK了

**Comment by youngjuning** [comment]
在哪修改的这个参数？@loveatting

**Comment by xuhongbo** [comment]
> 在哪修改的这个参数？@loveatting
[https://github.com/cnpm/cnpmjs.org/blob/522ad11124f168788b28dd925417ae37eb9d3991/config/index.js#L44](L44)
