### ISSUE TITLE
包都同步完成,但是在cnpm install的时候一直再retry,最后报ResponseError: socket hang up (req "error")

### ISSUE THREAD

**Issue by Fantasy9527** [cnpm/cnpmjs.org#1259]
```
⠦ [24/31] Installing yargs@^3.4.5[npminstall:get] retry GET http://r.cnpmjs.org/shipit-cli/download/shipit-cli-3.0.0.tgz after 400ms, retry left 1, error: ResponseError: socket hang up (req "error"), GET https://cnpmjs.oss-ap-southeast-1.aliyuncs.com/shipit-cli/-/shipit-cli-3.0.0.tgz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":51,"createSocketErrorCount":0,"closeSocketCount":41,"errorSocketCount":0,"timeoutSocketCount":41,"requestCount":11,"freeSockets":{},"sockets":{"cnpmjs.oss-ap-southeast-1.aliyuncs.com:443:::::::true::":10},"requests":{"cnpmjs.oss-ap-southeast-1.aliyuncs.com:443:::::::true::":1}})
headers: {}
[npminstall:get] retry GET http://r.cnpmjs.org/sprintf-js/download/sprintf-js-1.1.1.tgz after 400ms, retry left 1, error: ResponseError: socket hang up (req "error"), GET https://cnpmjs.oss-ap-southeast-1.aliyuncs.com/sprintf-js/-/sprintf-js-1.1.1.tgz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":52,"createSocketErrorCount":0,"closeSocketCount":42,"errorSocketCount":0,"timeoutSocketCount":42,"requestCount":12,"freeSockets":{},"sockets":{"cnpmjs.oss-ap-southeast-1.aliyuncs.com:443:::::::true::":10},"requests":{}})
headers: {}
⠹ [24/31] Installing yargs@^3.4.5[npminstall:get] retry GET http://r.cnpmjs.org/jsonfile/download/jsonfile-2.4.0.tgz after 400ms, retry left 1, error: ResponseError: socket hang up (req "error"), GET https://cnpmjs.oss-ap-southeast-1.aliyuncs.com/jsonfile/-/jsonfile-2.4.0.tgz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":52,"createSocketErrorCount":0,"closeSocketCount":43,"errorSocketCount":0,"timeoutSocketCount":43,"requestCount":12,"freeSockets":{},"sockets":{"cnpmjs.oss-ap-southeast-1.aliyuncs.com:443:::::::true::":9},"requests":{}})
headers: {}
⠇ [24/31] Installing yargs@^3.4.5[npminstall:get] retry GET http://r.cnpmjs.org/bluebird/download/bluebird-2.11.0.tgz after 400ms, retry left 1, error: ResponseError: socket hang up (req "error"), GET https://cnpmjs.oss-ap-southeast-1.aliyuncs.com/bluebird/-/bluebird-2.11.0.tgz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":54,"createSocketErrorCount":0,"closeSocketCount":44,"errorSocketCount":0,"timeoutSocketCount":44,"requestCount":13,"freeSockets":{},"sockets":{"cnpmjs.oss-ap-southeast-1.aliyuncs.com:443:::::::true::":10},"requests":{}})
headers: {}
⠏ [24/31] Installing yargs@^3.4.5[npminstall:get] retry GET http://r.cnpmjs.org/wechat-enterprise/download/wechat-enterprise-0.1.1.tgz after 400ms, retry left 1, error: ResponseError: socket hang up (req "error"), GET https://cnpmjs.oss-ap-southeast-1.aliyuncs.com/wechat-enterprise/-/wechat-enterprise-0.1.1.tgz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":55,"createSocketErrorCount":0,"closeSocketCount":45,"errorSocketCount":0,"timeoutSocketCount":45,"requestCount":14,"freeSockets":{},"sockets":{"cnpmjs.oss-ap-southeast-1.aliyuncs.com:443:::::::true::":10},"requests":{}})
headers: {}
⠋ [24/31] Installing yargs@^3.4.5[npminstall:get] retry GET http://r.cnpmjs.org/path2/download/path2-0.1.0.tgz after 400ms, retry left 1, error: ResponseError: socket hang up (req "error"), GET https://cnpmjs.oss-ap-southeast-1.aliyuncs.com/path2/-/path2-0.1.0.tgz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":55,"createSocketErrorCount":0,"closeSocketCount":46,"errorSocketCount":0,"timeoutSocketCount":46,"requestCount":14,"freeSockets":{},"sockets":{"cnpmjs.oss-ap-southeast-1.aliyuncs.com:443:::::::true::":9},"requests":{}})
headers: {}
✖ Install fail! ResponseError: socket hang up (req "error"), GET https://cnpmjs.oss-ap-southeast-1.aliyuncs.com/https/-/https-1.0.0.tgz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":55,"createSocketErrorCount":0,"closeSocketCount":47,"errorSocketCount":0,"timeoutSocketCount":47,"requestCount":14,"freeSockets":{},"sockets":{"cnpmjs.oss-ap-southeast-1.aliyuncs.com:443:::::::true::":8},"requests":{}})
headers: {}
ResponseError: socket hang up (req "error"), GET https://cnpmjs.oss-ap-southeast-1.aliyuncs.com/https/-/https-1.0.0.tgz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":55,"createSocketErrorCount":0,"closeSocketCount":47,"errorSocketCount":0,"timeoutSocketCount":47,"requestCount":14,"freeSockets":{},"sockets":{"cnpmjs.oss-ap-southeast-1.aliyuncs.com:443:::::::true::":8},"requests":{}})
headers: {}
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketCloseListener (_http_client.js:363:23)
    at emitOne (events.js:121:20)
    at TLSSocket.emit (events.js:211:7)
    at _handle.close (net.js:554:12)
    at TCP.done [as _onclose] (_tls_wrap.js:356:7)
```

**Comment by johnzhu12** [comment]
+1

**Comment by johnzhu12** [comment]
![1](https://user-images.githubusercontent.com/11485619/33703866-ee0b030c-db64-11e7-8aa5-14eefa24a8d6.png)
![2](https://user-images.githubusercontent.com/11485619/33703867-efaa7134-db64-11e7-8ae8-1c62b013f8c6.png)
![3](https://user-images.githubusercontent.com/11485619/33703940-43b4f2cc-db65-11e7-9ed6-7319a29fdb94.png)

 我publish了两个测试包，一个testone，一个johnzhu，如图。registry也设置了。但是一直下载不下来。

![2](https://user-images.githubusercontent.com/11485619/33703945-4b11d5da-db65-11e7-8d51-640a81c1f44c.png)

**Comment by johnzhu12** [comment]
找到答案了，在config/index.js里有个配置，我看到的所有文章都没有提到。
// registry url name
  registryHost: '172.16.48.146:7001',//'r.cnpmjs.org',   修改成你自己服务器host。

**Comment by Fantasy9527** [comment]
@johnzhu12 
配置完成之后,你可以通过你搭建的cnpm服务器地址下载从外面同步过来的包吗?

**Comment by johnzhu12** [comment]
可以啊，cnpm它的逻辑是这样的－－先从你的私服找那个包下载，如果没有就去cnpm官方服务器下载。
   （我现在就是把cnpm 的registry设置成我的私服。其他项目，有官方的包也照下的。当然你也可以把你私服和cnpm org同步，也就是sync一下，不过没必要，都在墙内）

**Comment by backupbrains** [comment]
我也遇到了类似问题，写了个总结
https://www.jianshu.com/p/c6c5755901e3

**Comment by Fantasy9527** [comment]
我的问题解决了,是因为公司防火墙限制了部分网络的访问.导致了这个问题.
