### ISSUE TITLE
[master] sync failed with TypeError.

### ISSUE THREAD

**Issue by lawrency** [cnpm/cnpmjs.org#1260]
[2017-11-28 09:43:49] [c#0] [gulp] package(https://registry.npm.taobao.org/gulp) status: 200, dist-tags: {\"latest\":\"3.9.1\"}, time.modified: 2017-03-27T10:03:32.000Z, unpublished: null, start...\n
[2017-11-28 09:43:49] [c#0] [error] [gulp] sync error: TypeError: Cannot read property \'findAll\' of null\n
   at Object.exports.listModuleAbbreviatedsByName (/root/cnpm/cnpmjs.org/services/package.js:327:44)\n 
   at next (native)\n
   at onFulfilled (/root/cnpm/cnpmjs.org/node_modules/co/index.js:65:19)\n
   at /root/cnpm/cnpmjs.org/node_modules/co/index.js:54:5\n
   at co (/root/cnpm/cnpmjs.org/node_modules/co/index.js:50:10)\n
   at toPromise (/root/cnpm/cnpmjs.org/node_modules/co/index.js:118:63)\n
   at Array.map (native)\n 
   at arrayToPromise (/root/cnpm/cnpmjs.org/node_modules/co/index.js:154:26)\n  
   at toPromise (/root/cnpm/cnpmjs.org/node_modules/co/index.js:120:49)\n  
   at next (/root/cnpm/cnpmjs.org/node_modules/co/index.js:99:29)\n  
   at onFulfilled (/root/cnpm/cnpmjs.org/node_modules/co/index.js:69:7)\n 
   at /root/cnpm/cnpmjs.org/node_modules/co/index.js:54:5\n 
   at co (/root/cnpm/cnpmjs.org/node_modules/co/index.js:50:10)\n  
   at toPromise (/root/cnpm/cnpmjs.org/node_modules/co/index.js:118:63)\n 
   at next (/root/cnpm/cnpmjs.org/node_modules/co/index.js:99:29)\n  
   at onFulfilled (/root/cnpm/cnpmjs.org/node_modules/co/index.js:69:7)\n
[2017-11-28 09:43:49] ----------------- Synced gulp fail -------------------\n

**Comment by lawrency** [comment]
Commit: 5e264beba9f06370b562729cbfbcc526a0767949
