### ISSUE TITLE
npm owner add xxx fail

### ISSUE THREAD

**Issue by yangbin1994** [cnpm/cnpmjs.org#1269]
```bash
~ [16:37:24] ⬢ 8.9.1 
⚡️  npm owner add jiang.zhu @tarsocial/src2dist --registry=http://registry.npm.tarsocial.com/ --verbose 
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node/8.9.1/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'owner',
npm verb cli   'add',
npm verb cli   'jiang.zhu',
npm verb cli   '@tarsocial/src2dist',
npm verb cli   '--registry=http://registry.npm.tarsocial.com/',
npm verb cli   '--verbose' ]
npm info using npm@5.5.1
npm info using node@v8.9.1
npm verb config Skipping project config: /Users/yangbin/.npmrc. (matches userconfig)
npm verb owner add jiang.zhu to @tarsocial/src2dist
npm verb request uri http://registry.npm.tarsocial.com/-/user/org.couchdb.user:jiang.zhu
npm verb request new user, so can't send auth
npm info attempt registry request try #1 at 下午4:37:27
npm verb request id 4725346d8627869b
npm http request GET http://registry.npm.tarsocial.com/-/user/org.couchdb.user:jiang.zhu
npm http 401 http://registry.npm.tarsocial.com/-/user/org.couchdb.user:jiang.zhu
npm verb headers { date: 'Wed, 06 Dec 2017 08:37:27 GMT',
npm verb headers   'content-type': 'application/json; charset=utf-8',
npm verb headers   'content-length': '47',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-current-requests': '1',
npm verb headers   vary: 'Origin',
npm verb headers   'www-authenticate': 'Basic realm="sample"',
npm verb headers   'x-readtime': '1' }
npm ERR! owner mutate Error getting user data for jiang.zhu
npm verb stack Error: unauthorized login first: -/user/org.couchdb.user:jiang.zhu
npm verb stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
npm verb stack     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:14)
npm verb stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
npm verb stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at Request.emit (events.js:214:7)
npm verb stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1163:10)
npm verb stack     at emitOne (events.js:116:13)
npm verb stack     at Request.emit (events.js:211:7)
npm verb stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1085:12)
npm verb statusCode 401
npm verb cwd /Users/yangbin
npm verb Darwin 16.7.0
npm verb argv "/usr/local/Cellar/node/8.9.1/bin/node" "/usr/local/bin/npm" "owner" "add" "jiang.zhu" "@tarsocial/src2dist" "--registry=http://registry.npm.tarsocial.com/" "--verbose"
npm verb node v8.9.1
npm verb npm  v5.5.1
npm ERR! code E401
npm ERR! 404 unauthorized login first: -/user/org.couchdb.user:jiang.zhu
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yangbin/.npm/_logs/2017-12-06T08_37_27_817Z-debug.log
```

> npm http 401 http://registry.npm.tarsocial.com/-/user/org.couchdb.user:jiang.zhu

求教应该如何解决？

**Comment by glen-84** [comment]
@fengmk2,

I have this issue as well.

```
npm verb request new user, so can't send auth
```

Why is it considered to be a *new* user?

Is there a solution or work-around?

---

**Server:**

Node.js version: v6.7.0
cnpmjs.org version: 2.12.2

**Client:**

Node.js version: v8.11.4
npm: 5.6.0

**Comment by glen-84** [comment]
@fengmk2 Is this a bug? Is there a way to work around this issue?

**Comment by glen-84** [comment]
I was able to work around the issue by setting `alwaysAuth` to `false` in `config/config.js`.

**Comment by fengmk2** [comment]
you should login first.

`npm login --registry=http://registry.npm.tarsocial.com/`

**Comment by glen-84** [comment]
@fengmk2,

I am logged in. I'm using an old version of cnpm, so maybe it has been fixed since then.

Did/does the text `new user, so can't send auth` come from cnpm or npm?

The problem is that auth is not being sent (for some unknown reason), but `alwaysAuth` requires it.
