### ISSUE TITLE
启动不成功（bind EADDRNOTAVAIL）

### ISSUE THREAD

**Issue by yinhaijiao** [cnpm/cnpmjs.org#1272]
使用npm start方式没有启动成功，不断的报以下错误。

nodejs_stdout.log
```
[Wed Dec 13 2017 16:14:37 GMT+0800 (CST)] [worker:31365] Server started, registry server listen at 172.16.54.171:8001, web listen at 172.16.54.171:8002, cluster: true
{ Error: bind EADDRNOTAVAIL 172.16.54.171:8001 (uncaughtException throw 1 times on pid:31365)
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at cb (net.js:1323:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:753:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'bind',
  address: '172.16.54.171',
  port: 8001 }
Error: bind EADDRNOTAVAIL 172.16.54.171:8001 (uncaughtException throw 1 times on pid:31365)
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at cb (net.js:1323:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:753:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Wed Dec 13 2017 16:14:37 GMT+0800 (CST)] [graceful:worker:31365:uncaughtException] throw error 1 times
{ Error: bind EADDRNOTAVAIL 172.16.54.171:8001 (uncaughtException throw 1 times on pid:31365)
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at cb (net.js:1323:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:753:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'bind',
  address: '172.16.54.171',
  port: 8001 }
Error: bind EADDRNOTAVAIL 172.16.54.171:8001 (uncaughtException throw 1 times on pid:31365)
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at cb (net.js:1323:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:753:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Wed Dec 13 2017 16:14:37 GMT+0800 (CST)] [graceful:worker:31365] will exit after 30000ms
[Wed Dec 13 2017 16:14:37 GMT+0800 (CST)] [graceful:worker:31365] close server#0, _connections: 0
[Wed Dec 13 2017 16:14:37 GMT+0800 (CST)] [graceful:worker:31365] close server#1, _connections: 0
[Wed Dec 13 2017 16:14:37 GMT+0800 (CST)] [graceful:worker:31365] close 2 servers!
[Wed Dec 13 2017 16:14:37 GMT+0800 (CST)] [graceful:worker:31365] worker disconnect!
{ Error: bind EADDRNOTAVAIL 172.16.54.171:8002 (uncaughtException throw 2 times on pid:31365)
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at cb (net.js:1323:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:753:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'bind',
  address: '172.16.54.171',
  port: 8002 }
Error: bind EADDRNOTAVAIL 172.16.54.171:8002 (uncaughtException throw 2 times on pid:31365)
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at cb (net.js:1323:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:753:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Wed Dec 13 2017 16:14:37 GMT+0800 (CST)] [graceful:worker:31365:uncaughtException] throw error 2 times
{ Error: bind EADDRNOTAVAIL 172.16.54.171:8002 (uncaughtException throw 2 times on pid:31365)
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at cb (net.js:1323:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:753:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'bind',
  address: '172.16.54.171',
  port: 8002 }
Error: bind EADDRNOTAVAIL 172.16.54.171:8002 (uncaughtException throw 2 times on pid:31365)
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at cb (net.js:1323:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:753:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[2017-12-13 16:14:37.596] [cfork:master:28007] worker:31365 disconnect (exitedAfterDisconnect: true, state: disconnected, isDead: false, worker.disableRefork: undefined)
[2017-12-13 16:14:37.603] [cfork:master:28007] new worker:31375 fork (state: none)
[Wed Dec 13 2017 16:14:37 GMT+0800 (CST)] [master:28007] wroker:31365 disconnect, suicide: true, state: disconnected.
[Wed Dec 13 2017 16:14:37 GMT+0800 (CST)] [worker:31375] new worker start
[Wed Dec 13 2017 16:14:38 GMT+0800 (CST)] [graceful:worker:31273] kill timeout, exit now.
[2017-12-13 16:14:38.694] [cfork:master:28007] worker:31273 exit (code: 1, exitedAfterDisconnect: true, state: dead, isDead: true, isExpected: true, worker.disableRefork: undefined)
[Wed Dec 13 2017 16:14:38 GMT+0800 (CST)] [master:28007] wroker exit: WorkerDiedError: worker 31273 died (code: 1, signal: null, suicide: true, state: dead)
    at EventEmitter.<anonymous> (/usr/local/cnpm/node_modules/cnpmjs.org/dispatch.js:37:15)
    at emitThree (events.js:121:20)
    at EventEmitter.emit (events.js:194:7)
    at ChildProcess.<anonymous> (cluster.js:379:15)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

error.log
```
2017-12-13 16:14:37.580 nodejs.EADDRNOTAVAILErrorException: Error: bind EADDRNOTAVAIL 172.16.54.171:8001 (uncaughtException throw 1 times on pid:31365)
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at cb (net.js:1323:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:753:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
pid: 31365
Host: host-10-0-69-73
URL: 
Data: ''
2017-12-13 16:14:37.580
2017-12-13 16:14:37.593 nodejs.EADDRNOTAVAILErrorException: Error: bind EADDRNOTAVAIL 172.16.54.171:8002 (uncaughtException throw 2 times on pid:31365)
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at cb (net.js:1323:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:753:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
pid: 31365
Host: host-10-0-69-73
URL: 
Data: ''
2017-12-13 16:14:37.593
```

**Comment by yinhaijiao** [comment]
找到原因了，自己机器配置的问题。

**Comment by ydmap** [comment]
@yinhaijiao 什么配置问题？
