### ISSUE TITLE
cnpm使用always-auth导入包失败

### ISSUE THREAD

**Issue by GitHubForQiuKai** [cnpm/cnpmjs.org#1280]
#### 运行命令:
cnpm insatll @bimjk/qiukai-test --save

#### 错误信息:
```
⠋ [npminstall:get] retry GET http://127.0.0.1:7001/@bimjk%2Fqiukai-test after 100ms, retry left 4, error: SyntaxError: Unexpected token l in JSON at position 0
⠙ [0/1] Installing @bimjk/qiukai-test@*[npminstall:get] retry GET http://127.0.0.1:7001/@bimjk%2Fqiukai-test after 200ms, retry left 3, error: SyntaxError: Unexpected token l in JSON at position 0
⠸ [0/1] Installing @bimjk/qiukai-test@*[npminstall:get] retry GET http://127.0.0.1:7001/@bimjk%2Fqiukai-test after 300ms, retry left 2, error: SyntaxError: Unexpected token l in JSON at position 0
⠧ [0/1] Installing @bimjk/qiukai-test@*[npminstall:get] retry GET http://127.0.0.1:7001/@bimjk%2Fqiukai-test after 400ms, retry left 1, error: SyntaxError: Unexpected token l in JSON at position 0
✖ Install fail! SyntaxError: Unexpected token l in JSON at position 0
SyntaxError: Unexpected token l in JSON at position 0
    at JSON.parse (<anonymous>)
    at _get (/Users/qiukai/.nvm/versions/node/v8.5.0/lib/node_modules/cnpm/node_modules/npminstall/lib/get.js:70:26)
    at _get.next (<anonymous>)
    at onFulfilled (/Users/qiukai/.nvm/versions/node/v8.5.0/lib/node_modules/cnpm/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

#### cnpm配置信息：
```
; cli configs
disturl = "https://npm.taobao.org/mirrors/node"
metrics-registry = "http://127.0.0.1:7001/"
registry = "http://127.0.0.1:7001/"
scope = ""
user-agent = "npm/5.4.2 node/v8.5.0 darwin x64"
userconfig = "/Users/qiukai/.cnpmrc"

; userconfig /Users/qiukai/.cnpmrc
//127.0.0.1:7001/:always-auth = true
//127.0.0.1:7001/:email = "admin@cnpmjs.org"
//127.0.0.1:7001/:username = "admin"
registry = "http://127.0.0.1:7001/"
```
#### index.js配置:
```
alwaysAuth: true,
```

#### 然后把alwaysAuth改为false又可以正常导入了

**Comment by lenodeCC** [comment]
碰到了同样的问题，但是使用npm是没有问题的
