### ISSUE TITLE
chromium镜像失效,望恢复

### ISSUE THREAD

**Issue by zhuoqi-chen** [cnpm/cnpmjs.org#1286]
安装puppeteer失败

`cnpm i puppeteer -S`

原因:chromium镜像源404,error如下

`ERROR: Failed to download Chromium r526987! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: Download failed: server returned code 404. URL: https://cdn.npm.taobao.org/dist/chromium-browser-snapshots/Linux_x64/526987/chrome-linux.zip
    at response (/data/node_modules/_puppeteer@1.0.0@puppeteer/lib/Downloader.js:228:21)
    at ClientRequest.require.request.res (/data/node_modules/_puppeteer@1.0.0@puppeteer/lib/Downloader.js:279:7)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)`

**Comment by SunyongLim-B2LiNK** [comment]
it seems taobao cdn npm has some problem so it can't be access to chromium now.

i resolved this issue with changing puppeteer download location
check this code
`PUPPETEER_DOWNLOAD_HOST=https://storage.googleapis.com.cnpmjs.org
npm i puppeteer`

another option is just install puppeteer 1.0 with outside of china, go to './node_modules/puppeteer/.local-chromium' and send back it to china

**Comment by dicebattle** [comment]
it seems taobao cdn npm has some problem so it can't be access to chromium now.

i resolved this issue with changing puppeteer download location
check this code (but it is pretty slow in even alicloud)
PUPPETEER_DOWNLOAD_HOST=https://storage.googleapis.com.cnpmjs.org npm i puppeteer

another option is just install puppeteer 1.0 with outside of china, go to './node_modules/puppeteer/.local-chromium' and send back it to china
