### ISSUE TITLE
部署好cnpm后，全部同步失败。尝试手动同步angular，报错如下

### ISSUE THREAD

**Issue by name100li** [cnpm/cnpmjs.org#1307]
Search Packages
Sync package angular
Sync started, please wait patiently.
Log

[2018-03-14 08:48:57] user: anonymous, sync angular worker start, 1 concurrency, nodeps: false, publish: false, syncUpstreamFirst: true
[2018-03-14 08:48:57] ----------------- Syncing upstream https://registry.npm.taobao.org/angular/sync/log/4901564 -------------------
[2018-03-14 08:48:58] [2018-03-14 23:48:57] user: anonymous, sync angular worker start, 1 concurrency, nodeps: false, publish: false
[2018-03-14 08:49:00] [2018-03-14 23:48:57] ----------------- Syncing upstream https://r.cnpmjs.org/angular/sync/log/2136699 -------------------
[2018-03-14 08:49:02] [2018-03-14 23:49:00] [2018-03-14 23:48:57] user: anonymous, sync angular worker start, 1 concurrency, nodeps: false, publish: false, syncUpstreamFirst: false
[2018-03-14 23:48:57] ----------------- Syncing angular -------------------
[2018-03-14 23:48:58] [c#0] [angular] package(https://replicate.npmjs.com/angular) status: 200, dist-tags: {"latest":"1.6.9","old":"1.2.32","previous_1_4":"1.4.14","previous_1_5":"1.5.11"}, time.modified: 2018-03-12T16:53:17.108Z, unpublished: null, start...
[2018-03-14 23:48:58]   [angular] found 0 missing star users
[2018-03-14 23:48:58]   [angular] all versions are exists
[2018-03-14 23:48:58]   [angular] 0 versions: [] need to deleted, but we won't delete them because `config.syncDeletedVersions=false`
[2018-03-14 23:48:58]   [angular] all 237 npm users exists
[2018-03-14 23:48:58] [c#0] [angular] synced success, 0 versions: 
[2018-03-14 23:48:58] ----------------- Synced angular success -------------------
[2018-03-14 23:48:58] ----------------- Syncing angular -------------------
[2018-03-14 23:48:58] [c#0] [angular] package(https://registry.npmjs.com/angular) status: 200, dist-tags: {"latest":"1.6.9","old":"1.2.32","previous_1_4":"1.4.14","previous_1_5":"1.5.11"}, time.modified: 2018-03-12T16:53:17.108Z, unpublished: null, start...
[2018-03-14 23:48:58]   [angular] found 0 missing star users
[2018-03-14 23:48:58]   [angular] all versions are exists
[2018-03-14 23:48:58]   [angular] 0 versions: [] need to deleted, but we won't delete them because `config.syncDeletedVersions=false`
[2018-03-14 23:48:58]   [angular] all 237 npm users exists
[2018-03-14 23:48:58] [c#0] [angular] synced success, 0 versions: 
[2018-03-14 23:48:58] ----------------- Synced angular success -------------------
[2018-03-14 23:48:58] [Upstream done] Sync angular package finished, 2 success, 0 fail
Success: [ angular, angular ]
Fail: [  ]
[2018-03-14 23:49:00] ----------------- Synced upstream https://r.cnpmjs.org/angular/sync/log/2136699 -------------------
[2018-03-14 23:49:00] ----------------- Syncing angular -------------------
[2018-03-14 23:49:00] [c#0] [angular] package(https://r.cnpmjs.org/angular) status: 200, dist-tags: {"latest":"1.6.9","old":"1.2.32","previous_1_4":"1.4.14","previous_1_5":"1.5.11"}, time.modified: 2018-02-02T13:13:57.000Z, unpublished: null, start...
[2018-03-14 23:49:00]   [angular] found 0 missing star users
[2018-03-14 23:49:00]   [angular] all versions are exists
[2018-03-14 23:49:00]   [angular] no versions need to deleted
[2018-03-14 23:49:00]   [angular] all 252 npm users exists
[2018-03-14 23:49:00] [c#0] [angular] synced success, 0 versions: 
[2018-03-14 23:49:00] ----------------- Synced angular success -------------------
[2018-03-14 23:49:00] [Upstream done] Sync angular package finished, 1 success, 0 fail
Success: [ angular ]
Fail: [  ]
[2018-03-14 08:49:02] ----------------- Synced upstream https://registry.npm.taobao.org/angular/sync/log/4901564 -------------------
[2018-03-14 08:49:02] ----------------- Syncing angular -------------------
[2018-03-14 08:49:02] [c#0] [angular] package(https://registry.npm.taobao.org/angular) status: 200, dist-tags: {"latest":"1.6.9","old":"1.2.32","previous_1_4":"1.4.14","previous_1_5":"1.5.11"}, time.modified: 2018-02-02T13:14:19.000Z, unpublished: null, start...
[2018-03-14 08:49:02] [c#0] [error] [angular] sync error: TypeError: Cannot read property 'findAll' of null
    at Object.exports.listModuleAbbreviatedsByName (/home/sunny/cnpmjs.org/services/package.js:327:45)
    at exports.listModuleAbbreviatedsByName.next ()
    at onFulfilled (/home/sunny/cnpmjs.org/node_modules/co/index.js:65:19)
    at /home/sunny/cnpmjs.org/node_modules/co/index.js:54:5
    at new Promise ()
    at co (/home/sunny/cnpmjs.org/node_modules/co/index.js:50:10)
    at toPromise (/home/sunny/cnpmjs.org/node_modules/co/index.js:118:63)
    at Array.map ()
    at arrayToPromise (/home/sunny/cnpmjs.org/node_modules/co/index.js:154:26)
    at toPromise (/home/sunny/cnpmjs.org/node_modules/co/index.js:120:49)
    at next (/home/sunny/cnpmjs.org/node_modules/co/index.js:99:29)
    at onFulfilled (/home/sunny/cnpmjs.org/node_modules/co/index.js:69:7)
    at /home/sunny/cnpmjs.org/node_modules/co/index.js:54:5
    at new Promise ()
    at co (/home/sunny/cnpmjs.org/node_modules/co/index.js:50:10)
    at toPromise (/home/sunny/cnpmjs.org/node_modules/co/index.js:118:63)
    at next (/home/sunny/cnpmjs.org/node_modules/co/index.js:99:29)
    at onFulfilled (/home/sunny/cnpmjs.org/node_modules/co/index.js:69:7)
    at 
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-03-14 08:49:02] ----------------- Synced angular fail -------------------
[2018-03-14 08:49:02] [done] Sync angular package finished, 0 success, 1 fail
Success: [  ]
Fail: [ angular ]
Sync angular complete!

**Comment by name100li** [comment]
自己找到了，在设置中配置：enableAbbreviatedMetadata: true，即可修复该问题。
谢谢伟大的GITHUT。O(∩_∩)O哈哈~
