### ISSUE TITLE
cannot sync many versions of "scratch-paint"

### ISSUE THREAD

**Issue by lgh06** [cnpm/cnpmjs.org#1318]
official npm repo：
https://www.npmjs.com/package/scratch-paint?activeTab=versions  

> [2018-04-09 16:24:02]     [scratch-paint:38] syncing, delay: 13192860187 ms, version: 0.1.0-prerelease.20171107154253, dist: {"shasum":"87869e5c3fb1a711db82b7f79d5ea54652bdcb7c","tarball":"https://registry.npmjs.org/scratch-paint/-/scratch-paint-0.1.0-prerelease.20171107154253.tgz"}, no deps: false, publish on cnpm: false, dependencies: 0, devDependencies: 0, syncDevDependencies: false
[2018-04-09 16:24:02]     [scratch-paint:38] sync error, version: 0.1.0-prerelease.20171107154253, SequelizeUniqueConstraintError: SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/home/www/git/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/query.js:149:14)
    at Query._callback (/home/www/git/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/home/www/git/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (/home/www/git/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/home/www/git/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/www/git/cnpmjs.org/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/www/git/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket. (/home/www/git/cnpmjs.org/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)

**Comment by fengmk2** [comment]
"0.2.0-prerelease.20180406202128" over 30 chars https://github.com/cnpm/cnpmjs.org/blob/master/docs/db.sql#L70

**Comment by fengmk2** [comment]
https://npm.taobao.org/sync/scratch-paint#logid=5906368

**Comment by fengmk2** [comment]
目前数据库数据量太大，没法修改 version 字段长度，暂时无法解决。

![image](https://user-images.githubusercontent.com/156269/38495673-02a0578a-3c2d-11e8-9b32-4c730e0bf624.png)

**Comment by fengmk2** [comment]
fixed on https://github.com/cnpm/cnpm/issues/291
