### ISSUE TITLE
同步出现数据库失败

### ISSUE THREAD

**Issue by Pennnn** [cnpm/cnpmjs.org#1331]
[@sindresorhus/is:1] sync error, version: 0.2.0, SequelizeDatabaseError: SequelizeBaseError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: 
     Incorrect string value: '\xF0\x9F\xA6\x84')...' for column 'description' at row 1
    at Query.formatError (/root/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/root/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/root/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (/root/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/root/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/root/cnpmjs.org/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/root/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket. (/root/cnpmjs.org/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)

同步的时候一直提示上诉错误

**Comment by Pennnn** [comment]
如 这个库的description字段有emoji表情就会出现这个错误 @sindresorhus/is;
我把数据库里的utf8 全部改成了uft8mb4 仍然不行 请问是需要别的步骤吗

**Comment by Pennnn** [comment]
http://blog.51cto.com/suifu/1853864 使用这方法把全部编码转成uft8mb4即可
