### ISSUE TITLE
cnpm install 被拒绝

### ISSUE THREAD

**Issue by icepy** [cnpm/cnpmjs.org#1339]
Hi，自己搭建了一个公司内部用的cnpmjs.org，publish也可以正常发布，但是安装包被拒绝。

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/xiangwenwen/.nvm/versions/node/v8.9.3/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '--registry=https://registry.npm.taobao.org',
1 verbose cli   '--cache=/Users/xiangwenwen/.npm/.cache/cnpm',
1 verbose cli   '--disturl=https://npm.taobao.org/dist',
1 verbose cli   '--userconfig=/Users/xiangwenwen/.cnpmrc',
1 verbose cli   'install',
1 verbose cli   '@entropage/nodejs-cnpm',
1 verbose cli   '--save' ]
2 info using npm@6.1.0
3 info using node@v8.9.3
4 verbose npm-session 59616be55c4ec369
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 http://localhost:7001/@entropage%2fnodejs-cnpm 92ms
8 http fetch GET 200 http://localhost:7001/@entropage/nodejs-cnpm/download/@entropage/nodejs-cnpm-1.0.2.tgz 31ms
9 silly pacote tag manifest for @entropage/nodejs-cnpm@latest fetched in 147ms
10 timing stage:loadCurrentTree Completed in 342ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 6ms
16 silly install loadAllDepsIntoIdealTree
17 timing stage:rollbackFailedOptional Completed in 0ms
18 timing stage:runTopLevelLifecycles Completed in 351ms
19 silly saveTree @entropage/nodejs-cnpm@1.0.2
19 silly saveTree └── jquery@3.3.1
20 verbose stack Error: Refusing to install package with name "@entropage/nodejs-cnpm" under a package
20 verbose stack also called "@entropage/nodejs-cnpm". Did you name your project the same
20 verbose stack as the dependency you're installing?
20 verbose stack
20 verbose stack For more information, see:
20 verbose stack     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
20 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:64:14)
20 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
20 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
20 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
20 verbose stack     at hasMinimumFields (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:30:12)
20 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
20 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
20 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
20 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:16:5
20 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
20 verbose stack     at Array.forEach (<anonymous>)
20 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
20 verbose stack     at Array.forEach (<anonymous>)
20 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
20 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:15:3)
20 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
21 verbose cwd /Users/xiangwenwen/nodejs-cnpm
22 verbose Darwin 17.5.0
23 verbose argv "/Users/xiangwenwen/.nvm/versions/node/v8.9.3/bin/node" "/usr/local/bin/npm" "--registry=https://registry.npm.taobao.org" "--cache=/Users/xiangwenwen/.npm/.cache/cnpm" "--disturl=https://npm.taobao.org/dist" "--userconfig=/Users/xiangwenwen/.cnpmrc" "install" "@entropage/nodejs-cnpm" "--save"
24 verbose node v8.9.3
25 verbose npm  v6.1.0
26 error code ENOSELF
27 error Refusing to install package with name "@entropage/nodejs-cnpm" under a package
27 error also called "@entropage/nodejs-cnpm". Did you name your project the same
27 error as the dependency you're installing?
27 error
27 error For more information, see:
27 error     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
28 verbose exit [ 1, true ]
```
翻了很久，没搞明白，不知道作者可以帮忙看看么。

config:

```
module.exports = {
  admin: {
    'icepy': 'xiangwenwe@foxmail.com'
  },
  database:{
    db: 'cnpmjs_private',
    username: 'root',
    password: '',
    dialect: 'mysql',
    host: '127.0.0.1',
    port: 3306,
    pool: {
      maxConnections: 10,
      minConnections: 0,
      maxIdleTime: 30000
    }
  },
  registryHost:'localhost:7001',
  scopes:['@entropage']
}
```

**Comment by J-DuYa** [comment]
是什么原因导致的呢
