### ISSUE TITLE
部分模块 sync 失败

### ISSUE THREAD

**Issue by yeli19950109** [cnpm/cnpmjs.org#1350]
>>>
[2018-06-22 09:22:09]     [cordova:60] syncing, delay: 59351311523 ms, version: 6.3.1-
nightly.2016.8.4.5e6e3bf1, dist: {"shasum":"3c421ba3068713bf9b757b2cccfe72a024d47b3a","tarball":"http://registry.npmjs.org/cordova/-/cordova-6.3.1-nightly.2016.8.4.5e6e3bf1.tgz"}, no deps: false, publish on cnpm: false, dependencies: 7, devDependencies: 0, syncDevDependencies: false
[2018-06-22 09:20:46] [2018-06-22 09:22:11] [2018-06-22 09:22:09]     [cordova:60] sync error, version: 6.3.1-nightly.2016.8.4.5e6e3bf1, SequelizeUniqueConstraintError: SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/home/www/git/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/query.js:149:14)
    at Query._callback (/home/www/git/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/home/www/git/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (/home/www/git/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/home/www/git/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/www/git/cnpmjs.org/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/www/git/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket. (/home/www/git/cnpmjs.org/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
<<<

**Comment by yeli19950109** [comment]
cordova sync 老是这样

**Comment by yeli19950109** [comment]
Unhandled rejection SequelizeConnectionError: Cannot enqueue Quit after fatal error.
    at Quit._callback (D:\cnpmjs.org\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:136:30)
    at Quit.Sequence.end (D:\cnpmjs.org\node_modules\mysql\lib\protocol\sequences\Sequence.js:88:24)
    at Quit.end (D:\cnpmjs.org\node_modules\mysql\lib\protocol\sequences\Quit.js:24:28)
    at D:\cnpmjs.org\node_modules\mysql\lib\protocol\Protocol.js:225:14
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

{ Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  headerSent: true }
Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
