### ISSUE TITLE
retry on sync tgz 404

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#1362]
wait for 10s and retry again

```log
[2018-07-16 21:53:08] ----------------- Syncing @vue/cli-ui -------------------
[2018-07-16 21:53:12] [2018-07-16 21:53:11] [2018-07-16 21:53:10] [c#0] [@vue/cli-ui] official registry({"latest":"3.0.0-rc.4"}, "2018-07-13T17:13:48.732Z"), replicate({"latest":"3.0.0-rc.5"}, "2018-07-16T13:53:05.294Z")
[2018-07-16 21:53:10] [c#0] [@vue/cli-ui] package(https://replicate.npmjs.com/@vue%2fcli-ui) status: 200, dist-tags: {"latest":"3.0.0-rc.5"}, time.modified: 2018-07-16T13:53:05.294Z, unpublished: null, start...
[2018-07-16 21:53:10]   [@vue/cli-ui] found 0 missing star users
[2018-07-16 21:53:10]   [@vue/cli-ui] 1 versions need to sync
[2018-07-16 21:53:10]     [@vue/cli-ui:0] syncing, delay: 5695 ms, version: 3.0.0-rc.5, dist: {"shasum":"e40114a74822b6e27ab42b1d63bda57be5e6797c","tarball":"https://registry.npmjs.org/@vue/cli-ui/-/cli-ui-3.0.0-rc.5.tgz","fileCount":314,"unpackedSize":7620528}, no deps: false, publish on cnpm: false, dependencies: 27, devDependencies: 0, syncDevDependencies: false
[2018-07-16 21:53:10]     add dependencies: @akryum/winattr
[2018-07-16 21:53:10]     add dependencies: @vue/cli-shared-utils
[2018-07-16 21:53:10]     add dependencies: chalk
[2018-07-16 21:53:10]     add dependencies: clone
[2018-07-16 21:53:10]     add dependencies: deepmerge
[2018-07-16 21:53:10]     add dependencies: execa
[2018-07-16 21:53:10]     add dependencies: express-history-api-fallback
[2018-07-16 21:53:10]     add dependencies: fs-extra
[2018-07-16 21:53:10]     add dependencies: globby
[2018-07-16 21:53:10]     add dependencies: graphql
[2018-07-16 21:53:10]     add dependencies: graphql-tag
[2018-07-16 21:53:10]     add dependencies: graphql-type-json
[2018-07-16 21:53:10]     add dependencies: javascript-stringify
[2018-07-16 21:53:10]     add dependencies: js-yaml
[2018-07-16 21:53:10]     add dependencies: launch-editor
[2018-07-16 21:53:10]     add dependencies: lodash.merge
[2018-07-16 21:53:10]     add dependencies: lowdb
[2018-07-16 21:53:10]     add dependencies: lru-cache
[2018-07-16 21:53:10]     add dependencies: node-ipc
[2018-07-16 21:53:10]     add dependencies: node-notifier
[2018-07-16 21:53:10]     add dependencies: parse-git-config
[2018-07-16 21:53:10]     add dependencies: portfinder
[2018-07-16 21:53:10]     add dependencies: semver
[2018-07-16 21:53:10]     add dependencies: shortid
[2018-07-16 21:53:10]     add dependencies: terminate
[2018-07-16 21:53:10]     add dependencies: vue-cli-plugin-apollo
[2018-07-16 21:53:10]     add dependencies: watch
[2018-07-16 21:53:14] [2018-07-16 21:53:13] [2018-07-16 21:53:12]     [@vue/cli-ui:0] sync error, version: 3.0.0-rc.5, DownloadTarballError: DownloadTarballError: Download https://registry.npmjs.org/@vue/cli-ui/-/cli-ui-3.0.0-rc.5.tgz fail, status: 404
    at SyncModuleWorker._syncOneVersion (/home/www/git/cnpmjs.org/controllers/sync_module_worker.js:1336:17)
    at SyncModuleWorker._syncOneVersion.next (<anonymous>)
    at onFulfilled (/home/www/git/cnpmjs.org/node_modules/co/index.js:65:19)
    at <anonymous>

```

**Comment by fengmk2** [comment]
7月份有1万多次 404

```log
[2018-07-20 13:20:18.798][1858] [sync_module_worker] Download http://registry.npmjs.org/metalsmith/-/metalsmith-0.2.0.tgz fail, status: 404
[2018-07-20 13:20:19.691][1858] [sync_module_worker] Download http://registry.npmjs.org/metalsmith/-/metalsmith-0.2.1.tgz fail, status: 404
[2018-07-20 13:31:08.263][1858] [sync_module_worker] Download http://registry.npmjs.org/karma-browserify/-/karma-browserify-4.1.1.tgz fail, status: 404
[2018-07-20 13:34:13.579][1863] [sync_module_worker] Download http://registry.npmjs.org/karma-browserify/-/karma-browserify-4.1.1.tgz fail, status: 404
[2018-07-20 13:36:55.651][1858] [sync_module_worker] Download https://registry.npmjs.org/froncubator-bridge/-/froncubator-bridge-0.0.22.tgz fail, status: 404
[2018-07-20 13:43:40.821][1863] [sync_module_worker] Download http://registry.npmjs.org/karma-browserify/-/karma-browserify-4.1.1.tgz fail, status: 404
[2018-07-20 13:58:52.694][1863] [sync_module_worker] Download http://registry.npmjs.org/karma-browserify/-/karma-browserify-4.1.1.tgz fail, status: 404
[2018-07-20 14:03:27.727][1863] [sync_module_worker] Download http://registry.npmjs.org/webpack-config/-/webpack-config-1.1.0.tgz fail, status: 404
[2018-07-20 14:06:29.648][1858] [sync_module_worker] Download https://registry.npmjs.org/npmrc-cli/-/npmrc-cli-2.1.1.tgz fail, status: 404
[2018-07-20 14:07:03.743][1863] [sync_module_worker] Download http://registry.npmjs.org/karma-browserify/-/karma-browserify-4.1.1.tgz fail, status: 404
[2018-07-20 14:08:20.656][1858] [sync_module_worker] Download http://registry.npmjs.org/karma-browserify/-/karma-browserify-4.1.1.tgz fail, status: 404
[2018-07-20 14:09:02.774][1863] [sync_module_worker] Download http://registry.npmjs.org/fibers/-/fibers-1.0.11.tgz fail, status: 404
[2018-07-20 14:09:23.586][1863] [sync_module_worker] Download http://registry.npmjs.org/gulp-print/-/gulp-print-1.0.1.tgz fail, status: 404
[2018-07-20 14:10:14.497][1863] [sync_module_worker] Download http://registry.npmjs.org/karma-browserify/-/karma-browserify-4.1.1.tgz fail, status: 404
[2018-07-20 14:22:00.637][1858] [sync_module_worker] Download http://registry.npmjs.org/ioredis/-/ioredis-1.0.5.tgz fail, status: 404
[2018-07-20 14:23:33.197][1863] [sync_module_worker] Download http://registry.npmjs.org/ioredis/-/ioredis-1.0.5.tgz fail, status: 404
[2018-07-20 14:23:38.480][1858] [sync_module_worker] Download http://registry.npmjs.org/ioredis/-/ioredis-1.0.5.tgz fail, status: 404
www@iZ22dlerhseZ:~/logs/cnpmjs.org$ grep 'fail, status' sync_info.2018-07-*|wc -l
17317

```

**Comment by fengmk2** [comment]
已经发布很久还是 404 的要忽略掉

```log
[2018-07-20 14:36:37.913][6762] [sync_module_worker] delay: 102192073461 ms, publish_time: 2015-04-24 19:55:24.452, start sync ioredis@1.0.5
[2018-07-20 14:36:37.922][6762] [sync_module_worker] downloading "http://registry.npmjs.org/ioredis/-/ioredis-1.0.5.tgz" to "/home/www/logs/cnpmjs.org/downloads/ioredis-1.0.5.46b0ce46680be2337c629c48bf80174a.tgz"
[2018-07-20 14:36:38.764][6762] [sync_module_worker] Download http://registry.npmjs.org/ioredis/-/ioredis-1.0.5.tgz fail, status: 404

```
