### ISSUE TITLE
cnpm install 会报错response 405 status

### ISSUE THREAD

**Issue by SnowFlowers** [cnpm/cnpmjs.org#1379]
Install fail! Error: [qrcode@^1.2.0] GET http://192.168.92.24:7001/qrcode/%3E%3D1.2.0%20%3C2.0.0 response 405 status

仓库是本地私库的地址
```
✖ Install fail! Error: [qrcode@^1.2.0] GET http://192.168.92.24:7001/qrcode/%3E%3D1.2.0%20%3C2.0.0 response 405 status
Error: [qrcode@^1.2.0] GET http://192.168.92.24:7001/qrcode/%3E%3D1.2.0%20%3C2.0.0 response 405 status
    at get (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/get.js:51:17)
    at get.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npminstall version: 2.26.4
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/Paco/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://192.168.92.24:7001/
```

**Comment by rhinoceros** [comment]
@开头的包，版本不要用regex匹配；

**Comment by rhinoceros** [comment]
```
检查是否服务端问题，或者网络问题:
curl http://192.168.92.24:7001/qrcode/%3E%3D1.2.0%20%3C2.0.0
或者浏览器打开
http://192.168.92.24:7001/qrcode/%3E%3D1.2.0%20%3C2.0.0

检查一下你的npm/cnpm客户端是不是比较老了，可以升级一个新版本试试

如果还不行，建议你提供这些信息：
     你执行的命令，及npm/cnpm 的版本；
     package.json文件；
     在192.168.92.24安装服务的版本号；
     config/index.js中的这两个字段：
            config.syncByInstall
            config.enablePrivate 


```
