### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by MIyulong** [cnpm/cnpmjs.org#1390]
After cnpm install, then i get these: 
```
➜  b-system git:(dev-2) ✗ cnpm install
⠦ [21/55] Installing source-map@^0.5.3
WARN node unsupported "node@v6.11.3" is incompatible with eslint@^5.6.0, expected node@^6.14.0 || ^8.10.0 || >=9.10.0
✖ Install fail! Error: GET https://registry.npm.taobao.org/frieeslintrc.jsndly-errors-webpack-plugin response 404 status
Error: GET https://registry.npm.taobao.org/frieeslintrc.jsndly-errors-webpack-plugin response 404 status
    at get (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/get.js:57:17)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
npminstall version: 3.12.0
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/Users/yulong/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org
```
as for 'frieeslintrc.jsndly-errors-webpack-plugin', i search any information abount this,
so what can I do to run it successfully

**Comment by fengmk2** [comment]
https://registry.npmjs.org/frieeslintrc.jsndly-errors-webpack-plugin is not exists.
