### ISSUE TITLE
在界面上点同步之后，最后都会报错，请问是什么问题

### ISSUE THREAD

**Issue by stephen7729** [cnpm/cnpmjs.org#1394]
```[2018-10-10 15:42:05] user: anonymous, sync vuepress worker start, 1 concurrency, nodeps: false, publish: false, syncUpstreamFirst: true
[2018-10-10 15:42:05] ----------------- Syncing upstream https://registry.npm.taobao.org/vuepress/sync/log/4967552 -------------------
[2018-10-10 15:42:09] [2018-10-10 15:42:48] user: anonymous, sync vuepress worker start, 1 concurrency, nodeps: false, publish: false, syncUpstreamFirst: true
[2018-10-10 15:42:48] ----------------- Syncing upstream https://r.cnpmjs.org/vuepress/sync/log/339664 -------------------
[2018-10-10 15:42:51] [2018-10-10 15:42:48] user: anonymous, sync vuepress worker start, 1 concurrency, nodeps: false, publish: false, syncUpstreamFirst: false
[2018-10-10 15:42:48] ----------------- Syncing vuepress -------------------
[2018-10-10 15:42:49] [c#0] [vuepress] official registry({"latest":"0.14.4","next":"1.0.0-alpha.9"}, "2018-10-10T06:03:51.006Z"), replicate({"latest":"0.14.4","next":"1.0.0-alpha.9"}, "2018-10-10T06:03:51.006Z")
[2018-10-10 15:42:49] [c#0] [vuepress] package(https://replicate.npmjs.com/vuepress) status: 200, dist-tags: {"latest":"0.14.4","next":"1.0.0-alpha.9"}, time.modified: 2018-10-10T06:03:51.006Z, unpublished: null, start...
[2018-10-10 15:42:49]   [vuepress] found 0 missing star users
[2018-10-10 15:42:49]   [vuepress] all versions are exists
[2018-10-10 15:42:49]   [vuepress] no versions need to deleted
[2018-10-10 15:42:49]   [vuepress] all 2 npm users exists
[2018-10-10 15:42:49] [c#0] [vuepress] synced success, 0 versions: 
[2018-10-10 15:42:49] ----------------- Synced vuepress success -------------------
[2018-10-10 15:42:49] [Upstream done] Sync vuepress package finished, 1 success, 0 fail
Success: [ vuepress ]
Fail: [  ]
[2018-10-10 15:42:51] ----------------- Synced upstream https://r.cnpmjs.org/vuepress/sync/log/339664 -------------------
[2018-10-10 15:42:51] ----------------- Syncing vuepress -------------------
[2018-10-10 15:42:51] [c#0] [vuepress] package(https://r.cnpmjs.org/vuepress) status: 200, dist-tags: {"latest":"0.14.4","next":"1.0.0-alpha.9"}, time.modified: 2018-10-10T06:03:58.000Z, unpublished: null, start...
[2018-10-10 15:42:51]   [vuepress] found 0 missing star users
[2018-10-10 15:42:51]   [vuepress] all versions are exists
[2018-10-10 15:42:51]   [vuepress] no versions need to deleted
[2018-10-10 15:42:51]   [vuepress] all 2 npm users exists
[2018-10-10 15:42:51] [c#0] [vuepress] synced success, 0 versions: 
[2018-10-10 15:42:51] ----------------- Synced vuepress success -------------------
[2018-10-10 15:42:51] [Upstream done] Sync vuepress package finished, 1 success, 0 fail
Success: [ vuepress ]
Fail: [  ]
[2018-10-10 15:42:09] ----------------- Synced upstream https://registry.npm.taobao.org/vuepress/sync/log/4967552 -------------------
[2018-10-10 15:42:09] ----------------- Syncing vuepress -------------------
[2018-10-10 15:42:09] [c#0] [vuepress] package(https://registry.npm.taobao.org/vuepress) status: 200, dist-tags: {"latest":"0.14.4","next":"1.0.0-alpha.9"}, time.modified: 2018-10-10T06:04:00.000Z, unpublished: null, start...
[2018-10-10 15:42:09]   [vuepress] found 1 missing star users
[2018-10-10 15:42:09]   [vuepress] all versions are exists
[2018-10-10 15:42:09]   [vuepress] no versions need to deleted
[2018-10-10 15:42:09] [c#0] [error] [vuepress] sync error: TypeError: Cannot read property 'find' of null
    at Object.exports.savePackageReadme (/usr/local/cnpm/cnpmjs.org-master/services/package.js:490:41)
    at exports.savePackageReadme.next ()
    at onFulfilled (/usr/local/cnpm/cnpmjs.org-master/node_modules/co/index.js:65:19)
    at /usr/local/cnpm/cnpmjs.org-master/node_modules/co/index.js:54:5
    at new Promise ()
    at co (/usr/local/cnpm/cnpmjs.org-master/node_modules/co/index.js:50:10)
    at toPromise (/usr/local/cnpm/cnpmjs.org-master/node_modules/co/index.js:118:63)
    at next (/usr/local/cnpm/cnpmjs.org-master/node_modules/co/index.js:99:29)
    at onFulfilled (/usr/local/cnpm/cnpmjs.org-master/node_modules/co/index.js:69:7)
[2018-10-10 15:42:09] ----------------- Synced vuepress fail -------------------
[2018-10-10 15:42:09] [done] Sync vuepress package finished, 0 success, 1 fail
Success: [  ]
Fail: [ vuepress ]
Sync vuepress complete!

**Comment by stephen7729** [comment]
一开始安装过，后来因为硬盘不够大，又扩容过，删过数据库。
![image](https://user-images.githubusercontent.com/25659117/46926902-5ddf7500-d065-11e8-81c8-708d571b9461.png)
有这张表

**Comment by rhinoceros** [comment]
检查一下：config/index.js 中的这个配置：enableAbbreviatedMetadata 
  // https://github.com/cnpm/cnpmjs.org/issues/1149
  // if enable this option, must create module_abbreviated and package_readme table in database
  enableAbbreviatedMetadata: false,

**Comment by rhinoceros** [comment]
检查一下：config/index.js 中的这个配置：enableAbbreviatedMetadata

**Comment by stephen7729** [comment]
![image](https://user-images.githubusercontent.com/25659117/46927387-bb74c100-d067-11e8-99d2-09d073fc7914.png)

**Comment by rhinoceros** [comment]
改成true试试，改之前做一下备份。

**Comment by stephen7729** [comment]
好的，我试试

**Comment by stephen7729** [comment]
```
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@2.5.4
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@2.5.3
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@2.5.1
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@2.5.0
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@2.0.5
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@2.0.4
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@2.0.3
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@2.0.2
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@2.0.1
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@2.0.0
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@1.4.9
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@1.4.8
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@1.4.7
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@1.4.6
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@1.4.5
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@1.4.4
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@1.4.3
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@1.4.2
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@1.4.1
[2018-10-15 10:50:49]     saved moduleAbbreviateds, module: vuescroll@1.4.0
[2018-10-15 10:50:49] [c#0] [vuescroll] synced success, 2 versions: 4.9.0-beta.3, 4.9.0-beta.4
[2018-10-15 10:50:49] ----------------- Synced vuescroll success -------------------
[2018-10-15 10:50:49] [done] Sync vuescroll package finished, 1 success, 0 fail
Success: [ vuescroll ]
Fail: [  ]
Sync vuescroll complete!
```
已经成功，感谢大神！

**Comment by latel** [comment]
有用
