### ISSUE TITLE
网页上同步时报错 You may only yield a function, promise, generator, array, or object

### ISSUE THREAD

**Issue by sunxiuguo** [cnpm/cnpmjs.org#1402]
[2018-10-30 06:58:25]     [mocha:26] tries: 3, delay: 216315693003 ms, sync error, version: 0.7.1, TypeError: TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed: "[object Object]"
    at next (/med/node_modules/co/index.js:101:25)
    at onFulfilled (/med/node_modules/co/index.js:69:7)
    at /med/node_modules/co/index.js:54:5
    at Promise ()
    at Function.co (/med/node_modules/co/index.js:50:10)
    at Function.toPromise (/med/node_modules/co/index.js:118:63)
    at next (/med/node_modules/co/index.js:99:29)
    at onFulfilled (/med/node_modules/co/index.js:69:7)
    at 
    at process._tickDomainCallback (internal/process/next_tick.js:208:7)

在网页上sync一个包的时候，总是会报这种错误，一直在retry，请问这个是什么问题呢

**Comment by sunxiuguo** [comment]
我查看了代码中使用co的地方都是用的generator

**Comment by sunxiuguo** [comment]
@fengmk2 大佬有时间帮忙看一下嘛

**Comment by sunxiuguo** [comment]
是我自己写的amson s3的函数有问题...closed
