### ISSUE TITLE
搭建私有库，成功Publish私有包后，安装时报错sha不匹配

### ISSUE THREAD

**Issue by sunxiuguo** [cnpm/cnpmjs.org#1406]
如题。
我搭建私有库后，接入s3存储包文件，同步和下载依赖包都正常。
但是测试发布npm包，显示publish成功，并且npm view @scope/moduleName也能正确显示出包的信息

```
root@bogon:~/work/npm_test# npm view xxx-test-final-2

xxx-test-final-2@0.1.0 | Proprietary | deps: 10 | versions: 1
## Project setup ``` yarn install ```

dist
.tarball: http://xxxxxxxxxx/xxx-test-final-2/download/sunxiuguo-test-final-2-0.1.0.tgz
.shasum: 362fa64a44dbabe028dd2ba4fd5fe93ed8ec1c6f

dependencies:
hoek: ^6.0.3                    register-service-worker: ^1.0.0 vue: ^2.5.17
is-type-of: ^1.2.1              vue-class-component: ^6.0.0     vuex: ^3.0.1
react: ^16.6.0                  vue-property-decorator: ^7.0.0
redux: ^4.0.1                   vue-router: ^3.0.1

maintainers:
- xxxx <xxx@xxx.com>

dist-tags:
latest: 0.1.0

published 17 minutes ago by xxxx <xxx@xxxx.com>
```

**但是安装@scope/moduleName时总是会报错**

```
events.js:167░░░░░░⸩ ⠙ extract:scheduler: http fetch POST 500 http://registry.npm.xxxxx-xxxxx.com/-/npm/v1/security/audit
      throw er; // Unhandled 'error' event
      ^

Error: sha1-Ni+mSkTbq+Ao3Suk/V/pPtjsHG8= integrity checksum failed when using sha1: wanted sha1-Ni+mSkTbq+Ao3Suk/V/pPtjsHG8= but got sha512-J8dGcK23UHX60FjVzq97IMTneGyDuuijL2Jvl4KvNMmjPCBG72D9Knh403jin+yFGAa72aZ4ePOp8c2kgwdj/Q== sha1-vyGp6PvFo4RvsFtPoIWeCReyIC8=. (2 bytes)
    at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:310:19)
    at Transform.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at err (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/cache.js:191:31)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:75:7
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:31:21)
    at WriteStream.f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at WriteStream.onclose (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:48:54)
    at WriteStream.emit (events.js:187:15)
    at WriteStream.destroy (/usr/local/lib/node_modules/npm/node_modules/flush-write-stream/index.js:53:8)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:45:45
    at call (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:72:25
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Transform.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:31:21)
    at Transform.f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Transform.onerror (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:43:12)
events.js:167░░░░░░⸩ ⠙ extract:core-util-is: http fetch POST 500 http://registry.npm.xxxxx-xxxx.com/-/npm/v1/security/au
      throw er; // Unhandled 'error' event
      ^

Error: sha1-Ni+mSkTbq+Ao3Suk/V/pPtjsHG8= integrity checksum failed when using sha1: wanted sha1-Ni+mSkTbq+Ao3Suk/V/pPtjsHG8= but got sha512-J8dGcK23UHX60FjVzq97IMTneGyDuuijL2Jvl4KvNMmjPCBG72D9Knh403jin+yFGAa72aZ4ePOp8c2kgwdj/Q== sha1-vyGp6PvFo4RvsFtPoIWeCReyIC8=. (2 bytes)
    at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:310:19)
    at Transform.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at err (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/cache.js:191:31)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:75:7
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:31:21)
    at WriteStream.f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at WriteStream.onclose (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:48:54)
    at WriteStream.emit (events.js:187:15)
    at WriteStream.destroy (/usr/local/lib/node_modules/npm/node_modules/flush-write-stream/index.js:53:8)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:45:45
    at call (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/npm/node_modules/pump/index.js:72:25
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Transform.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/pump/index.js:31:21)
    at Transform.f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Transform.onerror (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:43:12)
npm WARN @xxxxx/npm_test@1.0.0 No repository field.

npm ERR! cancel after 1 retries!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sunxiuguo/.npm/_logs/2018-11-12T02_53_40_209Z-debug.log

```
我查看了私有源服务器上的日志~/.cnpmjs.org/logs，有如下报错提示
```
{ Error: unexpected end of file
    at Unzip.zlibOnError (zlib.js:152:15) errno: -5, code: 'Z_BUF_ERROR' }
```

尝试过
```
rm -rf node_modules
npm cache clean --force
```
但是没有效果，还是报错。

问题是测试期间，我切换Npm版本到4.6.1时，安装成功了一次。。。然后再怎么安装就都失败，无论什么版本。。

现在怀疑是我nfs接入s3的方法写的有问题，下面是我的download 和 createDownloadStream方法，
```
AwsWrapper.prototype.download = function* (key, filepath, options) {
    const params = { Bucket: this.bucket, Key: trimKey(key) };
    logger.syncInfo(`进入aws->download key=${key} trimKey=${trimKey(key)} filepath=${filepath}`);

    const target = fs.createWriteStream(filepath);
    this.client.getObject(params, function(err, data) {
        if (err) {
            logger.syncInfo(`download: ${err.stack}`); // an error occurred
        } else {
            target.write(data.Body.toString('utf-8'))
        }
    });
};

AwsWrapper.prototype.createDownloadStream = function* (key, options) {
    const params = { Bucket: this.bucket, Key: trimKey(key) };
    return (yield this.client.getObject(params)).Body.toString('utf-8');
};
```

本地环境
node 10.13.0
npm 6.4.1
cnpm 6.0.0

私有源服务器上的环境为
cnpmjs.org version: 3.0.0-rc.5
Node.js version: v8.1.2

**Comment by rhinoceros** [comment]
**failed when using sha1: wanted sha1 but got sha512**
看着像本地npm的问题

看看这个issue有没有参考的地方：
https://github.com/nodejs/node/issues/13635
删除package-lock.json这个文件试试
rm -rf package-lock.json
rm -rf node_modules
npm cache clean --force

看这个issue有人这么搞过：
https://github.com/cncjs/cncjs/issues/172
npm cache clean --force
npm install --update-binary --no-shrinkwrap


**这个的500，使用cnpmjs.org是肯定会有的一个error**
```http fetch POST 500 http://registry.npm.guazi-apps.com/-/npm/v1/security/audit```

**Comment by githoniel** [comment]
this is a bug of nodejs。 I do not know why clear. But 
https://github.com/verdaccio/verdaccio/issues/301 will resolve your problem I think

**Comment by cp1001** [comment]
从私有库下载的包校验不通过，很有可能下载的包有问题。如果是这样的话，在本地做任何操作都无效，需要检查私有源上该包是否正确，是否完整下载了。某个包的某个版本，下载到私有源缓存时发生错误，这样你从私有源下载永远就是错误的了

**Comment by alsotang** [comment]
这个500的我修过，最新的cnpm对于 `/-/npm/v1/security/audit` 路由是有转发的了。
