### ISSUE TITLE
sync @pulumi/pulumi 报错，求助

### ISSUE THREAD

**Issue by huguobo** [cnpm/cnpmjs.org#1444]
[2019-03-07 14:45:03]     [@pulumi/pulumi:78] syncing, delay: 24042050974 ms, version: 0.12.3-dev-1527898283-g261fa865, dist: {"shasum":"262dbf673a10629d3ba0bdbd25c612649f9b4d4e","size":100857,"noattachment":false,"tarball":"https://r.cnpmjs.org/@pulumi/pulumi/download/@pulumi/pulumi-0.12.3-dev-1527898283-g261fa865.tgz"}, no deps: false, publish on cnpm: false, dependencies: 7, devDependencies: 0, syncDevDependencies: false
[2019-03-07 14:45:17]     at Query.formatError (/home/mk2/git/npm.taobao.org/node_modules/sequelize/lib/dialects/mysql/query.js:149:14)
    at Query. (/home/mk2/git/npm.taobao.org/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query. (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/Connection.js:502:10)
    at Query._callback (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/Connection.js:468:16)
    at Query.Sequence.end (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket. (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/Connection.js:91:28)
    at Socket. (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2019-03-07 14:45:15]     [@pulumi/pulumi:127] syncing, delay: 22310888384 ms, version: 0.14.1-dev-1529629283-g89b052fc, dist: {"shasum":"ff4c3dbdc1629ec2a758736f474bb2e41a8fbb9a","size":104475,"noattachment":false,"tarball":"https://r.cnpmjs.org/@pulumi/pulumi/download/@pulumi/pulumi-0.14.1-dev-1529629283-g89b052fc.tgz"}, no deps: false, publish on cnpm: false, dependencies: 7, devDependencies: 0, syncDevDependencies: false
[2019-03-07 14:45:16]     [@pulumi/pulumi:127] tries: 3, delay: 22310888594 ms, sync error, version: 0.14.1-dev-1529629283-g89b052fc, SequelizeUniqueConstraintError: SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/home/mk2/git/npm.taobao.org/node_modules/sequelize/lib/dialects/mysql/query.js:149:14)
    at Query. (/home/mk2/git/npm.taobao.org/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query. (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/Connection.js:502:10)
    at Query._callback (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/Connection.js:468:16)
    at Query.Sequence.end (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket. (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/Connection.js:91:28)
    at Socket. (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2019-03-07 14:45:16]     [@pulumi/pulumi:128] syncing, delay: 22250435162 ms, version: 0.14.1-dev-1529689703-g34be8203, dist: {"shasum":"fb6ddeda8e89cd926a3a6c6a940e094e0a28a830","size":104500,"noattachment":false,"tarball":"https://r.cnpmjs.org/@pulumi/pulumi/download/@pulumi/pulumi-0.14.1-dev-1529689703-g34be8203.tgz"}, no deps: false, publish on cnpm: false, dependencies: 7, devDependencies: 0, syncDevDependencies: false
[2019-03-07 14:45:16]     [@pulumi/pulumi:128] tries: 3, delay: 22250435378 ms, sync error, version: 0.14.1-dev-1529689703-g34be8203, SequelizeUniqueConstraintError: SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/home/mk2/git/npm.taobao.org/node_modules/sequelize/lib/dialects/mysql/query.js:149:14)
    at Query. (/home/mk2/git/npm.taobao.org/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query. (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/Connection.js:502:10)
    at Query._callback (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/Connection.js:468:16)
    at Query.Sequence.end (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket. (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/Connection.js:91:28)
    at Socket. (/home/mk2/git/npm.taobao.org/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by alsotang** [comment]
```
> '0.14.1-dev-1529629283-g89b052fc'.length
31
```

@fengmk2 包名过长？

**Comment by alsotang** [comment]
不过你如果使用正常的版本号应该不受影响吧？ @huguobo

**Comment by fengmk2** [comment]
> ```
> > '0.14.1-dev-1529629283-g89b052fc'.length
> 31
> ```
> @fengmk2 版本名过长？

对，目前只支持 30 https://github.com/cnpm/cnpmjs.org/blob/master/models/module.js#L51

**Comment by fengmk2** [comment]
正常的版本不受影响 https://npm.taobao.org/package/@pulumi/pulumi

**Comment by huguobo** [comment]
> 不过你如果使用正常的版本号应该不受影响吧？ @huguobo

嗯嗯，谢谢回复，正常版本确实不会，但是每次sync upstream 都有大量的报错~，我把我们的module version调整到了varchar(50)，但是sync upstream https://registry.npm.taobao.org 还是会报错，没有扩充这个字段的打算吗~

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpm/issues/291

**Comment by fengmk2** [comment]
@huguobo fixed
