### ISSUE TITLE
cnpm can't use

### ISSUE THREAD

**Issue by ChrisChenSZ** [cnpm/cnpmjs.org#1469]
[0/80] Installing stylelint-scss@^3.4.0[npminstall:get] retry GET https://registry.npm.taobao.org/clipboard after 100ms, retry left 4, error: JSONResponseFormatError: Unexpected token < in JSON at position 0 (data json format: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\r\n<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<h1>502 Bad Gateway</h1>\r\n<p>The proxy server received an invalid response from an upstream server.</body>\r\n</html>\r\n"), GET https://registry.npm.taobao.org/clipboard 502 (connected: true, keepalive socket: false, agent status: {"createSocketCount":12,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":6,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"r.cnpmjs.org:443:::::::::":1},"sockets":{"registry.npm.taobao.org:443:::::::true::":10},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 1)
headers: {"date":"Fri, 24 May 2019 02:30:54 GMT","content-type":"text/html","content-length":"246","connection":"keep-alive"}, status: 502, headers: {"date":"Fri, 24 May 2019 02:30:54 GMT","content-type":"text/html","content-length":"246","connection":"keep-alive"}, 
stack: JSONResponseFormatError: Unexpected token < in JSON at position 0 (data json format: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\r\n<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<h1>502 Bad Gateway</h1>\r\n<p>The proxy server received an invalid response from an upstream server.</body>\r\n</html>\r\n"), GET https://registry.npm.taobao.org/clipboard 502 (connected: true, keepalive socket: false, agent status: {"createSocketCount":12,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":6,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"r.cnpmjs.org:443:::::::::":1},"sockets":{"registry.npm.taobao.org:443:::::::true::":10},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 1)
headers: {"date":"Fri, 24 May 2019 02:30:54 GMT","content-type":"text/html","content-length":"246","connection":"keep-alive"}
    at JSON.parse (<anonymous>)
    at parseJSON (/root/nvm/versions/node/v8.15.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:1150:24)
    at /root/nvm/versions/node/v8.15.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:880:23
    at decodeContent (/root/nvm/versions/node/v8.15.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:687:14)
    at IncomingMessage.<anonymous> (/root/nvm/versions/node/v8.15.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:861:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by mystylemylife** [comment]
同求，现在无法cnpm install了

**Comment by raylee1994** [comment]
搞了一上午，原来都遇到这个问题了

**Comment by zaaack** [comment]
修好了吗?感觉还是挂的

**Comment by fengmk2** [comment]
已经恢复。
