### ISSUE TITLE
同步包的时候报错

### ISSUE THREAD

**Issue by MkAnHui** [cnpm/cnpmjs.org#1488]
同步的包名:metro-source-map，版本0.55.0
报错信息
[2019-07-17 15:39:03]     [metro-source-map:0] syncing, delay: 5505341587 ms, version: 0.54.1, dist: {"shasum":"e17bad53c11978197d3c05c9168d799c2e04dcc5","size":12993,"noattachment":false,"tarball":"https://registry.npm.taobao.org/metro-source-map/download/metro-source-map-0.54.1.tgz"}, no deps: false, publish on cnpm: false, dependencies: 3, devDependencies: 0, syncDevDependencies: false
[2019-07-17 15:39:03]     add dependencies: @babel/traverse
[2019-07-17 15:39:03]     add dependencies: @babel/types
[2019-07-17 15:39:03]     add dependencies: source-map
[2019-07-17 15:39:03]     [metro-source-map:0] sync error, version: 0.54.1, SequelizeDatabaseError: SequelizeDatabaseError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x9A\x87 S...' for column 'description' at row 1
    at Query.formatError (/home/deploy/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/home/deploy/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/home/deploy/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (/home/deploy/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/home/deploy/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/deploy/cnpmjs.org/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/deploy/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket. (/home/deploy/cnpmjs.org/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:608:20)

**Comment by fengmk2** [comment]
[2019-07-17 15:39:03] [metro-source-map:0] sync error, version: 0.54.1, SequelizeDatabaseError: SequelizeDatabaseError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x9A\x87 S...' for column 'description' at row 1

description 字段需要改成 utf8mb4 编码。
