### ISSUE TITLE
同步资源时报错 sync error: TypeError: Cannot read property 'find' of null

### ISSUE THREAD

**Issue by ymuzi** [cnpm/cnpmjs.org#1496]
[2019-08-20 10:49:41] ----------------- Synced upstream https://registry.npm.taobao.org/react/sync/log/14332098 -------------------
[2019-08-20 10:49:41] ----------------- Syncing react -------------------
[2019-08-20 10:49:41] [c#0] [react] package(https://registry.npm.taobao.org/react?sync_timestamp=1566298181184) status: 200, dist-tags: {"alpha":"16.9.0-alpha.0","canary":"0.0.0-8d5403877","latest":"16.9.0","next":"16.9.0","unstable":"0.0.0-0c756fb-f7f79fd"}, time.modified: 2019-08-09T02:31:05.000Z, unpublished: null, start...
[2019-08-20 10:49:41]   [react] found 783 missing star users
[2019-08-20 10:49:41]   [react] all versions are exists
[2019-08-20 10:49:41]   [react] no versions need to deleted
[2019-08-20 10:49:41] [c#0] [error] [react] sync error: TypeError: Cannot read property 'find' of null
    at Object.exports.savePackageReadme (/home/xngdev/cnpmjs.org/services/package.js:490:41)
    at exports.savePackageReadme.next ()
    at onFulfilled (/home/xngdev/cnpmjs.org/node_modules/co/index.js:65:19)
    at /home/xngdev/cnpmjs.org/node_modules/co/index.js:54:5
    at new Promise ()
    at co (/home/xngdev/cnpmjs.org/node_modules/co/index.js:50:10)
    at toPromise (/home/xngdev/cnpmjs.org/node_modules/co/index.js:118:63)
    at next (/home/xngdev/cnpmjs.org/node_modules/co/index.js:99:29)
    at onFulfilled (/home/xngdev/cnpmjs.org/node_modules/co/index.js:69:7)
[2019-08-20 10:49:41] ----------------- Synced react fail -------------------
[2019-08-20 10:49:41] [done] Sync react package finished, 0 success, 1 fail
Success: [  ]
Fail: [ react ]
Sync react complete!

---------
cnpmjs.org version: 3.0.0-rc.27
Node.js version: v10.16.3

**Comment by ydmap** [comment]
same here.

**Comment by ydmap** [comment]
维护者对issuse, pr的处理似乎不太积极，2016年的都还open着好多...

**Comment by alsotang** [comment]
还算积极了。这么多年坚持下来了。

需要大家共建。

**Comment by fengmk2** [comment]
services/package.js:490:41 直接看代码就能修复。欢迎提交 pr。

**Comment by ymuzi** [comment]
> services/package.js:490:41 直接看代码就能修复。欢迎提交 pr。
这句话是说，你已经通过看代码修复了，但你希望其他同学提交pr，是这样么？还是说，这么小的问题不值得提issue ？

**Comment by fengmk2** [comment]
@ymuzi 淘宝 npm 上并没有这个错误，所以我并不认为它是我现在需要去修复的 bug。如果你的环境可以稳定复现，那么我觉得你来修复是更加合理的。

开源项目不是免费的劳动力。

**Comment by ymuzi** [comment]
@fengmk2  你不能复现就不能复现，你又把谁当免费劳动力呢，你也知道开源是共建的，何必展示你的优越感

**Comment by fengmk2** [comment]
@ymuzi 无言以对，祝好吧。

**Comment by atian25** [comment]
@ymuzi 那请问你对开源社区有任何的回馈了吗？
