### ISSUE TITLE
electron 7.0.0 安装出错

### ISSUE THREAD

**Issue by cjahv** [cnpm/cnpmjs.org#1519]
这是安装6.1.0到日志
```
> electron@6.1.0 postinstall /Users/jahv/Documents/Projects/ole/node_modules/electron
> node install.js

https://npm.taobao.org/mirrors/electron/6.1.0/electron-v6.1.0-darwin-x64.zip
Downloading tmp-63302-0-electron-v6.1.0-darwin-x64.zip
```

这是7.0.0的日志
```
> electron@7.0.0 postinstall /Users/jahv/Documents/Projects/ole/node_modules/electron
> node install.js

  @electron/get:index Downloading https://npm.taobao.org/mirrors/electron/v7.0.0/electron-v7.0.0-darwin-x64.zip to /var/folders/_d/yt4ztykn79ngfzgnw_685q9h0000gn/T/electron-download-sZJr7G/electron-v7.0.0-darwin-x64.zip with options: undefined +0ms
(node:63357) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.emitter.on.response (/Users/jahv/Documents/Projects/ole/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:198:13)
    at module.exports (/Users/jahv/Documents/Projects/ole/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/jahv/Documents/Projects/ole/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:203:15)
    at ClientRequest.origin.emit.args [as emit] (/Users/jahv/Documents/Projects/ole/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
(node:63357) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

看上去是因为v7.0.0导致的

**Comment by cjahv** [comment]
.npmrc添加`electron_custom_dir=7.0.0`可以临时解决

**Comment by cjahv** [comment]
https://github.com/electron/electron-packager/issues/1050

**Comment by cjahv** [comment]
使用新的镜像地址
```
electron_mirror=https://cdn.npm.taobao.org/dist/electron/
```
