### ISSUE TITLE
使用docker-compose，publish成功，install时404

### ISSUE THREAD

**Issue by wbget** [cnpm/cnpmjs.org#1565]
registryHost俩个配置文件我都改了地址。
```
test cnpm publish
npm notice
npm notice 📦  wb2@1.0.0
npm notice === Tarball Contents ===
npm notice 21B  index.js
npm notice 199B package.json
npm notice === Tarball Details ===
npm notice name:          wb2
npm notice version:       1.0.0
npm notice package size:  286 B
npm notice unpacked size: 220 B
npm notice shasum:        8da841ede8aebe1069dc122e5be6267987ba8a04
npm notice integrity:     sha512-nPKi6SLK3Z+lZ[...]h0J65aCUI5QSQ==
npm notice total files:   2
npm notice
```

失败
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/webb/code/nvm/versions/node/v10.15.1/bin/node',
1 verbose cli   '/Users/webb/code/nvm/versions/node/v10.15.1/bin/npm',
1 verbose cli   'i',
1 verbose cli   'wb2' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose npm-session b363a3f6d7fe3047
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 http://r.npm.maaee.com/wb2 4203ms
8 silly fetchPackageMetaData error for wb2@latest 404 Not Found: wb2@latest
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 4504ms
11 verbose stack Error: 404 Not Found: wb2@latest
11 verbose stack     at fetch.then.res (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
11 verbose stack     at tryCatcher (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
11 verbose stack     at Promise._settlePromise (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Async._drainQueue (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
11 verbose stack     at Async._drainQueues (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at runCallback (timers.js:705:18)
11 verbose stack     at tryOnImmediate (timers.js:676:5)
11 verbose stack     at processImmediate (timers.js:658:5)
12 verbose cwd /Users/webb/project/test1
13 verbose Darwin 17.7.0
14 verbose argv "/Users/webb/code/nvm/versions/node/v10.15.1/bin/node" "/Users/webb/code/nvm/versions/node/v10.15.1/bin/npm" "i" "wb2"
15 verbose node v10.15.1
16 verbose npm  v6.4.1
17 error code E404
18 error 404 Not Found: wb2@latest
19 verbose exit [ 1, true ]

```

**Comment by wbget** [comment]
```
npm notice
npm notice 📦  @maaee/wb2@1.0.0
npm notice === Tarball Contents ===
npm notice 21B  index.js
npm notice 206B package.json
npm notice === Tarball Details ===
npm notice name:          @maaee/wb2
npm notice version:       1.0.0
npm notice package size:  292 B
npm notice unpacked size: 227 B
npm notice shasum:        86e351897c159ebecdb8ebe8f39b4cc9e2a79462
npm notice integrity:     sha512-DPQa1jUMAb344[...]5G7vLigFJUXsQ==
npm notice total files:   2
npm notice
+ @maaee/wb2@1.0.0
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/webb/code/nvm/versions/node/v10.15.1/bin/node',
1 verbose cli   '/Users/webb/code/nvm/versions/node/v10.15.1/bin/npm',
1 verbose cli   'i',
1 verbose cli   '@maaee/wb2' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose npm-session 04f5a6bb80b0a2be
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 http://r.npm.maaee.com/@maaee%2fwb2 4143ms
8 silly fetchPackageMetaData error for @maaee/wb2@latest 404 Not Found: @maaee/wb2@latest
9 timing stage:rollbackFailedOptional Completed in 2ms
10 timing stage:runTopLevelLifecycles Completed in 4506ms
11 verbose stack Error: 404 Not Found: @maaee/wb2@latest
11 verbose stack     at fetch.then.res (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
11 verbose stack     at tryCatcher (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
11 verbose stack     at Promise._settlePromise (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Async._drainQueue (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
11 verbose stack     at Async._drainQueues (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Users/webb/code/nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at runCallback (timers.js:705:18)
11 verbose stack     at tryOnImmediate (timers.js:676:5)
11 verbose stack     at processImmediate (timers.js:658:5)
12 verbose cwd /Users/webb/project/test1
13 verbose Darwin 17.7.0
14 verbose argv "/Users/webb/code/nvm/versions/node/v10.15.1/bin/node" "/Users/webb/code/nvm/versions/node/v10.15.1/bin/npm" "i" "@maaee/wb2"
15 verbose node v10.15.1
16 verbose npm  v6.4.1
17 error code E404
18 error 404 Not Found: @maaee/wb2@latest
19 verbose exit [ 1, true ]

```

**Comment by wbget** [comment]
docker里文件是存在的，就是访问不到～

**Comment by wbget** [comment]
配置scope就可以了
