### ISSUE TITLE
安装报错Error: Cannot find module 'node:util'

### ISSUE THREAD

**Issue by Tigerioo** [cnpm/cnpmjs.org#1751]
操作系统是MacOS Ventura 13.3
本地node版本是8.5.0
安装`npm install -g cnpm --registry=https://registry.npmmirror.com`
执行`cnpm --version`报错如下：
```
module.js:529
    throw err;
    ^

Error: Cannot find module 'node:util'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/cnpm/bin/cnpm:3:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by fengmk2** [comment]
node 版本请升级到最新的 v16 版本或以上。
