### ISSUE TITLE
TypeError: code must be a number or string

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#319]
```
TypeError: code must be a number or string
    at status (/home/mk2/git/cnpmjs.org/node_modules/koa/node_modules/statuses/index.js:46:11)
    at Object.status (/home/mk2/git/cnpmjs.org/node_modules/koa/lib/response.js:75:41)
    at Object.status (/home/mk2/git/cnpmjs.org/node_modules/koa/node_modules/delegates/index.js:91:31)
    at Object.exports.show (/home/mk2/git/cnpmjs.org/controllers/registry/module.js:85:17)
    at GeneratorFunctionPrototype.next (native)
    at Object.syncByInstall (/home/mk2/git/cnpmjs.org/middleware/sync_by_install.js:39:10)
    at GeneratorFunctionPrototype.next (native)
    at Object.<anonymous> (/home/mk2/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-router/node_modules/koa-compose/index.js:37:12)
    at GeneratorFunctionPrototype.next (native)
    at Object.next (/home/mk2/git/cnpmjs.org/node_modules/co/index.js:77:21)
```

**Comment by mgenev** [comment]
getting this currently with the latest koa
