### ISSUE TITLE
node服务不稳定, cnpm安装依赖时较频繁发生

### ISSUE THREAD

**Issue by Arthurgyh** [cnpm/cnpmjs.org#547]
使用node v0.11.9 及 v0.11.14 均出现
```javascript
Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:142:15)
    at IncomingMessage.Readable.push (_stream_readable.js:123:10)
    at HTTPParser.parserOnBody (_http_common.js:132:22)
    at Socket.socketOnData (_http_client.js:272:20)
    at Socket.EventEmitter.emit (events.js:98:17)
    at readableAddChunk (_stream_readable.js:156:16)
    at Socket.Readable.push (_stream_readable.js:123:10)
    at TCP.onread (net.js:509:20)
[ERROR] 12:58:01 Error


make启动的两个node进程将挂掉一个, 不再对外提供服务. 需要kill掉重启

是否有相关的keepalive脚本等可借鉴? 谢谢

**Comment by fengmk2** [comment]
这是什么问题呢？看不懂
