### ISSUE TITLE
remarkable error: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#551]
```log
2015-01-02 14:53:13.933 nodejs.TypeErrorException: TypeError: undefined is not a function
    at ParserBlock.parse (/home/mk2/git/cnpmjs.org/node_modules/remarkable/lib/parser_block.js:99:13)
    at Array.block (/home/mk2/git/cnpmjs.org/node_modules/remarkable/lib/rules_core/block.js:15:17)
    at Core.process (/home/mk2/git/cnpmjs.org/node_modules/remarkable/lib/parser_core.js:39:13)
    at Remarkable.parse (/home/mk2/git/cnpmjs.org/node_modules/remarkable/lib/index.js:103:13)
    at Remarkable.render (/home/mk2/git/cnpmjs.org/node_modules/remarkable/lib/index.js:113:36)
    at exports.render (/home/mk2/git/cnpmjs.org/common/markdown.js:25:13)
    at Object.show (/home/mk2/git/cnpmjs.org/controllers/web/package/show.js:93:16)
    at GeneratorFunctionPrototype.next (native)
    at Object.dispatch (/home/mk2/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-router/lib/router.js:89:44)
    at GeneratorFunctionPrototype.next (native)
    at Object.markdown (/home/mk2/git/cnpmjs.org/node_modules/koa-markdown/index.js:67:21)
    at GeneratorFunctionPrototype.next (native)
    at Object.etag (/home/mk2/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-etag/index.js:25:12)
pid: 14636
domainThrown: false
Host: AY140413234123710ce7Z
URL: /package/mysql-prettify
Data: ""
2015-01-02 14:53:13.933
```

**Comment by fengmk2** [comment]
http://registry.npmjs.org/mysql-prettify readme is not String ....
