### ISSUE TITLE
master uncaughtException: Error: channel closed

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#565]
```
[Thu Jan 15 2015 02:35:54 GMT-0500 (EST)] [worker:30053] Server started, registry server listen at 127.0.0.1:7001, web listen at 127.0.0.1:7002, cluster: true
{ [Error: request entity too large]
  message: 'request entity too large',
  type: 'entity.too.large',
  statusCode: 413,
  status: 413,
  expected: 11885180,
  length: 11885180,
  limit: 10485760 }
Error
    at makeError (/home/www/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-bodyparser/node_modules/co-body/node_modules/raw-body/index.js:142:15)
    at /home/www/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-bodyparser/node_modules/co-body/node_modules/raw-body/index.js:38:17
    at process._tickCallback (node.js:372:11)
[Thu Jan 15 2015 05:31:38 GMT-0500 (EST)] [master:30051] syncer exit: SyncerWorkerDiedError: syncer 30054 died (code: null, signal: SIGKILL, stdout: null, stderr: null)
[WARNNING] your config.js was too old, please @see https://github.com/cnpm/cnpmjs.org/wiki/Migrating-from-1.x-to-2.x
[Thu Jan 15 2015 05:31:40 GMT-0500 (EST)] [sync_worker:1630] syncing with all mode
[Thu Jan 15 2015 11:36:44 GMT-0500 (EST)] [master:30051] syncer exit: SyncerWorkerDiedError: syncer 1630 died (code: null, signal: SIGKILL, stdout: null, stderr: null)
[WARNNING] your config.js was too old, please @see https://github.com/cnpm/cnpmjs.org/wiki/Migrating-from-1.x-to-2.x
[Thu Jan 15 2015 11:36:46 GMT-0500 (EST)] [sync_worker:7996] syncing with all mode
[Fri Jan 16 2015 00:37:06 GMT-0500 (EST)] [cfork:master:30051] master uncaughtException: AssertionError: Resource leak detected.
    at removeWorker (cluster.js:328:9)
    at ChildProcess.<anonymous> (cluster.js:348:34)
    at ChildProcess.g (events.js:199:16)
    at ChildProcess.emit (events.js:118:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
{ [AssertionError: Resource leak detected.]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'Resource leak detected.',
  generatedMessage: false }
(total 0 disconnect, 0 unexpected exit)
[Fri Jan 16 2015 00:37:11 GMT-0500 (EST)] [cfork:master:30051] master uncaughtException: Error: channel closed
    at ChildProcess.target.send (child_process.js:413:26)
    at sendHelper (cluster.js:657:8)
    at RoundRobinHandle.handoff (cluster.js:198:3)
    at RoundRobinHandle.distribute (cluster.js:184:20)
[Error: channel closed]
(total 0 disconnect, 0 unexpected exit)
```

**Comment by fengmk2** [comment]
内存不足，需要 mirrors 合并部署了

**Comment by dead-horse** [comment]
。。。
