### ISSUE TITLE
安装 selenium 模块失败

### ISSUE THREAD

**Issue by whuhacker** [cnpm/cnpmjs.org#566]
`$ cnpm install -g webhook-deployer`

```
> keygrip@0.2.4 install /usr/lib/node_modules/webhook-deployer/node_modules/keygrip
> [ -x /usr/bin/nodejs ] && /usr/bin/nodejs ./install.js || node ./install.js

 
> ws@0.5.0 install /usr/lib/node_modules/webhook-deployer/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/lib/node_modules/webhook-deployer/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/usr/lib/node_modules/webhook-deployer/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
 
> selenium-standalone@2.44.0 install /usr/lib/node_modules/webhook-deployer/node_modules/selenium-standalone
> node install.js

Installation finished

Error: Could not download http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
    at getDownloadStream (/usr/lib/node_modules/webhook-deployer/node_modules/selenium-standalone/install.js:156:36)
    at installSelenium (/usr/lib/node_modules/webhook-deployer/node_modules/selenium-standalone/install.js:51:3)
    at /usr/lib/node_modules/webhook-deployer/node_modules/selenium-standalone/node_modules/async/lib/async.js:570:21
    at /usr/lib/node_modules/webhook-deployer/node_modules/selenium-standalone/node_modules/async/lib/async.js:249:17
    at /usr/lib/node_modules/webhook-deployer/node_modules/selenium-standalone/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/usr/lib/node_modules/webhook-deployer/node_modules/selenium-standalone/node_modules/async/lib/async.js:46:24)
    at async.each (/usr/lib/node_modules/webhook-deployer/node_modules/selenium-standalone/node_modules/async/lib/async.js:124:9)
    at _asyncMap (/usr/lib/node_modules/webhook-deployer/node_modules/selenium-standalone/node_modules/async/lib/async.js:248:13)
    at Object.map (/usr/lib/node_modules/webhook-deployer/node_modules/selenium-standalone/node_modules/async/lib/async.js:219:23)
```

这个模块会自己去 http://selenium-release.storage.googleapis.com 下载驱动，which is 被墙掉的地址……好无奈啊

有解决办法吗？

**Comment by fengmk2** [comment]
请再等等，今天抽空将这个镜像了

**Comment by fengmk2** [comment]
@whuhacker fix here https://github.com/vvo/selenium-standalone/pull/61

**Comment by whuhacker** [comment]
Thanks

**Comment by fengmk2** [comment]
@whuhacker 通过baseurl参数 https://github.com/vvo/selenium-standalone/blob/master/HISTORY.md#320-2015-01-23

**Comment by whuhacker** [comment]
Perfect
