### ISSUE TITLE
使用 sqlite3，getDownloadTotal 出 SequelizeBaseError 错误

### ISSUE THREAD

**Issue by undoZen** [cnpm/cnpmjs.org#571]
貌似是 downloadTotalService 里面用了 sequelize 不支持的 date 格式？

必要的话我可以交出我们的 db 文件帮你们 debug

**Comment by undoZen** [comment]
package 页面、首页下载量统计的 ajax 请求会触发错误

```
SequelizeBaseError
    at module.exports.Query.formatError (/home/node/ccnpm/node_modules/cnpmjs.org/node_modules/sequelize/lib/dialects/sqlite/query.js:243:16)
    at /home/node/ccnpm/node_modules/cnpmjs.org/node_modules/sequelize/lib/dialects/sqlite/query.js:53:31
    at replacement (/home/node/ccnpm/node_modules/sqlite3/lib/trace.js:20:31)
    at Statement.errBack (/home/node/ccnpm/node_modules/sqlite3/lib/sqlite3.js:16:21)
```

最新 rc9 版本

**Comment by fengmk2** [comment]
我本地无法复现，能否提供一下 node 版本

**Comment by undoZen** [comment]
node: v0.11.15
sqlite3: 3.0.4
sequelize: 2.0.0-rc8

**Comment by fengmk2** [comment]
node试试0.11.14

**Comment by uzcc** [comment]
刚查了一下，之前说错，node 是 0.11.14 的
```bash
node@NODE:~/ccnpm$ ps aux |grep ccnpm
node     14268  0.0  1.5 1040896 128252 ?      Sl   Jan28   1:03 /home/node/.nvm/v0.11.14/bin/node --debug-port=5859 --harmony /home/node/ccnpm/worker.js
node     14269  0.0  1.5 1037876 126940 ?      Sl   Jan28   1:03 /home/node/.nvm/v0.11.14/bin/node --debug-port=5860 --harmony /home/node/ccnpm/worker.js
node     14270  0.0  1.6 1041884 131248 ?      Sl   Jan28   1:04 /home/node/.nvm/v0.11.14/bin/node --debug-port=5861 --harmony /home/node/ccnpm/worker.js
node     14275  0.0  1.5 1035784 124440 ?      Sl   Jan28   1:03 /home/node/.nvm/v0.11.14/bin/node --debug-port=5862 --harmony /home/node/ccnpm/worker.js
node     21500  0.0  0.0   8068   652 pts/1    R+   16:16   0:00 grep --color=auto ccnpm
node@NODE:~/ccnpm$
```

**Comment by fengmk2** [comment]
能否将 SequelizeBaseError 一次打印处理 console.log(err) ，我看看具体哪个 sql 出错了

**Comment by fengmk2** [comment]
能打印一下 err 么？
