### ISSUE TITLE
passing raw query replacements as the 4th argument to sequelize.query is deprecated. Please use options.replacements instead

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#597]

**Comment by fengmk2** [comment]
```
TypeError: Cannot read property '0' of undefined
    at /Users/mk2/git/cnpmjs.org/services/package.js:177:23
    at Array.filter (native)
    at Object.exports.listPublicModuleNamesByUser (/Users/mk2/git/cnpmjs.org/services/package.js:176:6)
    at GeneratorFunctionPrototype.next (native)
    at onFulfilled (/Users/mk2/git/cnpmjs.org/node_modules/co/index.js:59:19)
    at tryCatch1 (/Users/mk2/git/cnpmjs.org/node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/Users/mk2/git/cnpmjs.org/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/Users/mk2/git/cnpmjs.org/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/Users/mk2/git/cnpmjs.org/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:713:18)
    at Promise._settlePromiseAt (/Users/mk2/git/cnpmjs.org/node_modules/sequelize/lib/promise.js:76:18)
    at Promise._settlePromises (/Users/mk2/git/cnpmjs.org/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:854:14)
    at Async._consumeFunctionBuffer (/Users/mk2/git/cnpmjs.org/node_modules/sequelize/node_modules/bluebird/js/main/async.js:85:12)
    at Async.consumeFunctionBuffer (/Users/mk2/git/cnpmjs.org/node_modules/sequelize/node_modules/bluebird/js/main/async.js:40:14)
    at process._tickCallback (node.js:337:11)

```
