### ISSUE TITLE
curl localhost:7002/package/chewer markdown parse 100% cpu

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#598]
eat too much cpu 

![image](https://cloud.githubusercontent.com/assets/156269/6160814/ca94bf6e-b2a2-11e4-8118-412aa1c2ac3d.png)

```
{ [Error: request entity too large]
  message: 'request entity too large',
  type: 'entity.too.large',
  statusCode: 413,
  status: 413,
  expected: 11885181,
  length: 11885181,
  limit: 10485760 }
Error: request entity too large
    at makeError (/home/www/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-bodyparser/node_modules/co-body/node_modules/raw-body/index.js:142:15)
    at /home/www/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-bodyparser/node_modules/co-body/node_modules/raw-body/index.js:38:17
    at process._tickCallback (node.js:337:11)
{ [Error: request entity too large]
  message: 'request entity too large',
  type: 'entity.too.large',
  statusCode: 413,
  status: 413,
  expected: 11885191,
  length: 11885191,
  limit: 10485760 }
Error: request entity too large
    at makeError (/home/www/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-bodyparser/node_modules/co-body/node_modules/raw-body/index.js:142:15)
    at /home/www/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-bodyparser/node_modules/co-body/node_modules/raw-body/index.js:38:17
    at process._tickCallback (node.js:337:11)
{ [Error: request entity too large]
  message: 'request entity too large',
  type: 'entity.too.large',
  statusCode: 413,
  status: 413,
  expected: 11347587,
  length: 11347587,
  limit: 10485760 }
Error: request entity too large
    at makeError (/home/www/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-bodyparser/node_modules/co-body/node_modules/raw-body/index.js:142:15)
    at /home/www/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-bodyparser/node_modules/co-body/node_modules/raw-body/index.js:38:17
    at process._tickCallback (node.js:337:11)
{ [Error: request entity too large]
  message: 'request entity too large',
  type: 'entity.too.large',
  statusCode: 413,
  status: 413,
  expected: 11347587,
  length: 11347587,
  limit: 10485760 }
Error: request entity too large
    at makeError (/home/www/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-bodyparser/node_modules/co-body/node_modules/raw-body/index.js:142:15)
    at /home/www/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-bodyparser/node_modules/co-body/node_modules/raw-body/index.js:38:17
    at process._tickCallback (node.js:337:11)
events.js:75
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:738:11)
    at TCP.onread (net.js:530:26)
[Wed Feb 11 2015 13:37:27 GMT-0500 (EST)] [master:27848] syncer exit: SyncerWorkerDiedError: syncer 27859 died (code: 1, signal: null, stdout: null, stderr: null)
[WARNNING] your config.js was too old, please @see https://github.com/cnpm/cnpmjs.org/wiki/Migrating-from-1.x-to-2.x
[Wed Feb 11 2015 13:37:29 GMT-0500 (EST)] [sync_worker:31854] syncing with all mode
```

**Comment by fengmk2** [comment]
curl localhost:7002/package/chewer
