### ISSUE TITLE
sync worker die

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#599]
```
events.js:75
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:738:11)
    at TCP.onread (net.js:530:26)
[Wed Feb 11 2015 13:37:27 GMT-0500 (EST)] [master:27848] syncer exit: SyncerWorkerDiedError: syncer 27859 died (code: 1, signal: null, stdout: null, stderr: null)
[WARNNING] your config.js was too old, please @see https://github.com/cnpm/cnpmjs.org/wiki/Migrating-from-1.x-to-2.x
[Wed Feb 11 2015 13:37:29 GMT-0500 (EST)] [sync_worker:31854] syncing with all mode
```

**Comment by fengmk2** [comment]
怀疑跟 smtp 有关 https://github.com/andris9/nodemailer-smtp-transport/blob/master/src/smtp-transport.js#L58

**Comment by fengmk2** [comment]
https://github.com/node-modules/agentkeepalive/pull/30
