### ISSUE TITLE
Respository AND Web not working

### ISSUE THREAD

**Issue by jarrodconnolly** [cnpm/cnpmjs.org#606]
I have tried to test out a deployment of CNPM using the simple instructions in the "Deploy a private npm registry in 5 minutes" document.

Everything seems to install and build correctly from npm.

I can start the service using the "cnpmjs.org start" command.

When I try to use either the registry from npm or visit the website it always responds with: "Internal Server Error"

The following stack trace is in the logs.

{ [ReferenceError: dispatch is not defined] url: '/' }
ReferenceError: dispatch is not defined
    at Object.dispatch (/usr/local/lib/node_modules/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-router/lib/router.js:166:8)
    at Object.callee$1$0$ (/usr/local/lib/node_modules/cnpmjs.org/node_modules/koa/node_modules/koa-compose/index.js:31:20)
    at tryCatch (/usr/local/lib/node_modules/cnpmjs.org/node_modules/gnode/node_modules/regenerator/runtime.js:53:40)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/cnpmjs.org/node_modules/gnode/node_modules/regenerator/runtime.js:209:22)
    at onFulfilled (/usr/local/lib/node_modules/cnpmjs.org/node_modules/co/index.js:59:19)
    at /usr/local/lib/node_modules/cnpmjs.org/node_modules/co/index.js:48:5
    at tryCatcher (/usr/local/lib/node_modules/cnpmjs.org/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/usr/local/lib/node_modules/cnpmjs.org/node_modules/bluebird/js/main/promise.js:427:31)
    at new Promise (/usr/local/lib/node_modules/cnpmjs.org/node_modules/bluebird/js/main/promise.js:53:37)
    at Object.co (/usr/local/lib/node_modules/cnpmjs.org/node_modules/co/index.js:47:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/cnpmjs.org/node_modules/co/index.js:28:15)
    at Server.<anonymous> (/usr/local/lib/node_modules/cnpmjs.org/node_modules/koa/lib/application.js:124:8)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming](_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)

**Comment by fengmk2** [comment]
can you show me the version of `/usr/local/lib/node_modules/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-router` ?

```
cat /usr/local/lib/node_modules/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-router/package.json |grep version
```

**Comment by fengmk2** [comment]
and what's version of node you're using?

**Comment by jarrodconnolly** [comment]
[~]$ cat /usr/local/lib/node_modules/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-router/package.json |grep version
  "version": "3.8.0",

[~]$ node --version                                                                                                    
v0.12.0

**Comment by jarrodconnolly** [comment]
I have tried installing on both Ubuntu 14.04 and OSX with the same results.

**Comment by jarrodconnolly** [comment]
@fengmk2 
Any thoughts on what may be going on here or anything else I could try?
