### ISSUE TITLE
windows上安装私有npm库失败

### ISSUE THREAD

**Issue by luqin** [cnpm/cnpmjs.org#612]
按照Deploy a private npm registry in 5 minutes教程，在windows上无法安装，请问该怎么才能安装？
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink D:\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart cnpmjs.org@2.0.0-rc.15
7 info start cnpmjs.org@2.0.0-rc.15
8 verbose unsafe-perm in lifecycle true
9 info cnpmjs.org@2.0.0-rc.15 Failed to exec start script
10 verbose stack Error: cnpmjs.org@2.0.0-rc.15 start: `./bin/nodejsctl start && cp History.md docs/web/history.md`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (D:\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (D:\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid cnpmjs.org@2.0.0-rc.15
12 verbose cwd E:\WebstormProjects\cnpmjs.org
13 error Windows_NT 6.3.9600
14 error argv "D:\\nodejs\\\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
15 error node v0.12.2
16 error npm  v2.7.4
17 error code ELIFECYCLE
18 error cnpmjs.org@2.0.0-rc.15 start: `./bin/nodejsctl start && cp History.md docs/web/history.md`
18 error Exit status 1
19 error Failed at the cnpmjs.org@2.0.0-rc.15 start script './bin/nodejsctl start && cp History.md docs/web/history.md'.
19 error This is most likely a problem with the cnpmjs.org package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     ./bin/nodejsctl start && cp History.md docs/web/history.md
19 error You can get their info via:
19 error     npm owner ls cnpmjs.org
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by luqin** [comment]
已经安装成功
