### ISSUE TITLE
使用"Deploy a private npm registry in 5 minutes"不能部署成功

### ISSUE THREAD

**Issue by ilife5** [cnpm/cnpmjs.org#616]
系统：osx

按照上述文章的部署方法，不能部署成功，访问web页面报如下错误：

```
sudo cnpmjs.org start
Starting cnpmjs.org ...
cluster: false
admins: {"fengmk2":"fengmk2@gmail.com","admin":"admin@cnpmjs.org","dead_horse":"dead_horse@qq.com"}
scopes: ["@cnpm","@cnpmtest"]
sourceNpmRegistry: http://registry.npm.taobao.org
syncModel: none
[Tue May 05 2015 12:06:08 GMT+0800 (CST)] [worker:1991] Server started, registry server listen at 127.0.0.1:7001, web listen at 127.0.0.1:7002, cluster: false
[models/init_script.js] `sqlite` sequelize sync and init success
{ [ReferenceError: dispatch is not defined] url: '/' }
ReferenceError: dispatch is not defined
    at Object.dispatch (/usr/local/lib/node_modules/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-router/lib/router.js:166:8)
    at Object.callee$1$0$ (/usr/local/lib/node_modules/cnpmjs.org/node_modules/koa/node_modules/koa-compose/index.js:31:20)
    at tryCatch (/usr/local/lib/node_modules/cnpmjs.org/node_modules/gnode/node_modules/regenerator/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/cnpmjs.org/node_modules/gnode/node_modules/regenerator/runtime.js:234:22)
    at GeneratorFunctionPrototype.Gp.(anonymous function) [as next] (/usr/local/lib/node_modules/cnpmjs.org/node_modules/gnode/node_modules/regenerator/runtime.js:270:19)
    at onFulfilled (/usr/local/lib/node_modules/cnpmjs.org/node_modules/co/index.js:59:19)
    at /usr/local/lib/node_modules/cnpmjs.org/node_modules/co/index.js:48:5
    at tryCatcher (/usr/local/lib/node_modules/cnpmjs.org/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/usr/local/lib/node_modules/cnpmjs.org/node_modules/bluebird/js/main/promise.js:427:31)
    at new Promise (/usr/local/lib/node_modules/cnpmjs.org/node_modules/bluebird/js/main/promise.js:53:37)
    at Object.co (/usr/local/lib/node_modules/cnpmjs.org/node_modules/co/index.js:47:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/cnpmjs.org/node_modules/co/index.js:28:15)
    at Server.<anonymous> (/usr/local/lib/node_modules/cnpmjs.org/node_modules/koa/lib/application.js:124:8)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
```

**Comment by fengmk2** [comment]
node 版本是多少？

**Comment by PengXing** [comment]
0.12.2

**Comment by PengXing** [comment]
需要通过--harmony启动

**Comment by ilife5** [comment]
node 0.12.2

**Comment by huangyingjie** [comment]
> 需要通过--harmony启动
这个是指什么？在 ~/.bashrc里面alias node='node harmony'可以吗？
我这么做，然后重新执行`nohup cnpmjs.org start .....` 仍然会报这个错。
node 0.12.7

**Comment by huangyingjie** [comment]
解决了，参考：
http://stackoverflow.com/questions/20980222/run-a-node-shell-script-in-harmony-mode
直接映射alias node='node --harmony'没用，因为cnpmjs.org这个脚本里面写了这句：`#!/usr/bin/env node`
