### ISSUE TITLE
download tarball failed (in npm 2.x scope)

### ISSUE THREAD

**Issue by oluul** [cnpm/cnpmjs.org#619]
问题1： download router 不支持 如下url:http://domain.com/@myco/tool/download/@myco/tool-1.0.2.tgz
上面的路径是因为用了npm scope，package.name = "@myco/tool" 
config.nfs =  fs-cnpm;

报错信息：nodejs.TypeErrorException: TypeError: Cannot read property 'slice' of undefined (/controllers/registry/package/download.js:35:25)

/controllers/registry/package/download.js 内输出 this.params为空对象

除了这块web的/package/xxxx 路径遇到scope 式的name时遇到错误。

问题2：如何自定义tarball url? 现在是 127.0.0.1:7001 。是否支持更换domain和port

因对koa,yield不太熟悉。所以求救。谢

**Comment by fengmk2** [comment]
能打印一下 this 吗？ 

```
console.log(this, this.header, this.url, this.params)
```

**Comment by oluul** [comment]
1：下面是os x下测试的。相同的配置，没有上述的不能下载问题了。上面的错误是在ubuntu上报的，我明天再检查下。
2：如何自定义tarball url? 现在是 127.0.0.1:7001 。是否支持更换domain和port

console.log(this) 返回：

{ request:
   { method: 'GET',
     url: '/@cnpmtest/tool/download/@cnpmtest/tool-1.0.0.tgz',
     header:
      { host: '127.0.0.1:7001',
        connection: 'keep-alive',
        accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36',
        'accept-encoding': 'gzip, deflate, sdch',
        'accept-language': 'en-US,en;q=0.8,ru;q=0.6,zh-CN;q=0.4,zh;q=0.2,mn;q=0.2',
        cookie: 'CNZZDATA5757157=cnzz_eid%3D558670701-1431442401-%26ntime%3D1431442401',
        'ra-ver': '2.10.3',
        'ra-sid': '7739B173-20140918-082441-38eb69-bef41f',
        'if-none-match': '"8972d999392820492ffef38ee7801b3bc2e6b6cf"' } },
  response: { status: 404, message: 'Not Found', header: {} },
  app: { subdomainOffset: 2, env: 'development' },
  originalUrl: '/@cnpmtest/tool/download/@cnpmtest/tool-1.0.0.tgz',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }

**Comment by oluul** [comment]
即 versions.XXX.dist.tarball 中的 127.0.0.1:7001能否替换？
``` javascript
{
  "_id": "@cnpmtest/tool",
  "_rev": "1",
  "name": "@cnpmtest/tool",
  "description": "",
  "dist-tags": {
    "latest": "1.0.0"
  },
  "maintainers": [{
    "name": "bold",
    "email": "bold@oluul.com"
  }],
  "time": {
    "modified": "2015-05-12T14:58:58.000Z",
    "created": "2015-05-12T14:58:58.120Z",
    "1.0.0": "2015-05-12T14:58:58.120Z"
  },
  "users": {},
  "author": "",
  "versions": {
    "1.0.0": {
      "name": "@cnpmtest/tool",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC",
      "_id": "@cnpmtest/tool@1.0.0",
      "_shasum": "8972d999392820492ffef38ee7801b3bc2e6b6cf",
      "_from": ".",
      "_npmVersion": "2.9.1",
      "_nodeVersion": "0.12.2",
      "_npmUser": {
        "name": "bold",
        "email": "bold@oluul.com"
      },
      "maintainers": [{
        "name": "bold",
        "email": "bold@oluul.com"
      }],
      "dist": {
        "shasum": "8972d999392820492ffef38ee7801b3bc2e6b6cf",
        "size": 301,
        "key": "/@cnpmtest/tool/-/@cnpmtest/tool-1.0.0.tgz",
        "tarball": "http://127.0.0.1:7001/@cnpmtest/tool/download/@cnpmtest/tool-1.0.0.tgz"
      },
      "_publish_on_cnpm": true,
      "_cnpm_publish_time": 1431442738120
    }
  },
  "readme": "ERROR: No README data found!",
  "_attachments": {},
  "license": "ISC"
}
```

**Comment by fengmk2** [comment]
可以的，估计是你的 nginx 转发配置漏了参数

**Comment by fengmk2** [comment]
看这里 https://github.com/cnpm/cnpmjs.org/issues/615#issuecomment-101300689

**Comment by oluul** [comment]
解决了。改完nginx，重启下cnpmjs.org才生效的。谢谢

**Comment by oluul** [comment]
``` javascript
2015-05-13 16:24:19.910 nodejs.TypeErrorException: TypeError: Cannot read property 'slice' of undefined
    at Object.download (/data/private-npm-server/controllers/registry/package/download.js:36:25)
    at GeneratorFunctionPrototype.next (native)
    at Object.ignoreLimit (/data/private-npm-server/middleware/limit.js:24:12)
    at GeneratorFunctionPrototype.next (native)
    at Object.<anonymous> (/data/private-npm-server/node_modules/koa-middlewares/node_modules/koa-router/node_modules/koa-compose/index.js:29:12)
    at GeneratorFunctionPrototype.next (native)
    at Object.dispatch (/data/private-npm-server/node_modules/koa-middlewares/node_modules/koa-router/lib/router.js:317:14)
    at GeneratorFunctionPrototype.next (native)
    at Object.allowedMethods (/data/private-npm-server/node_modules/koa-middlewares/node_modules/koa-router/lib/router.js:356:12)
    at GeneratorFunctionPrototype.next (native)
    at Object.etag (/data/private-npm-server/node_modules/koa-middlewares/node_modules/koa-etag/index.js:25:12)
    at GeneratorFunctionPrototype.next (native)
    at Object.<anonymous> (/data/private-npm-server/node_modules/koa-middlewares/node_modules/koa-conditional-get/index.js:16:12)
    at GeneratorFunctionPrototype.next (native)
    at Object.notFound (/data/private-npm-server/middleware/registry_not_found.js:18:10)
    at GeneratorFunctionPrototype.next (native)
pid: 20015
domainThrown: false
Host: ubuntu
URL: /@xx/ttf2eot/download/@xx/ttf2eot-1.3.1.tgz
Data: ""
2015-05-13 16:24:19.910
```

**Comment by oluul** [comment]
@fengmk2
