### ISSUE TITLE
本地仓库安装gulp-sass和webpack-dev-server失败，但是使用npm可以安装

### ISSUE THREAD

**Issue by luqin** [cnpm/cnpmjs.org#620]
本地仓库安装gulp-sass和webpack-dev-server失败，但是使用npm可以安装

**Comment by luqin** [comment]
gulp-sass是提示依赖node-sass下载失败，下载地址在github上

**Comment by oluul** [comment]
npm install 的时候加上 --verbose 可以查看安装详情，应该会有错误日志

**Comment by luqin** [comment]
错误信息如下，使用npm安装没问题
```
15517 info node-sass@3.0.0 Failed to exec postinstall script
15518 verbose unlock done using C:\Users\dell\AppData\Roaming\npm-cache\_locks\node-sass-657a5d781b7fe705.lock for E:\dev\test\websrc\node_modules\gulp-sass\node_modules\node-sass
15519 verbose about to build E:\dev\test\websrc\node_modules\gulp-sass
15520 verbose unlock done using C:\Users\dell\AppData\Roaming\npm-cache\_locks\gulp-sass-9ae60c318f878236.lock for E:\dev\test\websrc\node_modules\gulp-sass
15521 verbose stack Error: node-sass@3.0.0 postinstall: `node scripts/build.js`
15521 verbose stack Exit status 1
15521 verbose stack     at EventEmitter.<anonymous> (D:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
15521 verbose stack     at EventEmitter.emit (events.js:110:17)
15521 verbose stack     at ChildProcess.<anonymous> (D:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
15521 verbose stack     at ChildProcess.emit (events.js:110:17)
15521 verbose stack     at maybeClose (child_process.js:1008:16)
15521 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
15522 verbose pkgid node-sass@3.0.0
15523 verbose cwd E:\dev\test\websrc
15524 error Windows_NT 6.1.7601
15525 error argv "D:\\Program Files (x86)\\nodejs\\\\node.exe" "D:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-sass"
15526 error node v0.12.0
15527 error npm  v2.9.1
15528 error code ELIFECYCLE
15529 error node-sass@3.0.0 postinstall: `node scripts/build.js`
15529 error Exit status 1
15530 error Failed at the node-sass@3.0.0 postinstall script 'node scripts/build.js'.
15530 error This is most likely a problem with the node-sass package,
15530 error not with npm itself.
15530 error Tell the author that this fails on your system:
15530 error     node scripts/build.js
15530 error You can get their info via:
15530 error     npm owner ls node-sass
15530 error There is likely additional logging output above.
```

**Comment by luqin** [comment]
![cnpm error](https://cloud.githubusercontent.com/assets/2267688/7601988/cf2256aa-f950-11e4-9c2e-aeca342501ca.png)

**Comment by luqin** [comment]
```
285834 verbose unlock done using C:\Users\dell\.cnpm\_locks\node-sass-657a5d781b7fe705.lock for E:\dev\test\websrc\node_modules\gulp-sass\node_modules\node-sass
285835 verbose about to build E:\dev\test\websrc\node_modules\gulp-sass
285836 verbose unlock done using C:\Users\dell\.cnpm\_locks\gulp-sass-9ae60c318f878236.lock for E:\dev\test\websrc\node_modules\gulp-sass
285837 verbose stack Error: ws@0.5.0 install: `(node-gyp rebuild 2> builderror.log) || (exit 0)`
285837 verbose stack Exit status 255
285837 verbose stack     at EventEmitter.<anonymous> (D:\Program Files (x86)\nodejs\node_modules\cnpm\node_modules\npm\lib\utils\lifecycle.js:213:16)
285837 verbose stack     at EventEmitter.emit (events.js:110:17)
285837 verbose stack     at ChildProcess.<anonymous> (D:\Program Files (x86)\nodejs\node_modules\cnpm\node_modules\npm\lib\utils\spawn.js:14:12)
285837 verbose stack     at ChildProcess.emit (events.js:110:17)
285837 verbose stack     at maybeClose (child_process.js:1008:16)
285837 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
285838 verbose pkgid ws@0.5.0
285839 verbose cwd E:\dev\test\websrc
285840 error Windows_NT 6.1.7601
285841 error argv "node" "D:\\Program Files (x86)\\nodejs\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\dell\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=C:\\Users\\dell\\.cnpm" "--registry=http://ci.dev.its:7001/" "--node-gyp=D:\\Program Files (x86)\\nodejs\\node_modules\\cnpm\\node_modules\\pangyp\\bin\\node-gyp.js" "install"
285842 error node v0.12.0
285843 error npm  v2.7.6
285844 error code ELIFECYCLE
285845 error ws@0.5.0 install: `(node-gyp rebuild 2> builderror.log) || (exit 0)`
285845 error Exit status 255
285846 error Failed at the ws@0.5.0 install script '(node-gyp rebuild 2> builderror.log) || (exit 0)'.
285846 error This is most likely a problem with the ws package,
285846 error not with npm itself.
285846 error Tell the author that this fails on your system:
285846 error     (node-gyp rebuild 2> builderror.log) || (exit 0)
285846 error You can get their info via:
285846 error     npm owner ls ws
285846 error There is likely additional logging output above.
285847 verbose exit [ 1, true ]
```
