### ISSUE TITLE
Install sqlite without --build-from-source flag, sqlite cannot be found by sequelize.

### ISSUE THREAD

**Issue by themez** [cnpm/cnpmjs.org#639]
sqlite3 has an issue that cannot be installed from source using -g as root user.

But if I install sqlite without --build-from-source flag, sqlite cannot be found by sequelize.

```
Error: Please install sqlite3 package manually
    at new ConnectionManager (/nodejs/lib/node_modules/cnpmjs.org/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:21:11)
    at new SqliteDialect (/nodejs/lib/node_modules/cnpmjs.org/node_modules/sequelize/lib/dialects/sqlite/index.js:12:28)
    at new module.exports.Sequelize (/nodejs/lib/node_modules/cnpmjs.org/node_modules/sequelize/lib/sequelize.js:185:22)
    at Object.<anonymous> (/nodejs/lib/node_modules/cnpmjs.org/common/sequelize.js:73:17)
    at Module._compile (module.js:460:26)
    at Object.gnodeJsExtensionCompiler [as .js] (/nodejs/lib/node_modules/cnpmjs.org/node_modules/gnode/index.js:61:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
/nodejs/lib/node_modules/cnpmjs.org/node_modules/sequelize/lib/sequelize.js:188
      throw new Error('The dialect ' + this.getDialect() + ' is not supported.

```

**Comment by jmolboy** [comment]
I have the same problem.how to solve it?

**Comment by YardWill** [comment]
Update your node-gyp. I solved it in this way. Because of sqlite3 not being build,so npm cant find sqlite3.
