### ISSUE TITLE
搭建的私有源同步出现问题

### ISSUE THREAD

**Issue by ywang1724** [cnpm/cnpmjs.org#648]
页面显示如下：
Sync Status
This registry will only update exist packages from official registry.

Last sync time is Thu Aug 06 2015 04:17:37 GMT+0800 (CST).

The sync worker is working in the backend now.

4 packages need to be sync  12 packages and dependencies waiting for sync   850% progress
34 packages and dependencies sync successed 0 packages and dependencies sync failed last success: pm2-logs

显示上次同步时间还是很久之前的，同步配置基本是采用默认配置，出现上述情况的原因可能在哪？谢谢～

**Comment by fengmk2** [comment]
具体是什么问题呢？

**Comment by selboo** [comment]
默认配置 好像是  none   不同步只连接
修改config/index.js 下  syncModel: 'all'  自动同步
估计全部同步下来，需要 500G 硬盘  10G 数据库

**Comment by ywang1724** [comment]
@selboo 我的配置是syncModel: 'exist'

**Comment by ywang1724** [comment]
@fengmk2 没有按照每十分钟自动同步

**Comment by fengmk2** [comment]
@ywang1724 你可以看看 sync_info*.log

**Comment by galen2017** [comment]
[2017-08-14 12:32:46] user: anonymous, sync connect worker start, 1 concurrency, nodeps: false, publish: false
[2017-08-14 12:32:46] ----------------- Syncing upstream https://registry.npm.taobao.org/connect/sync/log/6047220 -------------------
[2017-08-14 12:32:46] [2017-08-14 20:32:46] user: anonymous, sync connect worker start, 1 concurrency, nodeps: false, publish: false
[2017-08-14 12:32:48] [2017-08-14 20:32:47] ----------------- Syncing upstream https://r.cnpmjs.org/connect/sync/log/4008451 -------------------
[2017-08-14 20:32:47] [2017-08-14 20:32:47] user: anonymous, sync connect worker start, 1 concurrency, nodeps: false, publish: false
[2017-08-14 20:32:47] ----------------- Syncing connect -------------------
[2017-08-14 12:32:50] [2017-08-14 20:32:49] [2017-08-14 20:32:47] [c#0] [connect] package(https://replicate.npmjs.com/connect) status: 200, dist-tags: {"1.8":"1.9.0","latest":"3.6.3"}, time.modified: 2017-08-10T16:36:42.879Z, unpublished: null, start...
[2017-08-14 20:32:47]   [connect] found 0 missing star users
[2017-08-14 20:32:47]   [connect] all versions are exists
[2017-08-14 20:32:47]   [connect] no versions need to deleted
[2017-08-14 20:32:47]   [connect] all 225 npm users exists
[2017-08-14 20:32:47] [c#0] [connect] synced success, 0 versions: 
[2017-08-14 20:32:47] ----------------- Synced connect success -------------------
[2017-08-14 20:32:47] ----------------- Syncing connect -------------------
[2017-08-14 20:32:47] [c#0] [connect] package(https://registry.npmjs.com/connect) status: 200, dist-tags: {"1.8":"1.9.0","latest":"3.6.3"}, time.modified: 2017-08-10T16:36:42.879Z, unpublished: null, start...
[2017-08-14 20:32:48]   [connect] found 0 missing star users
[2017-08-14 20:32:48]   [connect] all versions are exists
[2017-08-14 20:32:48]   [connect] no versions need to deleted
[2017-08-14 20:32:48]   [connect] all 225 npm users exists
[2017-08-14 20:32:48] [c#0] [connect] synced success, 0 versions: 
[2017-08-14 20:32:48] ----------------- Synced connect success -------------------
[2017-08-14 20:32:48] [Upstream done] Sync connect package finished, 2 success, 0 fail
Success: [ connect, connect ]
Fail: [  ]
[2017-08-14 20:32:49] ----------------- Synced upstream https://r.cnpmjs.org/connect/sync/log/4008451 -------------------
[2017-08-14 20:32:49] ----------------- Syncing connect -------------------
[2017-08-14 20:32:49] [c#0] [connect] package(https://r.cnpmjs.org/connect) status: 200, dist-tags: {"1.8":"1.9.0","latest":"3.6.3"}, time.modified: 2017-08-07T23:24:31.000Z, unpublished: null, start...
[2017-08-14 20:32:50]   [connect] found 0 missing star users
[2017-08-14 20:32:50]   [connect] all versions are exists
[2017-08-14 20:32:50]   [connect] no versions need to deleted
[2017-08-14 20:32:50]   [connect] all 236 npm users exists
[2017-08-14 20:32:50] [c#0] [connect] synced success, 0 versions: 
[2017-08-14 20:32:50] ----------------- Synced connect success -------------------
[2017-08-14 20:32:50] [Upstream done] Sync connect package finished, 1 success, 0 fail
Success: [ connect ]
Fail: [  ]
[2017-08-14 12:32:50] ----------------- Synced upstream https://registry.npm.taobao.org/connect/sync/log/6047220 -------------------
[2017-08-14 12:32:50] ----------------- Syncing connect -------------------
[2017-08-14 12:32:50] [c#0] [connect] package(https://registry.npm.taobao.org/connect) status: 200, dist-tags: {"1.8":"1.9.0","latest":"3.6.3"}, time.modified: 2017-08-07T23:24:33.000Z, unpublished: null, start...
[2017-08-14 12:32:50] [c#0] [error] [connect] sync error: TypeError: Cannot read property 'findAll' of null
    at Object.exports.listModuleAbbreviatedsByName (/cnpmjs.org/services/package.js:327:44)
    at next (native)
    at onFulfilled (/cnpmjs.org/node_modules/co/index.js:65:19)
    at /cnpmjs.org/node_modules/co/index.js:54:5
    at co (/cnpmjs.org/node_modules/co/index.js:50:10)
    at toPromise (/cnpmjs.org/node_modules/co/index.js:118:63)
    at Array.map (native)
    at arrayToPromise (/cnpmjs.org/node_modules/co/index.js:154:26)
    at toPromise (/cnpmjs.org/node_modules/co/index.js:120:49)
    at next (/cnpmjs.org/node_modules/co/index.js:99:29)
    at onFulfilled (/cnpmjs.org/node_modules/co/index.js:69:7)
    at /cnpmjs.org/node_modules/co/index.js:54:5
    at co (/cnpmjs.org/node_modules/co/index.js:50:10)
    at toPromise (/cnpmjs.org/node_modules/co/index.js:118:63)
    at next (/cnpmjs.org/node_modules/co/index.js:99:29)
    at onFulfilled (/cnpmjs.org/node_modules/co/index.js:69:7)
[2017-08-14 12:32:50] ----------------- Synced connect fail -------------------
[2017-08-14 12:32:50] [done] Sync connect package finished, 0 success, 1 fail
Success: [  ]
Fail: [ connect ]
Sync connect complete!

@fengmk2 你好，我这也是同样的问题
