### ISSUE TITLE
不支持iojs3.3么？

### ISSUE THREAD

**Issue by i5ting** [cnpm/cnpmjs.org#654]
```
[deploy@iZ25uttmhb1Z ~]$ npm install -g --build-from-source   --registry=http://registry.npm.taobao.org   --disturl=http://npm.taobao.org/mirrors/node   cnpmjs.org cnpm sqlite3
npm WARN deprecated sequelize@2.0.6: critical security fix in v3.0.0
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
npm WARN deprecated bignumber.js@2.0.0: critical bug fixed in v2.0.4
/home/deploy/.nvm/versions/io.js/v3.3.0/bin/cnpmjs.org -> /home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/cnpmjs.org/bin/cli.js
\
> sqlite3@3.0.10 install /home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading http://npm.taobao.org/mirrors/node/v3.3.0/node-v3.3.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/npm/node_modules/request/request.js:1008:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 3.10.0-123.9.3.el7.x86_64
gyp ERR! command "/home/deploy/.nvm/versions/io.js/v3.3.0/bin/iojs" "/home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/sqlite3/lib/binding/node-v45-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/sqlite3/lib/binding/node-v45-linux-x64"
gyp ERR! cwd /home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/sqlite3
gyp ERR! node -v v3.3.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/deploy/.nvm/versions/io.js/v3.3.0/bin/iojs /home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/sqlite3/lib/binding/node-v45-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/sqlite3/lib/binding/node-v45-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:764:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.10.0-123.9.3.el7.x86_64
node-pre-gyp ERR! command "/home/deploy/.nvm/versions/io.js/v3.3.0/bin/iojs" "/home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/sqlite3
node-pre-gyp ERR! node -v v3.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok 
Failed to execute '/home/deploy/.nvm/versions/io.js/v3.3.0/bin/iojs /home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/sqlite3/lib/binding/node-v45-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/sqlite3/lib/binding/node-v45-linux-x64' (1)
/home/deploy/.nvm/versions/io.js/v3.3.0/bin/cnpm -> /home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/cnpm/bin/cnpm
/home/deploy/.nvm/versions/io.js/v3.3.0/bin/cnpm-check -> /home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/cnpm/bin/cnpm-check
/home/deploy/.nvm/versions/io.js/v3.3.0/bin/cnpm-sync -> /home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/cnpm/bin/cnpm-sync
/home/deploy/.nvm/versions/io.js/v3.3.0/bin/cnpm-web -> /home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/cnpm/bin/cnpm-web
/home/deploy/.nvm/versions/io.js/v3.3.0/bin/cnpm-user -> /home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/cnpm/bin/cnpm-user
/home/deploy/.nvm/versions/io.js/v3.3.0/bin/cnpm-doc -> /home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/cnpm/bin/cnpm-doc
/home/deploy/.nvm/versions/io.js/v3.3.0/bin/cnpm-search -> /home/deploy/.nvm/versions/io.js/v3.3.0/lib/node_modules/cnpm/bin/cnpm-search
npm ERR! Linux 3.10.0-123.9.3.el7.x86_64
npm ERR! argv "/home/deploy/.nvm/versions/io.js/v3.3.0/bin/iojs" "/home/deploy/.nvm/versions/io.js/v3.3.0/bin/npm" "install" "-g" "--build-from-source" "--registry=http://registry.npm.taobao.org" "--disturl=http://npm.taobao.org/mirrors/node" "cnpmjs.org" "cnpm" "sqlite3"
npm ERR! node v3.3.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.10 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.10 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/deploy/npm-debug.log
```

**Comment by i5ting** [comment]
目前测试v2.3.4下没问题

**Comment by fengmk2** [comment]
disturl=http://npm.taobao.org/mirrors/node 参数不对，改为 disturl=http://npm.taobao.org/mirrors/iojs

**Comment by fengmk2** [comment]
sqlite3 好像不支持 iojs 3

**Comment by i5ting** [comment]
部署之后，也启动成功了，但7001和7002都不能访问，防火墙也没问题，登录不知道对不对，也没有日志，进到cli里，直接start也没错。。。。

**Comment by fengmk2** [comment]
你确定启动成功了？npm start 会输出一个日志文件的，看看吧。
