### ISSUE TITLE
Migrating error

### ISSUE THREAD

**Issue by lyqdudu** [cnpm/cnpmjs.org#662]
[yqliu@SVR2341HP360 bin]$ tail -f /home/yqliu/.cnpmjs.org/logs/nodejs_stdout.log
    at Object.<anonymous> (/opt/cnpmjs.org/sync/index.js:53:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/cnpmjs.org/dispatch.js:37:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
[Thu Sep 24 2015 16:36:36 GMT+0800 (CST)] [worker:9584] kill timeout, exit now.

**Comment by lyqdudu** [comment]
我在升级的时候遇到这个问题，有谁遇到过吗

**Comment by lyqdudu** [comment]
[yqliu@SVR2341HP360 cnpmjs.org]$ node --harmony tools/sync_download_total.js
/opt/cnpmjs.org/tools/sync_download_total.js:108
}).then(function () {
   ^
TypeError: undefined is not a function
    at Object.<anonymous> (/opt/cnpmjs.org/tools/sync_download_total.js:108:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
bash: /tmp/.2015-09-24/yqliu_SVR2341HP360_history: No such file or directory

**Comment by fengmk2** [comment]
node 要求 >= 1.0.0
