### ISSUE TITLE
TypeError: Cannot assign to read only property '_cnpm_publish_time' 

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#670]
```
2015-10-06 11:35:17.576 nodejs.TypeErrorException: TypeError: Cannot assign to read only property '_cnpm_publish_time' of %7B%22name%22%3A%22angular-svg-round-progressbar%22%2C%22version%22%3A%220.3.5%22%2C%22description%22%3A%22AngularJS%20module%20that%20uses%20SVG%20to%20create%20a%20circular%20progressar%22%2C%22main%22%3A%22build%2FroundProgress.min.js%22%2C%22scripts%22%3A%7B%7D%2C%22repository%22%3A%7B%22type%22%3A%22git%22%2C%22url%22%3A%22git%3A%2F%2Fgithub.com%2Fcrisbeto%2Fangular-svg-round-progressbar.git%22%7D%2C%22keywords%22%3A%5B%22angular%22%2C%22progress%22%2C%22circle%22%2C%22round%22%2C%22svg%22%5D%2C%22author%22%3A%7B%22name%22%3A%22crisbeto%22%7D%2C%22license%22%3A%22MIT%22%2C%22bugs%22%3A%7B%22url%22%3A%22https%3A%2F%2Fgithub.com%2Fcrisbeto%2Fangular-svg-round-progressbar%2Fissues%22%7D%2C%22homepage%22%3A%22https%3A%2F%2Fgithub.com%2Fcrisbeto%2Fangular-svg-round-progressbar%22%2C%22devDependencies%22%3A%7B%22connect-livereload%22%3A%22%5E0.5.3%22%2C%22grunt%22%3A%22%5E0.4.5%22%2C%22grunt-contrib-concat%22%3A%22%5E0.5.0%22%2C%22grunt-contrib-connect%22%3A%22%5E0.11.2%22%2C%22grunt-contrib-jshint%22%3A%22%5E0.11.1%22%2C%22grunt-contrib-uglify%22%3A%22%5E0.5.0%22%2C%22grunt-contrib-watch%22%3A%22%5E0.6.1%22%2C%22grunt-gh-pages%22%3A%22%5E0.9.1%22%2C%22jshint-stylish%22%3A%22%5E1.0.1%22%2C%22load-grunt-tasks%22%3A%22%5E3.3.0%22%7D%2C%22dependencies%22%3A%7B%22angular%22%3A%22%5E1.3.0%22%7D%2C%22gitHead%22%3A%220ae4addb8b140ef1d9eb90a15104b61832359854%22%2C%22_id%22%3A%22angular-svg-round-progressbar%400.3.5%22%2C%22_shasum%22%3A%22ec6cf24926b5f17cc4f3cbb365f6b8f4cb61b31d%22%2C%22_from%22%3A%22.%22%2C%22_npmVersion%22%3A%222.11.2%22%2C%22_nodeVersion%22%3A%220.12.5%22%2C%22_npmUser%22%3A%7B%22name%22%3A%22crisbeto%22%2C%22email%22%3A%22crisbeto%40abv.bg%22%7D%2C%22dist%22%3A%7B%22shasum%22%3A%22ec6cf24926b5f17cc4f3cbb365f6b8f4cb61b31d%22%2C%22size%22%3A14246%2C%22noattachment%22%3Afalse%2C%22tarball%22%3A%22http%3A%2F%2F78red6.com2.z0.glb.qiniucdn.com%2Fangular-svg-round-progressbar%2F-%2Fangular-svg-round-progressbar-0.3.5.tgz%22%7D%2C%22maintainers%22%3A%5B%7B%22name%22%3A%22crisbeto%22%2C%22email%22%3A%22crisbeto%40abv.bg%22%7D%5D%2C%22directories%22%3A%7B%7D%2C%22readme%22%3A%22%23%20Angular%20SVG%20round%20progressbar%5Cr%5Cn%5Cr%5CnAngularJS%20module%20that%20uses%20SVG%20to%20create%20a%20circular%20progressbar%5Cr%5Cn%5Cr%5Cn%23%23%20%5BDemo%5D(http%3A%2F%2Fcrisbeto.github.io%2Fangular-svg-round-progressbar%2F)%5Cr%5Cn%5Cr%5Cn%23%23%20Install%5Cr%5Cn%5Cr%5CnInclude%20Angular%20and%20%5BroundProgress.min.js%5D(https%3A%2F%2Fraw.githubusercontent.com%2Fcrisbeto%2Fangular-svg-round-progressbar%2Fmaster%2Fbuild%2FroundProgress.min.js)%20or%20%5BroundProgress.js%5D(https%3A%2F%2Fraw.githubusercontent.com%2Fcrisbeto%2Fangular-svg-round-progressbar%2Fmaster%2Fbuild%2FroundProgress.js)%20in%20your%20page.%20You%20can%20use%20npm%2C%20bower%2C%20or%20a%20script-tag%3A%5Cr%5Cn%5Cr%5Cn%60npm%20install%20angular-svg-round-progressbar%60%5Cr%5Cn%5Cr%5Cnor%5Cr%5Cn%5Cr%5Cn%60bower%20install%20angular-svg-round-progressbar%60%5Cr%5Cn%5Cr%5Cnor%5Cr%5Cn%5Cr%5Cn%60%3Cscript%20src%3D%5C%22http%3A%2F%2Fcrisbeto.github.io%2Fangular-svg-round-progressbar%2FroundProgress.min.js%5C%22%3E%3C%2Fscript%3E%60%5Cr%5Cn%5Cr%5Cn%5Cr%5CnAdd%20%60angular-svg-round-progress%60%20to%20your%20app's%20module%20dependencies%3A%5Cr%5Cn%5Cr%5Cn%60%60%60javascript%5Cr%5Cnangular.module('someModule'%2C%20%5B'angular-svg-round-progress'%5D)%5Cr%5Cn%60%60%60%5Cr%5Cn%5Cr%5Cn%23%23%20Options%5Cr%5Cn%5Cr%5Cn*%20To%20edit%20the%20default%20values%2C%20change%20the%20options%20in%20the%20%60roundProgressConfig%60%20constant.%5Cr%5Cn*%20Since%20the%20%600.2.0%60%20release%20this%20directive%20uses%20dynamic%20binding.%20For%20example%2C%20if%20you%20want%20to%20change%20the%20fill%20color%20at%20a%20certain%20value%2C%20you%20can%20use%20%60color%3D%5C%22%7B%7B%20(current%20%2F%20max%20%3C%200.5)%20%3F%20'%23ff8080'%20%3A%20'%2345ccce'%20%7D%7D%5C%22%60.%5Cr%5Cn%5Cr%5Cn%7C%20Name%20%20%20%20%20%20%20%20%20%20%20%7C%20Description%20%20%20%20%20%20%20%20%20%20%20%20%0%20%20%20%20%20%20%20%20%20%20%20%20%20%220%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Required%20%20%7C%20Default%20value%20%20%20%20%20%7C%20Possible%20values%20%20%20%7C%5Cr%5Cn%7C%20---%20%20%20%20%20%20%20%20%20%20%20%20%7C%20---%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20---%20%20%20%20%20%20%20%7C%20---%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20---%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%5Cr%5Cn%7C%20%60current%60%20%20%20%20%20%20%7C%20The%20current%20progress.%20Limited%20by%20the%20%60max%60%20option.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Yes%20%20%20%20%20%20%20%7C%20undefined%20%20%20%20%20%20%20%20%20%7C%20Integer%20%20%20%20%20%20%20%20%20%20%20%7C%5Cr%5Cn%7C%20%60max%60%20%20%20%20%20%20%20%20%20%20%7C%20The%20progress'%20maximum%20value.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Yes%20%20%20%20%20%20%20%7C%20undefined%20%20%20%20%20%20%20%20%20%7C%20Integer%20%20%20%20%20%20%20%20%20%20%20%7C%5Cr%5Cn%7C%20%60radius%60%20%20%20%20%20%20%20%7C%20Radius%20of%20the%20circle.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20No%20%20%20%20%20%20%20%20%7C%2050%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Integer%20%20%20%20%20%20%20%20%20%20%20%7C%5Cr%5Cn%7C%20%60color%60%20%20%20%20%20%20%20%20%7C%20The%20color%20of%20the%20%60current%60%20value%20on%20the%20circle.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20No%20%20%20%20%20%20%20%20%7C%20%2345ccce%20%20%20%20%20%20%20%20%20%20%20%7C%20Hex%20color%20or%20string.%20Refer%20to%20%5Bthis%20example%5D(https%3A%2F%2Fgithub.com%2Fcrisbeto%2Fangular-svg-round-progressbar%2Fissues%2F29)%20for%20an%20example%20of%20using%20a%20gradient.%20%20%20%20%20%20%20%20%7C%5Cr%5Cn%7C%20%60bgcolor%60%20%20%20%20%20%20%7C%20Color%20of%20the%20circle's%20background.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20No%20%20%20%20%20%20%20%20%7C%20%23eaeaea%20%20%20%20%20%20%20%20%20%20%20%7C%20Hex%20color%20or%20string.%20Refer%20to%20%5Bthis%20example%5D(https%3A%2F%2Fgithub.com%2Fcrisbeto%2Fangular-svg-round-progressbar%2Fissues%2F29)%20for%20an%20example%20of%20using%20a%20gradient.%20%20%20%20%20%20%20%20%20%7C%5Cr%5Cn%7C%20%60stroke%60%20%20%20%20%20%20%20%7C%20Specifies%20the%20circle's%20thickness.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20No%20%20%20%20%20%20%20%20%7C%2015%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Integer%20%20%20%20%20%20%20%20%20%20%20%7C%5Cr%5Cn%7C%20%60semi%60%20%20%20%20%20%20%20%20%20%7C%20Whether%20the%20progressbar%20should%20be%20a%20full%20circle%20or%20a%20semicircle.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20No%20%20%20%20%20%20%20%20%7C%20false%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Boolean%20%20%20%20%20%20%20%20%20%20%20%7C%5Cr%5Cn%7C%20%60clockwise%60%20%20%20%20%7C%20Whether%20the%20progressbar%20should%20rotate%20clockwise%20or%20counter-clockwise.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20No%20%20%20%20%20%20%20%20%7C%20true%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Boolean%20%20%20%20%20%20%20%20%20%20%20%7C%5Cr%5Cn%7C%20%60responsive%60%20%20%20%7C%20Whether%20the%20progressbar%20should%20fit%20inside%20its%20parent%20container.%20**Note**%20Turning%20this%20option%20on%20will%20override%20the%20specified%20radius%20in%20order%20to%20make%20the%20circle%20fit%20in%20its%20parent.%20The%20radius%20to%20stroke%20ratio%20won't%20change.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20No%20%20%20%20%20%20%20%20%7C%20false%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Boolean%20%20%20%20%20%20%20%20%20%20%20%7C%5Cr%5Cn%7C%20%60rounded%60%20%20%20%20%20%20%7C%20Whether%20the%20current%20progress%20ending%20should%20be%20rounded%20or%20straight.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20No%20%20%20%20%20%20%20%20%7C%20false%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Boolean%20%20%20%20%20%20%20%20%20%20%20%7C%5Cr%5Cn%7C%20%60duration%60%20%20%20%20%20%7C%20The%20duration%20of%20the%20animation.%20Pass%200%20for%20no%20animation.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20No%20%20%20%20%20%20%20%20%7C%20800%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Integer%20%20%20%20%20%20%20%20%20%20%20%7C%5Cr%5Cn%7C%20%60animation%60%20%20%20%20%7C%20The%20easing%20function%20that%20will%20be%20used%20when%20animating.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20No%20%20%20%20%20%20%20%20%7C%20easeOutCubic%20%20%20%20%20%20%7C%20linearEase%20%3Cbr%3E%20easeInQuad%20%3Cbr%3E%20easeOutQuad%20%3Cbr%3E%20easeInOutQuad%20%3Cbr%3E%20easeInCubic%20%3Cbr%3E%20easeOutCubic%20%3Cbr%3E%20easeInOutCubic%20%3Cbr%3E%20easeInQuart%20%3Cbr%3E%20easeOutQuart%20%3Cbr%3E%20easeInOutQuart%20%3Cbr%3E%20easeInQuint%20%3Cbr%3E%20easeOutQuint%20%3Cbr%3E%20easeInOutQuint%20%3Cbr%3E%20easeInSine%20%3Cbr%3E%20easeOutSine%20%3Cbr%3E%20easeInOutSine%20%3Cbr%3E%20easeInExpo%20%3Cbr%3E%20easeOutExpo%20%3Cbr%3E%20easeInOutExpo%20%3Cbr%3E%20easeInCirc%20%3Cbr%3E%20easeOutCirc%20%3Cbr%3E%20easeInOutCirc%20%3Cbr%3E%20easeInElastic%20%3Cbr%3E%20easeOutElastic%20%3Cbr%3E%20easeInOutElastic%20%3Cbr%3E%20easeInBack%20%3Cbr%3E%20easeOutBack%20%3Cbr%3E%20easeInOutBack%20%3Cbr%3E%20easeInBounce%20%3Cbr%3E%20easeOutBounce%20%3Cbr%3E%20easeInOutBounce%20%3Cbr%3E%20%7C%5Cr%5Cn%5Cr%5Cn%5Cr%5Cn%23%23%23%20Example%3A%5Cr%5Cn%5Cr%5Cn%60%60%60html%5Cr%5Cn%3Cdiv%5Cr%5Cn%20%20%20%20round-progress%5Cr%5Cn%20%20%20%20max%3D%5C%22max%5C%22%5Cr%5Cn%20%20%20%20current%3D%5C%22current%5C%22%5Cr%5Cn%20%20%20%20color%3D%5C%22%2345ccce%5C%22%5Cr%5Cn%20%20%20%20bgcolor%3D%5C%22%23eaeaea%5C%22%5Cr%5Cn%20%20%20%20radius%3D%5C%22100%5C%22%5Cr%5Cn%20%20%20%20stroke%3D%5C%2220%5C%22%5Cr%5Cn%20%20%20%20semi%3D%5C%22true%5C%22%5Cr%5Cn%20%20%20%20rounded%3D%5C%22true%5C%22%5Cr%5Cn%20%20%20%20clockwise%3D%5C%22false%5C%22%5Cr%5Cn%20%20%20%20responsive%3D%5C%22false%5C%22%5Cr%5Cn%20%20%20%20duration%3D%5C%22800%5C%22%5Cr%5Cn%20%20%20%20animation%3D%5C%22easeInOutQuart%5C%22%3E%3C%2Fdiv%3E%5Cr%5Cn%60%60%60%5Cr%5Cn%5Cr%5Cn%23%23%20Browser%20support%5Cr%5Cn%5Cr%5Cn*%20Internet%20Explorer%209%2B%5Cr%5Cn*%20Firefox%2028.0%2B%5Cr%5Cn*%20Chrome%2031%2B%5Cr%5Cn*%20Safari%205.1%2B%5Cr%5Cn*%20and%20pretty%20much%20any%20browser%20that%20supports%20SVG%5Cr%5Cn%5Cr%5Cn%5Cr%5Cn%23%23%20Development%5Cr%5Cn%5Cr%5Cn*%20%20%60npm%20install%60%20to%20install%20development%20dependencies%5Cr%5Cn*%20%20%60grunt%60%20to%20run%20a%20development%20server.%20Not%20mandatory(you%20can%20run%20the%20build%2Findex.html%20directly)%2C%20but%20more%20convenient.%5Cr%5Cn*%20%20%60grunt%20build%60%20to%20build%20minified%20demo%20in%20build%2F%5Cr%5Cn*%20%20%60grunt%20deploy%60%20to%20build%20minified%20demo%20and%20push%20it%20to%20gh-pages%20branch%5Cr%5Cn%5Cr%5Cn%5Cr%5Cn%23%23%20Credits%5Cr%5Cn%5Cr%5Cn*%20Erik%20M%C3%B6ller%20for%20the%20requestAnimationFrame%20shim%5Cr%5Cn*%20%5BModernizr%5D(http%3A%2F%2Fmodernizr.com%2F)%20for%20the%20SVG%20support%20test%5Cr%5Cn*%20%5BRobert%20Penner%5D(http%3A%2F%2Fwww.robertpenner.com%2Feasing%2F)%20for%20the%20easing%20function%5Cr%5Cn*%20%5Bopsb%5D(http%3A%2F%2Fstackoverflow.com%2Fquestions%2F5736398%2Fhow-to-calculate-the-svg-path-for-an-arc-of-a-circle)%20for%20some%20of%20the%20math%5Cr%5Cn*%20%5Bkonsumer%5D(https%3A%2F%2Fgithub.com%2Fkonsumer)%20for%20build-system%20%26%20deployment%20stuff%5Cr%5Cn%22%2C%22publish_time%22%3A1443882468570%7D
    at Object.list (/data/git/cnpmjs.org/controllers/registry/package/list.js:134:28)
    at next (native)
    at Object.syncByInstall (/data/git/cnpmjs.org/middleware/sync_by_install.js:27:19)
    at next (native)
    at Object.<anonymous> (/data/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-router/node_modules/koa-compose/index.js:29:12)
    at next (native)
    at Object.dispatch (/data/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-router/lib/router.js:97:44)
    at next (native)
    at Object.etag (/data/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-etag/index.js:25:12)
    at next (native)
    at Object.<anonymous> (/data/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-conditional-get/index.js:16:12)
    at next (native)
    at Object.notFound (/data/git/cnpmjs.org/middleware/registry_not_found.js:18:10)
    at next (native)
    at Object.proxyToNpm (/data/git/cnpmjs.org/middleware/proxy_to_npm.js:36:21)
    at next (native)
pid: 4318
domainThrown: false
Host: 10-11-21-176
URL: /angular-svg-round-progressbar
Data: ""
2015-10-06 11:35:17.576
```

**Comment by fengmk2** [comment]
cnpm sync angular-svg-round-progressbar

**Comment by fengmk2** [comment]
http://r.cnpmjs.org/angular-svg-round-progressbar
