### ISSUE TITLE
Client.prototype.upload = function* (filepath, options) {

### ISSUE THREAD

**Issue by sharyuke** [cnpm/cnpmjs.org#704]
Client.prototype.upload = function* (filepath, options) {
                                  ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/sharyuke/tools/cnpmjs.org/config/index.js:143:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by sharyuke** [comment]
when I sudo npm start or node --harmony_generators dispatch.js i got this

**Comment by ibigbug** [comment]
Update you NodeJS version && just run  `make dev` would work.

**Comment by fengmk2** [comment]
@sharyuke require node >= 2.0.0

**Comment by ganxunzou** [comment]
I have the same problem .  

I Linux Environment:
[root@iZ28qt5vcnzZ cnpmjs.org]# node -v
v0.12.9
==================================================
mysql> select version()
    -> ;
+-----------+
| version() |
+-----------+
| 5.7.11    |
+-----------+

==================================================
[root@iZ28qt5vcnzZ cnpmjs.org]# redis-server -v
Redis server v=2.8.19 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=c0359e7aa3798aa2

How to solve it?

**Comment by ganxunzou** [comment]
@sharyuke  how do you solve  it ?

**Comment by dead-horse** [comment]
@ganxunzou  require node >= 2.0.0
