### ISSUE TITLE
五分钟安装私有npm报错

### ISSUE THREAD

**Issue by jaywcjlove** [cnpm/cnpmjs.org#723]
[五分钟安装私有npm](https://github.com/cnpm/cnpmjs.org/wiki/Deploy-a-private-npm-registry-in-5-minutes)报错 ，这个如何解决呢？
- node v4.2.2
- npm v3.3.9

我运行`sudo npm install -g --build-from-source cnpmjs.org cnpm sqlite3` 就报错...

```
> sqlite3@3.1.1 install /usr/local/lib/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

gyp: /Users/kacperwang/.node-gyp/4.2.2/common.gypi not found (cwd: /usr/local/lib/node_modules/sqlite3) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:349:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/sqlite3/lib/binding/node-v46-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/local/lib/node_modules/sqlite3/lib/binding/node-v46-darwin-x64"
gyp ERR! cwd /usr/local/lib/node_modules/sqlite3
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v2.0.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/sqlite3/lib/binding/node-v46-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/local/lib/node_modules/sqlite3/lib/binding/node-v46-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 15.0.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/sqlite3
node-pre-gyp ERR! node -v v4.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.14
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/sqlite3/lib/binding/node-v46-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/local/lib/node_modules/sqlite3/lib/binding/node-v46-darwin-x64' (1)
/usr/local/lib

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "--build-from-source" "cnpmjs.org" "cnpm" "sqlite3"
npm ERR! node v4.2.2
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kacperwang/cnpmjs.org/npm-debug.log
```

**Comment by fengmk2** [comment]
`--build-from-source` 去掉看看？

**Comment by jaywcjlove** [comment]
@fengmk2 

执行这个又报错了
```
$ nohup cnpmjs.org start --admins='myname,othername' \
  --scopes='@my-company-name,@other-name' &
```

```
sourceNpmRegistry: https://registry.npm.taobao.org
syncModel: none
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                                                  ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/cnpmjs.org/view/web/_layout.html'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/cnpmjs.org/servers/web.js:80:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cnpmjs.org/worker.js:18:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366
```

**Comment by ibigbug** [comment]
这个是权限的问题。可以先配置一下不用 root 权限运行 npm，或者用 sudo 试试。

**Comment by fengmk2** [comment]
呃。。。看来五分钟教程要重写了，@ibigbug 你比较不熟悉，你来写？

**Comment by jaywcjlove** [comment]
@fengmk2  先搞个教程让我搭建起来玩儿一玩儿嘛

**Comment by alsotang** [comment]
呃。。我是 git clone 之后手动搭建的，在这里我有跟人讨论过：
https://github.com/cnodejs/nodeclub/issues/404 。一块不可避免需要定制的业务代码，抽象成一个 npm
module，是一种抽象过度。

kenny.wang，克隆下来吧。

2015-11-12 20:49 GMT+08:00 kenny.wang <notifications@github.com>:

**Comment by ibigbug** [comment]
@fengmk2 我再跑一遍看看

**Comment by jaywcjlove** [comment]
@alsotang 我clone下来还没有跑通，我得研究研究。

**Comment by ibigbug** [comment]
跑了两遍，似乎没什么问题，汗。

不过 clone 下来运行似乎也不复杂。

**Comment by jaywcjlove** [comment]
@ibigbug 你是windows?   mac 下加上 `--build-from-source`这个就报错...

**Comment by ibigbug** [comment]
@jaywcjlove 我在 OS X 和 Fedora 虚拟机上面都测试了，版本号跟你列出的相同。我回家再试试。教程没有删除，好像有人误编辑了。

**Comment by ibigbug** [comment]
@fengmk2

**Comment by fengmk2** [comment]
可以看看 commits，谁这么调皮

**Comment by ibigbug** [comment]
我已经 revert 回来了。那个 ID 不认识。。

**Comment by jaywcjlove** [comment]
@ibigbug `cnpmjs.org start`

报错
```
sourceNpmRegistry: https://registry.npm.taobao.org
syncModel: none
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                                                  ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/cnpmjs.org/view/web/_layout.html'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/cnpmjs.org/servers/web.js:80:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cnpmjs.org/worker.js:18:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by jaywcjlove** [comment]
@ibigbug 尼玛这个是人品问题吧。clone 下来玩儿也报错。  `sudo make dev`

```
Starting cnpmjs.org ...
cluster: false
admins: {"fengmk2":"fengmk2@gmail.com","admin":"admin@cnpmjs.org","dead_horse":"dead_horse@qq.com"}
scopes: ["@cnpm","@cnpmtest","@cnpm-test"]
sourceNpmRegistry: https://registry.npm.taobao.org
syncModel: none
TypeError: Class constructors cannot be invoked without 'new'
    at Application (/Users/kacperwang/cnpmjs.org/node_modules/koa/lib/application.js:38:14)
    at Object.<anonymous> (/Users/kacperwang/cnpmjs.org/servers/registry.js:20:28)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.nodeDevHook [as .js] (/Users/kacperwang/cnpmjs.org/node_modules/node-dev/lib/hook.js:43:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/kacperwang/cnpmjs.org/worker.js:17:16)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.nodeDevHook [as .js] (/Users/kacperwang/cnpmjs.org/node_modules/node-dev/lib/hook.js:43:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
[ERROR] 01:10:49 TypeError
```

**Comment by alsotang** [comment]
咦？这是 koa 2.x 的报错，我看 cnpmjs.org 已经锁 koa 版本了啊。。。奇怪

**Comment by jaywcjlove** [comment]
@alsotang  你安装 哪个版本呢？ 不是打了tag  我下个tag来跑？  clone下来玩儿也报错。人品不行啊。

**Comment by ibigbug** [comment]
@jaywcjlove 前一个错误，跟上面的类似的。你注意到错误栈第一行
> Error: EACCES: permission denied, open '/usr/loc...

就会发现其实还是权限问题。

第二个报错我还不清楚。

**Comment by jaywcjlove** [comment]
@ibigbug  

我进入`/usr/local/lib/node_modules/`目录给权限果然跑起来了，`sudo chmod -R 777 cnpmjs.org/`

这个是怎么玩儿的呢？跟npm是一样的玩儿的吗 
```
nohup cnpmjs.org start --admins='myname,othername' \
  --scopes='@my-company-name,@other-name' &
```

执行上面命令之后 `cnpm login` 默认用户名密码是几多啊？

```bash 
npm WARN adduser Incorrect username or password
npm WARN adduser You can reset your account by visiting:
npm WARN adduser
npm WARN adduser     https://npmjs.org/forgot
npm WARN adduser
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--registry=https://registry.npm.taobao.org" "--cache=/Users/kacperwang/.npm/.cache/cnpm" "--disturl=https://npm.taobao.org/dist" "--userconfig=/Users/kacperwang/.cnpmrc" "login"
npm ERR! node v4.2.2
npm ERR! npm  v3.3.9
npm ERR! code E401

npm ERR! unauthorized Login first: -/user/org.couchdb.user:wangchujiang/-rev/1-6282b90275ec9528ca1b4436ebafd3cf
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kacperwang/helloworld/npm-debug.log
```

**Comment by alsotang** [comment]
我装的就是最新的版本啊

https://cnodejs.org/topic/5646147789b4b49902e7fbd5

2015-11-14 3:46 GMT+08:00 kenny.wang <notifications@github.com>:

**Comment by jaywcjlove** [comment]
@alsotang    可以上传私有 包到我们自己的私有服务器吗？cnpmjs.org  我搭建起来了 cnpm publish 上传的时候 总说我不是admin用户，这个是咋玩儿的呢？

**Comment by didikeke** [comment]
可以开vpn试试。

刚安装其他的包，因为也有sqlite3@3.1.1死活安装不上去，才搜到这个帖子。 然后cnpm安装试了也不行。

刚在服务器上开了sslocal， proxychains npm xxx 终于安装好了。 希望对其他 sqlite3@3.1.1安装出错搜到这个帖子的人有点用。

**Comment by fengmk2** [comment]
看来我还是将sqlite镜像做了
