### ISSUE TITLE
TypeError: Cannot assign to read only property 'fromNow' of %7B%22name%22%3

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#808]
```
at Object.show (/data/git/cnpmjs.org/controllers/web/package/show.js:89:23)
    at next (native)
    at Object.dispatch (/data/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-router/lib/router.js:97:44)
    at next (native)
    at Object.markdown (/data/git/cnpmjs.org/node_modules/koa-markdown/index.js:73:21)
    at next (native)
    at Object.etag (/data/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-etag/index.js:25:12)
    at next (native)
    at Object.conditional (/data/git/cnpmjs.org/node_modules/koa-middlewares/node_modules/koa-conditional-get/index.js:16:12)
    at next (native)
    at Object.notFound (/data/git/cnpmjs.org/middleware/web_not_found.js:20:10)
    at next (native)
    at Object.unauthorized (/data/git/cnpmjs.org/middleware/auth.js:69:19)
    at next (native)
    at Object.auth (/data/git/cnpmjs.org/middleware/auth.js:34:34)
    at next (native)

```

**Comment by fengmk2** [comment]
parse package error: appium-selendroid-driver, id: 1383056 version: 1.0.1, error: URIError: URI malformed

**Comment by fengmk2** [comment]
url: '/package/appium-selendroid-driver'
