### ISSUE TITLE
TypeError: ModuleLog.findById is not a function

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmjs.org#839]
```
2016-02-22 16:35:58.164 nodejs.TypeErrorException: TypeError: ModuleLog.findById is not a function
    at Object.exports.get (/git/cnpmjs.org/services/module_log.js:53:26)
    at next (native)
    at Object.exports.getSyncLog (/git/cnpmjs.org/controllers/sync.js:70:24)
    at next (native)
    at Object.dispatch (/git/cnpmjs.org/node_modules/.npminstall/koa-router/3.8.0/lib/router.js:97:44)
    at next (native)
    at Object.markdown (/git/cnpmjs.org/node_modules/.npminstall/koa-markdown/2.0.1/index.js:73:21)
    at throw (native)
    at Object.etag (/git/cnpmjs.org/node_modules/.npminstall/koa-etag/2.0.0/index.js:25:12)
    at throw (native)
pid: 15145
Host: cnpm6
URL: /sync/mocha/log/121883?offset=0
Data: ''
2016-02-22 16:35:58.164
```

**Comment by fengmk2** [comment]
@dead-horse 最近改了啥？

**Comment by fengmk2** [comment]
我升级到 `deps: sequelize@3.19.0` 看看。

**Comment by fengmk2** [comment]
使用最新的 commit 重启后就 ok 了。

**Comment by dead-horse** [comment]
sequelize API 变更？
