### ISSUE TITLE
npm run start SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by ganxunzou** [cnpm/cnpmjs.org#849]
[root@iZ28qt5vcnzZ cnpmjs.org]# npm run start

 "> cnpmjs.org@2.8.0 start /root/cnpmjs.org"
 "> ./bin/nodejsctl start && cp History.md docs/web/history.md"

/root/cnpmjs.org/node_modules/fs-cnpm/index.js:40
Client.prototype.upload = function* (filepath, options) {
                                  ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/cnpmjs.org/config/index.js:143:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
Starting cnpmjs.org ...
nohup node /root/cnpmjs.org/dispatch.js >  2>&1 &
./bin/nodejsctl: line 38: $STDOUT_LOG: ambiguous redirect
Start nodejs success. PID=
[root@iZ28qt5vcnzZ cnpmjs.org]# 
[root@iZ28qt5vcnzZ cnpmjs.org]# node -v
v0.12.9
[root@iZ28qt5vcnzZ cnpmjs.org]#

**Comment by ganxunzou** [comment]
very sorry . I saw a long time ago.

**Comment by dead-horse** [comment]
___Requires Node.js >= 4.2.3___
