### ISSUE TITLE
 Error: connect ECONNREFUSED 127.0.0.1:7001

### ISSUE THREAD

**Issue by ganxunzou** [cnpm/cnpmjs.org#850]
按照5分钟教程搭建

`nohup cnpmjs.org start --admins='myname,othername' \
  --scopes='@my-company-name,@other-name' &
`
执行这个步骤后，程序处于待输入状态。在执行这个`cnpm set registry http://localhost:7001`直接退出，但是查看了~/.cnpmrc的配置文件，生成是成功的。

然后我接着往下执行，$ cnpm login，输入用户名，密码和邮箱（随便输入的）等待好久就报错如下：

`cnpm login
Username: ganxunzou
Password: 
Email: (this IS public) ganxunzou@163.com
npm ERR! Linux 3.10.0-123.9.3.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/root/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/root/.cnpm" "--registry=http://localhost:7001" "--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "login"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.22
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED 127.0.0.1:7001
npm ERR!     at Object.exports._errnoException (util.js:870:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:893:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)
npm ERR!  { [Error: connect ECONNREFUSED 127.0.0.1:7001]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '127.0.0.1',
npm ERR!   port: 7001 }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
[1]+  Exit 1                  nohup cnpmjs.org start --admins='ganxz' --scopes='@conivision'
[root@iZ28qt5vcnzZ ~]# cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm',
1 verbose cli   '--userconfig=/root/.cnpmrc',
1 verbose cli   '--disturl=https://npm.taobao.org/mirrors/node',
1 verbose cli   '--cache=/root/.cnpm',
1 verbose cli   '--registry=http://localhost:7001',
1 verbose cli   '--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js',
1 verbose cli   'login' ]
2 info using npm@2.14.22
3 info using node@v4.3.2
4 verbose config Skipping project config: /root/.npmrc. (matches userconfig)
5 verbose adduser before first PUT { _id: 'org.couchdb.user:ganxunzou',
5 verbose adduser   name: 'ganxunzou',
5 verbose adduser   password: 'XXXXX',
5 verbose adduser   email: 'ganxunzou@163.com',
5 verbose adduser   type: 'user',
5 verbose adduser   roles: [],
5 verbose adduser   date: '2016-03-05T09:22:25.449Z' }
6 verbose request uri http://localhost:7001/-/user/org.couchdb.user:ganxunzou
7 verbose request new user, so can't send auth
8 info attempt registry request try #1 at 5:22:25 PM
9 verbose request id fa6dcc6d0ff44a9c
10 http request PUT http://localhost:7001/-/user/org.couchdb.user:ganxunzou
11 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 127.0.0.1:7001
12 info attempt registry request try #2 at 5:22:35 PM
13 http request PUT http://localhost:7001/-/user/org.couchdb.user:ganxunzou
14 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 127.0.0.1:7001
15 info attempt registry request try #3 at 5:23:35 PM
16 http request PUT http://localhost:7001/-/user/org.couchdb.user:ganxunzou
17 verbose request invalidating /root/.cnpm/localhost_7001/-/user/org.couchdb.user_3Aganxunzou on PUT
18 verbose adduser back [ { [Error: connect ECONNREFUSED 127.0.0.1:7001]
18 verbose adduser     code: 'ECONNREFUSED',
18 verbose adduser     errno: 'ECONNREFUSED',
18 verbose adduser     syscall: 'connect',
18 verbose adduser     address: '127.0.0.1',
18 verbose adduser     port: 7001 },
18 verbose adduser   undefined,
18 verbose adduser   undefined ]
19 verbose stack Error: connect ECONNREFUSED 127.0.0.1:7001
19 verbose stack     at Object.exports._errnoException (util.js:870:11)
19 verbose stack     at exports._exceptionWithHostPort (util.js:893:20)
19 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)
20 verbose cwd /root
21 error Linux 3.10.0-123.9.3.el7.x86_64
22 error argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/root/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/root/.cnpm" "--registry=http://localhost:7001" "--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "login"
23 error node v4.3.2
24 error npm  v2.14.22
25 error code ECONNREFUSED
26 error errno ECONNREFUSED
27 error syscall connect
28 error Error: connect ECONNREFUSED 127.0.0.1:7001
28 error     at Object.exports._errnoException (util.js:870:11)
28 error     at exports._exceptionWithHostPort (util.js:893:20)
28 error     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)
28 error  { [Error: connect ECONNREFUSED 127.0.0.1:7001]
28 error   code: 'ECONNREFUSED',
28 error   errno: 'ECONNREFUSED',
28 error   syscall: 'connect',
28 error   address: '127.0.0.1',
28 error   port: 7001 }
29 error If you are behind a proxy, please make sure that the
29 error 'proxy' config is set properly.  See: 'npm help config'
30 verbose exit [ 1, true ]`

**Comment by ganxunzou** [comment]
从错误上看，感觉是数据库连接异常了。数据库需要其他配置吗？

**Comment by ganxunzou** [comment]
我是CentOS7 64位的操作系统，貌似自带了一个Sqlite ，会不会和这个有关系呢？
`[root@iZ28qt5vcnzZ ~]# rpm -qa|grep sqlite*
sqlite-3.7.17-4.el7.x86_64`

**Comment by ganxunzou** [comment]
找到原因了，按照5分钟的教程，默认的数据库用的是sqlite，但是我的操作系统自导了sqlite3的安装包，可能是因为这个，导致sqlite一直无法连接。

解决方法：我改用Mysql了。
