### ISSUE TITLE
在web上Sync模块时报错

### ISSUE THREAD

**Issue by leftstick** [cnpm/cnpmjs.org#870]
```bash
[2016-03-28 17:44:55]     [caniuse-db:11] sync error, version: 1.0.30000273, SequelizeUniqueConstraintError: SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/opt/mnpm/node_modules/sequelize/lib/dialects/mysql/query.js:149:14)
    at Query._callback (/opt/mnpm/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/opt/mnpm/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/opt/mnpm/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/opt/mnpm/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/opt/mnpm/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/opt/mnpm/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket. (/opt/mnpm/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

这是什么意思？好像也不是同步失败，就是不停的报这个。但不是同步所有模块都会报这个错，有的模块才会

**Comment by fengmk2** [comment]
SequelizeUniqueConstraintError 主键冲突了，同时有多个人在同步 caniuse-db ？

**Comment by leftstick** [comment]
哦，原来如此，有这个可能！我`npm install`时报错了，我就自己跑到网页上`sync`去了。应该是后台这个时候也在`sync`吧！？

谢了

**Comment by fengmk2** [comment]
是的
