### ISSUE TITLE
sync error, version: 0.1.0, SequelizeDatabaseError xxx table is full

### ISSUE THREAD

**Issue by lijiexiang** [cnpm/cnpmjs.org#884]
你好，我在sync package时出现以下异常，请问是怎么回事，我看表的记录也才几千条而已。
 [connect-access:0] syncing, version: 0.1.0, dist: {"shasum":"c290206fbccb7ca80a6fdf2959db59662a7043e1","size":3188,"noattachment":false,"tarball":"http://registry.npm.taobao.org/connect-access/download/connect-access-0.1.0.tgz"}, no deps: false, publish on cnpm: false, dependencies: 2, devDependencies: 0, syncDevDependencies: false
[2016-04-11 05:54:07]     add dependencies: path-to-regexp
[2016-04-11 05:54:07]     add dependencies: netmask
[2016-04-11 05:54:07]     [connect-access:0] sync error, version: 0.1.0, SequelizeDatabaseError: SequelizeDatabaseError: ER_RECORD_FILE_FULL: The table 'module_deps' is full
    at Query.formatError (/home/jackli/docker/npm/cnpm/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/home/jackli/docker/npm/cnpm/cnpmjs.org/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/home/jackli/docker/npm/cnpm/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/home/jackli/docker/npm/cnpm/cnpmjs.org/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/home/jackli/docker/npm/cnpm/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/jackli/docker/npm/cnpm/cnpmjs.org/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/home/jackli/docker/npm/cnpm/cnpmjs.org/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket. (/home/jackli/docker/npm/cnpm/cnpmjs.org/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)

不止这张表报这个异常，表：npm_module_maintainer也报这个异常了

**Comment by fengmk2** [comment]
> ER_RECORD_FILE_FULL: The table 'module_deps' is full

你的数据库所在的服务器磁盘空间满了。

**Comment by fengmk2** [comment]
google 关键词 `ER_RECORD_FILE_FULL`

**Comment by lijiexiang** [comment]
恩，已经发现了。多谢！
