### ISSUE TITLE
cnpm install bug

### ISSUE THREAD

**Issue by willin** [cnpm/cnpmjs.org#937]
```
cnpm i dtrace-provider
[dtrace-provider@*] installed at node_modules/.npminstall/dtrace-provider/0.6.0/dtrace-provider (2 packages, use 421ms, speed 80.33kB/s, json 33.98kB, tarball 0B)
excute post install scripts...
[dtrace-provider@0.6.0] scripts.install: "node scripts/install.js" at ./node_modules/.npminstall/dtrace-provider/0.6.0/dtrace-provider
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.<anonymous> (/Users/willin/Desktop/blog/test/node_modules/.npminstall/dtrace-provider/0.6.0/dtrace-provider/scripts/install.js:19:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
Error: post install error, please remove node_modules before retry!
Run "sh -c node scripts/install.js" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node scripts/install.js" error, exit code 1
    at ChildProcess.proc.on.code (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/cnpm/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

compare vs npm

```
npm i dtrace-provider
npm WARN skippingAction Module is inside a symlinked module: not running remove nan@2.3.3 node_modules/dtrace-provider/node_modules/nan
npm WARN update-linked node_modules/dtrace-provider needs updating to 0.6.0 from 0.6.0 but we can't, as it's a symlink
/Users/willin/Desktop/blog/test
└─┬ dtrace-provider@0.6.0
  └── nan@2.3.3

npm WARN enoent ENOENT: no such file or directory, open '/Users/willin/Desktop/blog/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.
```

**Comment by dead-horse** [comment]
https://github.com/chrisa/node-dtrace-provider/blob/v0.6.0/scripts/install.js#L19 缺少 npm_execpath 环境变量

**Comment by fengmk2** [comment]
https://github.com/npm/npm/blob/9e03561547ec5830c5f61caa4e6221d4d3b813aa/lib/utils/lifecycle.js#L73

还有 `npm_node_execpath`, `NODE`

**Comment by RenShine** [comment]
这个bug能修复么？  我因为这个dtrace-provider  很多npm包都用不了 很尴尬

**Comment by fengmk2** [comment]
@RenShine 早就修复了 https://github.com/cnpm/npminstall/blob/37bd581cd9861858fa5d9a204ec738eef5a6f50a/bin/install.js#L140 ，你重新安装一下 cnpm 就好了。
