### ISSUE TITLE
ResponseTimeoutError

### ISSUE THREAD

**Issue by AnnatarHe** [cnpm/cnpmjs.org#992]
Hi, I just install npmjs.org for private repository last day. and I found something trouble me a lot and I can't find answer from google.

when I run

``` bash
$ cnpm install
```

I always got message like this:

```
[immutable@^3.8.1] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/immutable
[react-dom@^15.2.0] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/react-dom
[react-redux@^4.4.5] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/react-redux
[react-addons-css-transition-group@^15.2.0] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/react-addons-css-transition-group
[react-router@^2.5.2] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/react-router
[whatwg-fetch@^1.0.0] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/whatwg-fetch
[react-router-redux@^4.0.5] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/react-router-redux
[redux@^3.5.2] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/redux
[react@^15.2.0] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/react
[@iota/fe-utils@*] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/@iota/fe-utils
[ava@^0.15.2] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/ava
[babel-core@^6.10.4] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/babel-core
[babel-loader@^6.2.4] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/babel-loader
[babel-plugin-antd@^0.4.0] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/babel-plugin-antd
[babel-plugin-react-transform@^2.0.2] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/babel-plugin-react-transform
[babel-plugin-transform-object-rest-spread@^6.8.0] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/babel-plugin-transform-object-rest-spread
[babel-preset-es2015@^6.9.0] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/babel-preset-es2015
[babel-register@^6.9.0] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/babel-register
[eslint-loader@^1.4.0] existed at /home/iotahele/Work/code/web/iota-web-client-scaffold/node_modules/eslint-loader
[eslint-config-airbnb@^9.0.1] existed at node_modules/.npminstall/eslint-config-airbnb/9.0.1/eslint-config-airbnb (0 packages, use 2s, speed 38.62B/s, json 87B, tarball 0B)
[antd@^1.6.3] existed at node_modules/.npminstall/antd/1.6.4/antd (1 packages, use 3s, speed 76.51B/s, json 244B, tarball 0B)
[babel-preset-react@^6.11.1] existed at node_modules/.npminstall/babel-preset-react/6.11.1/babel-preset-react (1 packages, use 3s, speed 95.42B/s, json 329B, tarball 0B)
[css-loader@^0.23.1] existed at node_modules/.npminstall/css-loader/0.23.1/css-loader (1 packages, use 4s, speed 93.56B/s, json 407B, tarball 0B)
[babel-preset-react-hmre@^1.1.1] existed at node_modules/.npminstall/babel-preset-react-hmre/1.1.1/babel-preset-react-hmre (1 packages, use 4s, speed 133.33B/s, json 584B, tarball 0B)
[eslint@^3.0.0] existed at node_modules/.npminstall/eslint/3.0.1/eslint (2 packages, use 5s, speed 134.63B/s, json 729B, tarball 0B)
[faker@^3.1.0] installed at node_modules/.npminstall/faker/3.1.0/faker (13 packages, use 7s, speed 186B/s, json 1.78kB, tarball 0B)
[json-loader@^0.5.4] installed at node_modules/.npminstall/json-loader/0.5.4/json-loader (14 packages, use 6s, speed 184.99B/s, json 1.86kB, tarball 0B)
[cross-env@^1.0.8] existed at node_modules/.npminstall/cross-env/1.0.8/cross-env (27 packages, use 13s, speed 241.57B/s, json 3.02kB, tarball 0B)
[eslint-plugin-jsx-a11y@^1.5.3] installed at node_modules/.npminstall/eslint-plugin-jsx-a11y/1.5.5/eslint-plugin-jsx-a11y (29 packages, use 13s, speed 247.9B/s, json 3.17kB, tarball 0B)
[eslint-plugin-react@^5.2.2] installed at node_modules/.npminstall/eslint-plugin-react/5.2.2/eslint-plugin-react (30 packages, use 16s, speed 199.89B/s, json 3.66kB, tarball 0B)
[file-loader@^0.9.0] installed at node_modules/.npminstall/file-loader/0.9.0/file-loader (55 packages, use 22s, speed 247.57B/s, json 6.04kB, tarball 0B)
[less-loader@^2.2.3] installed at node_modules/.npminstall/less-loader/2.2.3/less-loader (70 packages, use 27s, speed 204.95B/s, json 7.41kB, tarball 0B)
[postcss-modules-values@^1.1.3] existed at node_modules/.npminstall/postcss-modules-values/1.1.3/postcss-modules-values (70 packages, use 18s, speed 207.21B/s, json 7.5kB, tarball 0B)
[nyc@^6.6.1] installed at node_modules/.npminstall/nyc/6.6.1/nyc (82 packages, use 28s, speed 219.98B/s, json 8.66kB, tarball 0B)
[eslint-plugin-import@^1.10.1] installed at node_modules/.npminstall/eslint-plugin-import/1.10.3/eslint-plugin-import (131 packages, use 54s, speed 276.8B/s, json 14.69kB, tarball 0B)
ResponseTimeoutError: Request timeout for 60000ms, GET https://registry.npmjs.com/enzyme/%3E%3D2.3.0%20%3C3.0.0 -1 (connected: true, keepalive socket: false)
headers: {}, GET http://10.8.25.7:7001/enzyme/%3E%3D2.3.0%20%3C3.0.0 -1 (connected: true, keepalive socket: false)
headers: {}
ResponseTimeoutError: Request timeout for 60000ms, GET https://registry.npmjs.com/enzyme/%3E%3D2.3.0%20%3C3.0.0 -1 (connected: true, keepalive socket: false)
headers: {}, GET http://10.8.25.7:7001/enzyme/%3E%3D2.3.0%20%3C3.0.0 -1 (connected: true, keepalive socket: false)
headers: {}
    at Timeout._onTimeout (/home/iotahele/.nvm/versions/node/v6.2.2/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:653:13)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

please notice this message:

```
ResponseTimeoutError: Request timeout for 60000ms, GET https://registry.npmjs.com/enzyme/%3E%3D2.3.0%20%3C3.0.0 -1 (connected: true, keepalive socket: false)
```

some package was installed. Not all.

when I run `cnpm install` again and again. It always appear in my screen.

I try to run `cnpm sync react` to sync package, but it doesn't works.

So, it's my fault? how to solve it?

Thanks.

**Comment by fengmk2** [comment]
You should set `sourceNpmRegistry` to https://registry.npm.taobao.org .

**Comment by AnnatarHe** [comment]
It's my config in `npmjs.org/config/config.js`,

```js
module.exports = {
    admins: {
        'foo': "foo@foo.com"
    },
    scopes: ['@foo'],
    sourceNpmRegistry: "https://registry.npm.taobao.org",
    syncModel: "exist"
}
```
It doesn't work.

when I run `cnpm install`, I got this:

```
ResponseTimeoutError: Request timeout for 60000ms, GET http://10.8.25.7:7001/has-ansi/%3E%3D2.0.0%20%3C3.0.0 -1 (connected: true, keepalive socket: true)
headers: {}
ResponseTimeoutError: Request timeout for 60000ms, GET http://10.8.25.7:7001/has-ansi/%3E%3D2.0.0%20%3C3.0.0 -1 (connected: true, keepalive socket: true)
headers: {}
```
